// Season data
const SEASON = {
    totalBets: 226,
    settled: 207,
    open: 18,
    voided: 2,
    staked: 2269.65,
    settledStaked: 2107.15,
    openStaked: 162.50,
    returned: 2454.99,
    pl: 347.84,
    roi: 16.5,
    winners: 23
};

const TOURNAMENTS = [
    { name: "AMEX", bets: 11, staked: 100, returned: 10, pl: -90, phase: 1 },
    { name: "Farmers", bets: 20, staked: 142, returned: 0, pl: -142, phase: 1 },
    { name: "WM Open", bets: 13, staked: 87.50, returned: 0, pl: -87.50, phase: 1 },
    { name: "Genesis", bets: 16, staked: 160, returned: 114.40, pl: -45.60, phase: 2 },
    { name: "Cognizant", bets: 17, staked: 184.50, returned: 526.25, pl: 341.75, phase: 2 },
    { name: "Arnold Palmer", bets: 22, staked: 192.50, returned: 243.60, pl: 51.10, phase: 2 },
    { name: "Puerto Rico", bets: 9, staked: 100, returned: 295, pl: 195, phase: 2 },
    { name: "Players", bets: 17, staked: 125, returned: 15, pl: -110, phase: 2 },
    { name: "Valspar", bets: 11, staked: 85, returned: 0, pl: -85, phase: 2 },
    { name: "Houston", bets: 11, staked: 130, returned: 72, pl: -58, phase: 2, status: "settled" },
    { name: "Valero", bets: 17, staked: 126.25, returned: 43.20, pl: -83.05, phase: 2, status: "settled" },
    { name: "Masters", bets: 28, staked: 524.40, returned: 1092.04, pl: 567.64, phase: 2, status: "settled" },
    { name: "RBC Heritage", bets: 15, staked: 150, returned: 43.50, pl: -106.50, phase: 2, status: "settled" },
];

const WINNERS = [
    { tournament: "Genesis", player: "Collin Morikawa", market: "Top 10", odds: "+210", stake: 20, ret: 62, pl: 42 },
    { tournament: "Genesis", player: "Tommy Fleetwood", market: "Top 10", odds: "+162", stake: 20, ret: 52.40, pl: 32.40 },
    { tournament: "Cognizant", player: "Nico Echavarria", market: "E/W 1/4 5pl", odds: "+5000", stake: 10, ret: 322.50, pl: 312.50 },
    { tournament: "Cognizant", player: "Keith Mitchell", market: "E/W 1/5 8pl", odds: "+2500", stake: 15, ret: 45, pl: 30 },
    { tournament: "Cognizant", player: "Austin Smotherman", market: "E/W 1/4 5pl", odds: "+10000", stake: 2.50, ret: 158.75, pl: 156.25 },
    { tournament: "Arnold Palmer", player: "Collin Morikawa", market: "Top 10", odds: "+230", stake: 10, ret: 33, pl: 23 },
    { tournament: "Puerto Rico", player: "Ricky Castillo", market: "E/W 1/4 5pl", odds: "+2200", stake: 20, ret: 295, pl: 275 },
    { tournament: "Arnold Palmer", player: "Conners/Bhatia", market: "2-Ball Parlay", odds: "+200", stake: 10, ret: 30, pl: 20 },
    { tournament: "Arnold Palmer", player: "Chris Gotterup", market: "72H vs Thomas", odds: "-110", stake: 10, ret: 19.10, pl: 9.10 },
    { tournament: "Arnold Palmer", player: "DFS Lineup", market: "GPP", odds: "-", stake: 20, ret: 144, pl: 124 },
    { tournament: "Houston", player: "Nicolai Hojgaard", market: "E/W 1/4 5pl", odds: "+2500", stake: 20, ret: 72, pl: 52 },
    { tournament: "Valero", player: "DFS Lineup", market: "GPP", odds: "-", stake: 10, ret: 43.20, pl: 33.20 },
    { tournament: "Masters", player: "Justin Rose", market: "EoR1 Top 10", odds: "+280", stake: 10, ret: 38, pl: 28 },
    { tournament: "Masters", player: "Patrick Reed", market: "FRL E/W Placed", odds: "+3500 1/4", stake: 10, ret: 48.75, pl: 38.75 },
    { tournament: "Masters", player: "Zach Johnson", market: "Top Senior", odds: "-102", stake: 40.40, ret: 80, pl: 39.60 },
    { tournament: "Masters", player: "Jacob Bridgeman", market: "3-Ball R1 DH", odds: "+120", stake: 20, ret: 22, pl: 2 },
    { tournament: "Masters", player: "Russell Henley", market: "Top 20", odds: "+102", stake: 20, ret: 40.40, pl: 20.40 },
    { tournament: "Masters", player: "Russell Henley", market: "E/W Placed T3", odds: "+3500 1/5", stake: 10, ret: 40, pl: 30 },
    { tournament: "Masters", player: "DFS Lineup", market: "GPP", odds: "-", stake: 109, ret: 750, pl: 641 },
    { tournament: "Masters", player: "McNealy/Henley", market: "R3 Matchup Parlay", odds: "+164", stake: 20, ret: 52.89, pl: 32.89 },
    { tournament: "Masters", player: "Sam Stevens", market: "Top Debutant DH", odds: "-", stake: 5, ret: 20, pl: 15 },
    { tournament: "RBC Heritage", player: "DFS Lineup", market: "GPP", odds: "-", stake: 10, ret: 43.50, pl: 33.50 },
];

const MARKETS = [
    { type: "Outright E/W", bets: 61, pl: 197, roi: 30.2 },
    { type: "FRL", bets: 54, pl: -116, roi: -29.2 },
    { type: "Props", bets: 26, pl: 47.40, roi: 9.0 },
    { type: "DFS", bets: 7, pl: 743, roi: 263.5 },
    { type: "Matchups/Parlays", bets: 7, pl: -5.01, roi: -7.2 },
    { type: "3-Ball", bets: 6, pl: -76, roi: -63.3 },
    { type: "Pool", bets: 1, pl: -50, roi: -100 },
];

const EW_TERMS = [
    { terms: "E/W 1/4 5pl", bets: 23, pl: 590.25, roi: 293.7 },
    { terms: "E/W 1/5 8pl", bets: 11, pl: -61, roi: -52.6 },
    { terms: "E/W 1/5 5pl", bets: 18, pl: -130, roi: -100 },
    { terms: "E/W 1/5 10pl", bets: 6, pl: -35, roi: -100 },
];

// Current Houston card
const HOUSTON_CARD = [
    { num: 1, player: "Nicolai Hojgaard", market: "Outright", terms: "1/4 5pl", odds: "+2500", stake: 20, placed: "Mar 25", edge: "Meta #3", status: "2nd (-16) PLACE $72", result: "Won" },
    { num: 2, player: "Kurt Kitayama", market: "Outright", terms: "1/4 5pl", odds: "+2800", stake: 20, placed: "Mar 25", edge: "APP #1 + 30% boost", status: "T60 (-1)", result: "Lost" },
    { num: 3, player: "Adam Scott", market: "Outright", terms: "1/4 5pl", odds: "+4000", stake: 10, placed: "Mar 25", edge: "Meta #2", status: "T21 (-8)", result: "Lost" },
    { num: 4, player: "Keith Mitchell", market: "Outright", terms: "1/5 8pl", odds: "+3500", stake: 10, placed: "Mar 25", edge: "APP+OTT double", status: "T14 (-10)", result: "Lost" },
    { num: 5, player: "Wyndham Clark", market: "Outright", terms: "1/5 8pl", odds: "+3500", stake: 10, placed: "Mar 25", edge: "T5 2025 + form", status: "MC", result: "Lost" },
    { num: 6, player: "Stephan Jaeger", market: "Outright", terms: "1/5 8pl", odds: "+4500", stake: 10, placed: "Mar 25", edge: "2024 winner", status: "T28 (-7)", result: "Lost" },
    { num: 7, player: "Max Greyserman", market: "Outright", terms: "1/5 8pl", odds: "+5500", stake: 10, placed: "Mar 25", edge: "T7 2024", status: "MC", result: "Lost" },
    { num: 8, player: "Kurt Kitayama", market: "FRL", terms: "1/4 5pl", odds: "+4000", stake: 10, placed: "Mar 25", edge: "5/5 filter", status: "Lost", result: "Lost" },
    { num: 9, player: "Nicolai Hojgaard", market: "FRL", terms: "1/4 5pl", odds: "+3500", stake: 10, placed: "Mar 25", edge: "5/5 filter", status: "Lost", result: "Lost" },
    { num: 10, player: "Keith Mitchell", market: "FRL", terms: "1/4 5pl", odds: "+4500", stake: 10, placed: "Mar 25", edge: "4/5 + history", status: "Lost", result: "Lost" },
    { num: 11, player: "Alejandro Tosti", market: "FRL", terms: "1/4 5pl", odds: "+8000", stake: 10, placed: "Mar 25", edge: "Co-FRL 2025", status: "Lost", result: "Lost" },
];

const MASTERS_CARD = [
    { num: 1, player: "Akshay Bhatia", market: "Outright", terms: "1/5 10pl", odds: "+5500", book: "b365", stake: 10, placed: "Mar 8", t10s: 0, comp: "#15", status: "MC +6 (Lost)" },
    { num: 2, player: "Bryson DeChambeau", market: "Outright", terms: "1/4 5pl", odds: "+1400", book: "b365", stake: 20, placed: "Mar 8", t10s: 2, comp: "#23", status: "MC +6 (Lost)" },
    { num: 3, player: "Adam Scott", market: "Outright", terms: "1/4 5pl", odds: "+8000", book: "b365", stake: 10, placed: "Mar 27", t10s: 3, comp: "#19", status: "T24 -2 (Lost)" },
    { num: 4, player: "Jason Day", market: "Outright", terms: "1/4 5pl", odds: "+7000", book: "b365", stake: 10, placed: "Mar 27", t10s: 4, comp: "#29", status: "T12 -5 (Lost)" },
    { num: 5, player: "Russell Henley", market: "Prop", terms: "Top 20", odds: "+102", book: "DK", stake: 20, placed: "Apr 5", t10s: 1, comp: "#8", status: "WON T3 +$20.40" },
    { num: 6, player: "Corey Conners", market: "Prop", terms: "Top 20", odds: "+172", book: "DK", stake: 20, placed: "Apr 5", t10s: 4, comp: "#12", status: "T49 +6 (Lost)" },
    { num: 7, player: "Tommy Fleetwood", market: "Outright", terms: "E/W 1/4 5pl", odds: "+2200", book: "b365", stake: 20, placed: "Apr 5", t10s: 1, comp: "#4", status: "T33 E (Lost)" },
    { num: 8, player: "Justin Rose", market: "EoR1 Top 10", terms: "Win", odds: "+280", book: "DK", stake: 10, placed: "Apr 8", t10s: 0, comp: "-", status: "WON +$28" },
    { num: 9, player: "Justin Rose", market: "FRL", terms: "E/W 1/4 5pl", odds: "+3000", book: "b365", stake: 10, placed: "Apr 8", t10s: 0, comp: "-", status: "Lost (T6 R1)" },
    { num: 10, player: "Nicolai Hojgaard", market: "FRL", terms: "E/W 1/4 5pl", odds: "+5000", book: "b365", stake: 10, placed: "Apr 8", t10s: 0, comp: "#5 TOT", status: "Lost (R1 76)" },
    { num: 11, player: "Michael Kim", market: "FRL", terms: "E/W 1/4 5pl", odds: "+9000", book: "b365", stake: 5, placed: "Apr 8", t10s: 0, comp: "-", status: "Lost" },
    { num: 12, player: "Zach Johnson", market: "Prop", terms: "Top Senior", odds: "-102", book: "DK", stake: 40.40, placed: "Apr 9", t10s: 0, comp: "-", status: "WON +$39.60" },
    { num: 13, player: "Si Woo Kim", market: "FRL", terms: "E/W 1/4 5pl", odds: "+3500", book: "b365", stake: 10, placed: "Apr 9", t10s: 0, comp: "#11 TOT", status: "Lost (R1 75)" },
    { num: 14, player: "Patrick Reed", market: "FRL", terms: "E/W 1/4 5pl", odds: "+3500", book: "b365", stake: 10, placed: "Apr 9", t10s: 0, comp: "-", status: "Placed +$38.75" },
    { num: 15, player: "Nicolai Hojgaard", market: "Prop", terms: "Top Dane", odds: "+106", book: "DK", stake: 20, placed: "Apr 9", t10s: 0, comp: "#15 TOT", status: "Lost (R.Hojgaard beat)" },
    { num: 16, player: "Fifa Laopakdee", market: "Prop", terms: "Low Amateur", odds: "+350", book: "Fanatics", stake: 10, placed: "Apr 9", t10s: 0, comp: "-", status: "Lost (MC)" },
    { num: 17, player: "Carlos Ortiz", market: "Outright", terms: "E/W 1/4 5pl", odds: "+16000", book: "b365", stake: 5, placed: "Apr 9", t10s: 0, comp: "#25 TOT", status: "MC +11 (Lost)" },
    { num: 18, player: "Patrick Reed", market: "Prop", terms: "Top 10", odds: "+350", book: "FD", stake: 20, placed: "Apr 9", t10s: 0, comp: "-", status: "T12 -5 (Lost)" },
    { num: 19, player: "Patrick Reed", market: "Outright", terms: "E/W 1/5 10pl", odds: "+2500", book: "b365", stake: 10, placed: "Apr 9", t10s: 0, comp: "-", status: "T12 -5 (Lost)" },
    { num: 20, player: "Russell Henley", market: "Outright", terms: "E/W 1/5 10pl", odds: "+3500", book: "b365", stake: 10, placed: "Apr 9", t10s: 1, comp: "#8", status: "Placed T3 +$30" },
    { num: 21, player: "Corey Conners", market: "3-Ball R1", terms: "Win", odds: "+130", book: "b365", stake: 20, placed: "Apr 7", t10s: 4, comp: "#40", status: "Lost (Brennan won)" },
    { num: 22, player: "Jacob Bridgeman", market: "3-Ball R1", terms: "Win", odds: "+120", book: "b365", stake: 20, placed: "Apr 7", t10s: 0, comp: "#39", status: "Tied (DH +$2)" },
    { num: 23, player: "Conners/Bridgeman", market: "3-Ball Parlay", terms: "R1 Double", odds: "+406", book: "b365", stake: 10, placed: "Apr 7", t10s: 0, comp: "-", status: "Lost (Conners leg)" },
    { num: 24, player: "DFS Lineup", market: "DFS", terms: "GPP", odds: "-", book: "DK", stake: 109, placed: "Apr 7", t10s: 0, comp: "-", status: "WON +$641" },
    { num: 25, player: "Masters Pools", market: "Pool", terms: "3 entries", odds: "-", book: "Pool", stake: 50, placed: "Apr 7", t10s: 0, comp: "-", status: "Lost" },
    { num: 26, player: "Conners/Aberg/N.Hojgaard", market: "Parlay", terms: "R1 Top Nationality", odds: "+573", book: "b365", stake: 10, placed: "Apr 7", t10s: 0, comp: "-", status: "Lost (Taylor won CAN)" },
    { num: 27, player: "McNealy/Henley", market: "Matchup Parlay", terms: "R3 2-Ball", odds: "+164", book: "b365", stake: 20, placed: "Apr 11", t10s: 0, comp: "-", status: "WON +$32.89" },
    { num: 28, player: "Sam Stevens", market: "Prop", terms: "Top Debutant", odds: "+1100", book: "DK", stake: 5, placed: "Apr 9", t10s: 0, comp: "-", status: "DH Won +$15" },
];

// Futures + Major Championship Early Locks
const FUTURES = [
    { player: "Xander Schauffele", market: "Outright", terms: "Win", odds: "+2250", book: "DK", stake: 10, placed: "Apr 12, 2026", event: "2027 Masters", status: "Open" },
    { player: "Brooks Koepka", market: "Outright", terms: "Win", odds: "+3500", book: "DK", stake: 10, placed: "Apr 12, 2026", event: "2027 Masters", status: "Open" },
    { player: "Russell Henley", market: "Outright", terms: "E/W 1/5 10pl", odds: "+2800", book: "b365", stake: 20, placed: "Apr 12, 2026", event: "2026 PGA Championship", status: "Open" },
    { player: "Matt Fitzpatrick", market: "Outright", terms: "E/W 1/5 10pl", odds: "+2200", book: "b365", stake: 20, placed: "Apr 12, 2026", event: "2026 PGA Championship", status: "Open" },
    { player: "Tommy Fleetwood", market: "Outright", terms: "E/W 1/5 10pl", odds: "+1800", book: "b365", stake: 20, placed: "Apr 12, 2026", event: "2026 PGA Championship", status: "Cashed $20 (void/push)" },
    { player: "Hideki Matsuyama", market: "Outright", terms: "E/W 1/4 5pl", odds: "+4000", book: "b365", stake: 10, placed: "Apr 12, 2026", event: "2026 PGA Championship", status: "Open" },
    { player: "Hideki Matsuyama", market: "Outright", terms: "E/W 1/4 5pl", odds: "+5000", book: "b365", stake: 10, placed: "Apr 12, 2026", event: "2026 US Open", status: "Open" },
    { player: "Russell Henley", market: "Outright", terms: "E/W 1/4 5pl", odds: "+5000", book: "b365", stake: 10, placed: "Apr 12, 2026", event: "2026 US Open", status: "Open" },
    { player: "Tony Finau", market: "Outright", terms: "E/W 1/4 5pl", odds: "+8000", book: "b365", stake: 10, placed: "Apr 13, 2026", event: "2026 PGA Championship", status: "Open" },
];

const RBC_CARD = [
    { num: 1, player: "Ryo Hisatsune", market: "Outright", terms: "Win", odds: "+10500", book: "DK", stake: 5, placed: "Apr 12", t10s: 0, comp: "M avg #11.7", status: "Lost (T60 -3)", result: "Lost" },
    { num: 2, player: "Brian Harman", market: "Outright", terms: "Win", odds: "+12500", book: "DK", stake: 5, placed: "Apr 12", t10s: 0, comp: "T3 2025. M7 #9", status: "Lost (T25 -8)", result: "Lost" },
    { num: 3, player: "Daniel Berger", market: "Outright", terms: "E/W 1/5 8pl", odds: "+6000", book: "b365", stake: 10, placed: "Apr 13", t10s: 0, comp: "T3 2025. Noonan pick", status: "Lost (T42 -6)", result: "Lost" },
    { num: 4, player: "Sungjae Im", market: "Outright", terms: "E/W 1/5 8pl", odds: "+10000", book: "b365", stake: 10, placed: "Apr 13", t10s: 0, comp: "Noonan E/W pick. T11 2025", status: "Lost (T42 -6)", result: "Lost" },
    { num: 8, player: "Russell Henley", market: "Outright", terms: "E/W 1/5 8pl", odds: "+1600", book: "b365", stake: 40, placed: "Apr 13", t10s: 0, comp: "DG #4. TAILWIND 1.87x. T8 2025. 7-model #3.6", status: "Lost (T25 -8)", result: "Lost" },
    { num: 9, player: "Lucas Glover", market: "Outright", terms: "E/W 1/5 10pl", odds: "+22500", book: "b365", stake: 5, placed: "Apr 13", t10s: 0, comp: "APP #8 comp 5yr. TAILWIND 2.15", status: "Lost (T42 -6)", result: "Lost" },
    { num: 10, player: "Tom Hoge", market: "Outright", terms: "E/W 1/5 10pl", odds: "+35000", book: "b365", stake: 5, placed: "Apr 13", t10s: 0, comp: "APP #5 comp 5yr. TAILWIND 1.29", status: "Lost (T71 E)", result: "Lost" },
    { num: 11, player: "Jacob Bridgeman", market: "FRL", terms: "E/W 1/4 5pl", odds: "+4000", book: "b365", stake: 10, placed: "Apr 13", t10s: 0, comp: "Poa Triv PUTT #1. Bent +0.72", status: "Lost (R1 75)", result: "Lost" },
    { num: 12, player: "Denny McCarthy", market: "FRL", terms: "E/W 1/4 5pl", odds: "+8000", book: "b365", stake: 10, placed: "Apr 13", t10s: 0, comp: "Poa Triv SG:SG #1. PUTT #3", status: "Lost (R1 74)", result: "Lost" },
    { num: 5, player: "Ryo Hisatsune", market: "Prop", terms: "Top 10", odds: "+500", book: "DK", stake: 5, placed: "Apr 13", t10s: 0, comp: "M avg #11.7. T18 2025", status: "Lost (T60 -3)", result: "Lost" },
    { num: 6, player: "Brian Harman", market: "Prop", terms: "Top 10", odds: "+530", book: "DK", stake: 5, placed: "Apr 13", t10s: 0, comp: "T3 2025. M7 #9", status: "Lost (T25 -8)", result: "Lost" },
    { num: 7, player: "Sungjae Im", market: "FRL", terms: "E/W 1/4 5pl", odds: "+7000", book: "b365", stake: 10, placed: "Apr 13", t10s: 0, comp: "Noonan pick. T11 2025", status: "Lost (R1 66 T13)", result: "Lost" },
    { num: 13, player: "Min Woo Lee", market: "FRL", terms: "E/W 1/4 5pl", odds: "+5850", book: "b365", stake: 10, placed: "Apr 14", t10s: 0, comp: "30% boost (+4500 base). DG FRL +EV 13.9%. Mayo 110/1", status: "Lost (R1 70 T50)", result: "Lost" },
    { num: 14, player: "Chris Gotterup", market: "Outright", terms: "E/W 1/5 3pl", odds: "+8000", book: "b365", stake: 10, placed: "Apr 15", t10s: 0, comp: "T10 2025 Harbour Town. Composite #28", status: "Lost (T25 -8)", result: "Lost" },
    { num: 15, player: "DFS Lineup", market: "DFS", terms: "GPP", odds: "-", book: "DK", stake: 10, placed: "Apr 16", t10s: 0, comp: "Cashed $43.50 on $10 buy-in (+$33.50)", status: "Won +$33.50", result: "Won" },
];

const ZURICH_CARD = [
    { num: 1, player: "Smalley / Springer", market: "Team Outright", terms: "Win", odds: "+2800", book: "DK", stake: 10, placed: "Apr 20", t10s: 0, comp: "Model #1 composite. Balanced 5/12. Haslbauer value flag.", status: "Open" },
    { num: 2, player: "Smotherman / Putnam", market: "Team Outright", terms: "Win", odds: "+4400", book: "DK", stake: 10, placed: "Apr 20", t10s: 0, comp: "Model #4. Balanced 17/23. Putnam 3.25x surger.", status: "Open" },
    { num: 3, player: "McCarty / Meissner", market: "Team Outright", terms: "Win", odds: "+2450", book: "DK", stake: 10, placed: "Apr 20", t10s: 0, comp: "Model #5. Haslbauer target. Top 10 BoB.", status: "Open" },
    { num: 4, player: "Silverman / Champ", market: "Team Outright", terms: "Win", odds: "+8200", book: "DK", stake: 5, placed: "Apr 20", t10s: 0, comp: "Model #2. Balanced 9/18. Biggest price-vs-model gap on board.", status: "Open" },
];

const MIAMI_CARD = [
    { num: 1, player: "Sungjae Im", market: "Outright", terms: "Win", odds: "+10000", book: "DK", stake: 5, placed: "Apr 24", t10s: 0, comp: "RH model #40. Bermuda + irons baseline.", status: "Open" },
    { num: 2, player: "Chris Gotterup", market: "Outright", terms: "Win", odds: "+3500", book: "DK", stake: 5, placed: "Apr 26 AM", t10s: 0, comp: "RH #3 + Mayo top tier + Titanic pick. Triple-confirm.", status: "Open" },
    { num: 3, player: "Jake Knapp", market: "Outright", terms: "Win", odds: "+3700", book: "DK", stake: 5, placed: "Apr 26", t10s: 0, comp: "Mayo + Titanic narrative. Distance + iron play. RH model #38.", status: "Open" },
    { num: 4, player: "Chris Gotterup", market: "Outright", terms: "Win", odds: "+3500", book: "DK", stake: 5, placed: "Apr 26 PM", t10s: 0, comp: "Second ticket — total $10 exposure on Gotterup at +3500.", status: "Open" },
    { num: 5, player: "Sepp Straka", market: "Outright", terms: "Win", odds: "+5500", book: "DK", stake: 5, placed: "Apr 26", t10s: 0, comp: "Mayo deep dart + Titanic pick. Florida + iron + putter risk (Leishman comp).", status: "Open" },
    { num: 6, player: "Aldrich Potgieter", market: "Outright", terms: "Win", odds: "+17500", book: "DK", stake: 2.50, placed: "Apr 26", t10s: 0, comp: "Titanic dart. Pure bombing thesis. RH #62, DG 0.26x extreme fader — variance lottery.", status: "Open" },
];

const VALERO_CARD = [
    { num: 1, player: "A.J. Ewart", market: "Outright", terms: "Win", odds: "+34000", book: "DK", stake: 1.25, placed: "Mar 28", edge: "Comp #2. Dark horse.", status: "T30 (-7)", result: "Lost" },
    { num: 2, player: "Will Zalatoris", market: "Outright", terms: "Win", odds: "+7800", book: "DK", stake: 5, placed: "Mar 28", edge: "Comp #4. APP elite.", status: "MC (-1)", result: "Lost" },
    { num: 3, player: "Sudarshan Yellamaraju", market: "Outright", terms: "Win", odds: "+14000", book: "DK", stake: 2.50, placed: "Mar 28", edge: "Comp #9. Dark horse.", status: "T21 (-9)", result: "Lost" },
    { num: 4, player: "Mackenzie Hughes", market: "Outright", terms: "Win", odds: "+11500", book: "DK", stake: 2.50, placed: "Mar 28", edge: "Comp #5. Course fit.", status: "T63 (E)", result: "Lost" },
    { num: 5, player: "Maverick McNealy", market: "Outright", terms: "Win", odds: "+2400", book: "DK", stake: 10, placed: "Mar 29", edge: "Comp #4. Klos #2. +6 gap.", status: "T21 (-9)", result: "Lost" },
    { num: 6, player: "Maverick McNealy", market: "Top 10", terms: "Win", odds: "+225", book: "DK", stake: 10, placed: "Mar 29", edge: "Comp #4. T10 13.5%.", status: "T21 (-9)", result: "Lost" },
    { num: 7, player: "Denny McCarthy", market: "Outright", terms: "1/5 8pl", odds: "+3000", book: "b365", stake: 10, placed: "Mar 30", edge: "TPC SA #2 history. PUTT#1 2025.", status: "MC (-1)", result: "Lost" },
    { num: 8, player: "Sam Ryder", market: "FRL", terms: "1/4 5pl", odds: "+12500", book: "b365", stake: 5, placed: "Mar 31", edge: "TAILWIND 1.91. 2025 FRL winner (63).", status: "T21 (-9)", result: "Lost" },
    { num: 9, player: "Ryo Hisatsune", market: "FRL", terms: "1/4 5pl", odds: "+4000", book: "b365", stake: 5, placed: "Mar 31", edge: "Expert #8. APP+ARG dual. Rick loves.", status: "T8 (-13)", result: "Lost" },
    { num: 10, player: "Thorbjorn Olesen", market: "FRL", terms: "1/4 5pl", odds: "+5000", book: "b365", stake: 5, placed: "Mar 31", edge: "2025 SG:TOT#5. APP#7 6mo.", status: "T54 (-3)", result: "Lost" },
    { num: 11, player: "Mac Meissner", market: "FRL", terms: "1/4 5pl", odds: "+6000", book: "b365", stake: 5, placed: "Mar 31", edge: "Andy2 #6. AM wave. Dark horse.", status: "T30 (-7)", result: "Lost" },
    { num: 12, player: "Chad Ramey", market: "FRL", terms: "1/4 5pl", odds: "+8000", book: "b365", stake: 5, placed: "Mar 31", edge: "PUTT#6. V25 SG:TOT#8.", status: "T39 (-5)", result: "Lost" },
    { num: 13, player: "DFS Lineup", market: "DFS", terms: "GPP", odds: "-", book: "DK", stake: 10, placed: "Mar 31", edge: "Si Woo/Hisatsune/Olesen/Smalley/Novak/Svensson", status: "2nd $43.20", result: "Won" },
    { num: 14, player: "Hideki Matsuyama", market: "Outright", terms: "1/4 5pl", odds: "+2200", book: "b365", stake: 20, placed: "Apr 1", edge: "30% BOOST. APP+ARG dual. Expert #4.", status: "T21 (-9)", result: "Lost" },
    { num: 15, player: "Alex Noren", market: "Outright", terms: "1/5 8pl", odds: "+3300", book: "b365", stake: 10, placed: "Apr 1", edge: "TAILWIND 1.24. Wind #6. Andy2 #4.", status: "T30 (-7)", result: "Lost" },
    { num: 16, player: "Christiaan Bezuidenhout", market: "Outright", terms: "1/5 8pl", odds: "+6000", book: "b365", stake: 10, placed: "Apr 1", edge: "4 signals. ARG#7 PUTT#7. TAILWIND.", status: "T49 (-4)", result: "Lost" },
    { num: 17, player: "Bud Cauley", market: "Outright", terms: "1/5 8pl", odds: "+10000", book: "b365", stake: 10, placed: "Apr 1", edge: "TAILWIND 1.50. V25 SG:TOT#7.", status: "T28 (-8)", result: "Lost" },
];

// Player rotation data
const PLAYERS = {
    active: [
        { name: "Russell Henley", bets: 4, wins: 2, pl: 40.40, roi: 67, note: "Masters T3. Double-cash. Season MVP." },
        { name: "Collin Morikawa", bets: 6, wins: 2, pl: 35, roi: 50 },
        { name: "Ricky Castillo", bets: 3, wins: 1, pl: 270, roi: 1080 },
        { name: "Maverick McNealy", bets: 4, wins: 1, pl: 12.89, roi: 43, note: "Masters R3 parlay cashed. DG edge validated." },
        { name: "Keith Mitchell", bets: 7, wins: 1, pl: -42, roi: -38 },
        { name: "Nicolai Hojgaard", bets: 8, wins: 1, pl: 17, roi: 11, note: "Masters MC but RBC Heritage early dart placed." },
    ],
    onNotice: [
        { name: "Tommy Fleetwood", bets: 5, wins: 1, pl: -22.60, consec: 2, reason: "Masters T33. R4 76 collapse. Was T4 after R2." },
        { name: "Patrick Reed", bets: 4, wins: 1, pl: -1.25, consec: 0, reason: "Masters T12. FRL placed T3 R1. Faded R3-R4." },
        { name: "Sepp Straka", bets: 3, wins: 0, pl: -25, consec: 3, reason: "T8 Players near-miss" },
        { name: "Ryo Hisatsune", bets: 3, wins: 0, pl: -7.50, consec: 3, reason: "T13 Players near-miss" },
        { name: "Pierceson Coody", bets: 3, wins: 0, pl: -15, consec: 2, reason: "Model backing strong" },
        { name: "Haotong Li", bets: 4, wins: 0, pl: -12.50, consec: 2, reason: "WD risk" },
    ],
    benched: [
        { name: "Kurt Kitayama", bets: 8, wins: 0, pl: -80, consec: 8, reason: "0-8 all markets. T60 Houston." },
        { name: "Min Woo Lee", bets: 4, wins: 0, pl: -40, consec: 4, reason: "0-4 all markets" },
        { name: "Ryan Gerard", bets: 4, wins: 0, pl: -30, consec: 4, reason: "0-4 all markets" },
        { name: "Si Woo Kim", bets: 3, wins: 0, pl: -30, consec: 3, reason: "Putting liability" },
        { name: "Max McGreevy", bets: 4, wins: 0, pl: -36, consec: 4, reason: "Over-exposed Cognizant" },
        { name: "Michael Brennan", bets: 3, wins: 0, pl: -17.50, consec: 3, reason: "Long darts not connecting" },
        { name: "Max Greyserman", bets: 1, wins: 0, pl: -10, consec: 1, reason: "MC Houston. Course history thesis failed." },
        { name: "Wyndham Clark", bets: 1, wins: 0, pl: -10, consec: 1, reason: "MC Houston. Form signal didn't translate." },
    ]
};

// Player scouting profiles (game evaluation, not betting)
const SCOUTING = [
    { name:"Scottie Scheffler", tier:"Elite", sg_tot:2.58, app:0.90, ott:0.71, arg:0.40, putt:0.57, putt_bermuda:0.52, putt_bent:0.65, putt_poa:0.48, dd:8.7,
      shape:"Fade", surface:"All", strengths:"Complete game. #1 in world. APP+ARG+PUTT all positive. Par 5 scorer.",
      weaknesses:"None significant. Occasionally loses focus in non-major events.", notes:"2x Masters champion. Withdrew Houston (2nd child). The standard." },
    { name:"Rory McIlroy", tier:"Elite", sg_tot:2.12, app:0.69, ott:0.94, arg:0.19, putt:0.30, putt_bermuda:0.25, putt_bent:0.38, putt_poa:0.22, dd:19.4,
      shape:"Draw", surface:"All", strengths:"Longest elite driver on Tour. APP solid. 2025 Masters champion (career slam).",
      weaknesses:"ARG can leak under pressure (Augusta 2011 collapse). Historically inconsistent with wedges.", notes:"Career Grand Slam completed 2025. Form lukewarm since." },
    { name:"Collin Morikawa", tier:"Elite", sg_tot:1.70, app:0.96, ott:0.73, arg:0.05, putt:-0.04, putt_bermuda:-0.12, putt_bent:0.08, putt_poa:-0.15, dd:2.0,
      shape:"Fade", surface:"Bentgrass best", strengths:"Best iron player on Tour. SG:APP #1 career. Distance control is elite.",
      weaknesses:"Putting. Career SG:PUTT slightly negative. ARG near zero. Not a scrambler.", notes:"Masters T7 (-9). Played through back injury � ball speed down to 172. Walking gingerly per Mayo. Best iron player on Tour when healthy. Harbour Town is perfect for his game IF he plays." },
    { name:"Xander Schauffele", tier:"Elite", sg_tot:1.84, app:0.83, ott:0.60, arg:0.16, putt:0.25, putt_bermuda:0.22, putt_bent:0.3, putt_poa:0.18, dd:11.4,
      shape:"Fade", surface:"All", strengths:"Most balanced elite player. Positive in all 4 SG categories. 2 majors in 2024.",
      weaknesses:"Returning from early-season injury. Putting rank 76th this year — concerning.", notes:"Chasing career slam (needs Masters). Multiple Augusta T10s." },
    { name:"Jordan Spieth", tier:"Contender", sg_tot:0.97, app:0.38, ott:0.09, arg:0.21, putt:0.29, putt_bermuda:0.18, putt_bent:0.42, putt_poa:0.15, dd:6.1,
      shape:"Variable", surface:"Bentgrass best", strengths:"6 Augusta T10s in 11 starts incl 2015 win. Creative short game. Clutch putter. Course knowledge elite. But 2 MCs in last 3.",
      weaknesses:"Ball-striking has deteriorated. OTT +0.09 is below average. Distance disadvantage at long courses.", notes:"Masters T12 (-5). TAILWIND 1.75x worked � made weekend, ground it out. 2022 Harbour Town winner. Short game + course knowledge. Model avg #24.7 for RBC but course history overrides." },
    { name:"Cameron Smith", liv:true, tier:"Contender", sg_tot:0.31, app:-0.25, ott:-0.38, arg:0.48, putt:0.47, putt_bermuda:0.55, putt_bent:0.35, putt_poa:0.28, dd:-8.0,
      shape:"Draw", surface:"Bermuda", strengths:"Par 5 king at Augusta. 5 T10s in 8 starts (T2, T3, T5, T6, T10). Elite short game + putting.",
      weaknesses:"LIV = no recent PGA data. Short hitter. OTT and APP both negative career. Ball-striking is a real weakness.", notes:"At +8000 the LIV discount is real. Also had T55 finishes in 2016 and 2019." },
    { name:"Adam Scott", tier:"Contender", sg_tot:0.91, app:0.60, ott:0.30, arg:0.05, putt:-0.03, putt_bermuda:-0.08, putt_bent:0.12, putt_poa:-0.15, dd:8.2,
      shape:"Draw", surface:"Bentgrass", strengths:"Won Masters 2013. 21 cuts in 23 starts at Augusta. MC in 2025. Ball speed up 4mph in 2026. APP elite.",
      weaknesses:"Age 45. Putting slightly negative career. ARG near zero. May lack closing gear at this stage.", notes:"Masters T24 (-2). Made cut but never threatened. Ball speed up thesis didn't translate to results. +12.5% CLV on our lock but still lost. 45 years old." },
    { name:"Jason Day", tier:"Veteran", sg_tot:0.58, app:-0.06, ott:0.01, arg:0.33, putt:0.29, putt_bermuda:0.22, putt_bent:0.38, putt_poa:0.15, dd:-1.4,
      shape:"Draw", surface:"Bentgrass", strengths:"4 Augusta T10s in 12 starts (T2, 3rd, T10, T5). Also 2 MCs. SG:ARG +0.33 elite at hardest ARG course.",
      weaknesses:"Ball-striking has cratered. APP -0.06 and OTT +0.01 are Tour average at best. Current form #53 in composite.", notes:"Masters T12 (-5). T5 through R3 then shot 75 R4. History play worked to a point but couldn't close. R4 fade pattern. ARG still elite (+1.04 at Masters) but ball-striking too weak for consistent contention." },
    { name:"Kurt Kitayama", tier:"Contender", sg_tot:1.17, app:0.69, ott:0.57, arg:-0.01, putt:-0.09, putt_bermuda:-0.15, putt_bent:0.05, putt_poa:-0.12, dd:10.2,
      shape:"Fade", surface:"All", strengths:"SG:APP top-10 on Tour. Distance + iron combo is elite. RH models consistently rank him top-5.",
      weaknesses:"Putting. SG:PUTT -0.09 career. ARG -0.01 is neutral. Doesn't surge — steady T15-T25 grinder who rarely wins. 0-for-6 in our tracker.",
      notes:"The model loves him every week but he doesn't convert. Price is always right but form never peaks." },
    { name:"Nicolai Hojgaard", tier:"Contender", sg_tot:1.11, app:0.52, ott:0.36, arg:-0.01, putt:0.23, putt_bermuda:0.18, putt_bent:0.28, putt_poa:0.22, dd:14.3,
      shape:"Fade", surface:"Poa/Bent", strengths:"Distance + APP + positive putting. Versatile across course types. Top-10 in all 5 RH models at Houston.",
      weaknesses:"ARG slightly negative. No Augusta history. Still developing consistency — can MC unexpectedly.", notes:"Masters MC (+6). Small Augusta sample concern proved valid. Market had shortened massively pre-Masters but it didn't matter. RBC Heritage model avg #28 � mixed. ON CARD at +6800." },
    { name:"Stephan Jaeger", tier:"Mid-field", sg_tot:0.40, app:0.10, ott:-0.22, arg:0.27, putt:0.26, putt_bermuda:0.2, putt_bent:0.3, putt_poa:0.25, dd:5.7,
      shape:"Straight", surface:"Poa", strengths:"2024 Houston winner. ARG +0.27 elite. Putting positive. Textbook weakness-masked player.",
      weaknesses:"OTT -0.22 (terrible driver). APP +0.10 is below average. Only works at courses that mask driving.", notes:"TAILWIND 1.31x is strongest recent form in the field. The weakness-masked thesis is proven by his own 2024 win." },
    { name:"Ben Griffin", tier:"Mid-field", sg_tot:1.05, app:0.35, ott:-0.04, arg:0.28, putt:0.46, putt_bermuda:0.38, putt_bent:0.45, putt_poa:0.42, dd:0.1,
      shape:"Draw", surface:"Poa", strengths:"ARG + PUTT combo = elite short game. Well-rounded without a glaring weakness.",
      weaknesses:"Not a bomber (DrDist +0.1). OTT slightly negative. Doesn't have the distance for the longest courses.", notes:"Masters T33 (E). ARG +2.78 was elite that week. Short game player. Harbour Town model avg #32.7 � models don't love him here despite ARG fit." },
    { name:"Wyndham Clark", tier:"Contender", sg_tot:0.62, app:0.30, ott:0.03, arg:0.27, putt:0.02, putt_bermuda:-0.05, putt_bent:0.08, putt_poa:0.02, dd:8.4,
      shape:"Fade", surface:"All", strengths:"ARG +0.27 amplified at short-grass courses. T5 Houston 2025. TAILWIND 1.29x = surging form.",
      weaknesses:"OTT and PUTT both near zero. Not an elite ball-striker or putter. Relies on form momentum.", notes:"2023 US Open champion. Form-dependent player whose ceiling is very high when everything clicks." },
    { name:"Tommy Fleetwood", tier:"Contender", sg_tot:1.73, app:0.66, ott:0.49, arg:0.33, putt:0.24, putt_bermuda:0.18, putt_bent:0.28, putt_poa:0.2, dd:1.4,
      shape:"Draw", surface:"All", strengths:"Complete game. Positive in all 4 SG categories. APP+ARG combo elite. 5yr-comp #7 at Augusta correlated courses.",
      weaknesses:"Hasn't won a major. Can be passive in final rounds. Not the longest off the tee.", notes:"Masters T33 (E). Collapsed R4 with 76 after being T4 through R2. R4 fade pattern confirmed. T7 at Harbour Town 2025. 3-model avg #6.0 for RBC. ARG#1 on Tour but Sunday closability is a concern." },
    { name:"Russell Henley", tier:"Contender", sg_tot:1.56, app:0.60, ott:0.29, arg:0.29, putt:0.38, putt_bermuda:0.32, putt_bent:0.45, putt_poa:0.28, dd:-8.4,
      shape:"Fade", surface:"Bentgrass best", strengths:"APP+ARG+PUTT all positive = complete short-game player. 5yr-comp ARG #4 at Augusta courses. Lag putting elite.",
      weaknesses:"Short hitter (DrDist -8.4). OTT +0.29 is modest. Distance disadvantage at long courses.", notes:"Masters T3 (-10). Shot 66-68 weekend. T20 prop + E/W place both cashed (+$50.40). Season MVP. T8 at Harbour Town 2025. 3-model avg #2.7 for RBC Heritage. Perennially underpriced � market is learning." },
    { name:"Corey Conners", tier:"Contender", sg_tot:0.83, app:0.56, ott:0.47, arg:-0.06, putt:-0.15, putt_bermuda:-0.22, putt_bent:-0.1, putt_poa:-0.18, dd:-1.6,
      shape:"Fade", surface:"All", strengths:"Iron play is elite (APP +0.56). OTT +0.47 = good total driving. 2x Valero champion. 3-for-3 Augusta T10s.",
      weaknesses:"Putting is a real problem (-0.15 career). ARG -0.06. The flat stick consistently costs him.", notes:"Masters T49 (+6). Disappointing. T20 prop lost. T49 at Harbour Town 2025 too. Model avg #26 for RBC � wide range. Iron play elite but putting kills him." },
    { name:"Patrick Cantlay", tier:"Contender", sg_tot:1.30, app:0.56, ott:0.47, arg:0.15, putt:0.11, putt_bermuda:0.08, putt_bent:0.15, putt_poa:0.05, dd:5.1,
      shape:"Fade", surface:"All", strengths:"5yr-comp TOT #6 at Augusta-correlated courses. Balanced game. 4 Augusta T10s. Steady under pressure.",
      weaknesses:"Not a bomber. Form has dipped (1mo rank outside top-15). Market has drifted him to +6600.", notes:"Masters T12 (-5). Shot 66-66 R3-R4 weekend surge. T13 at Harbour Town 2025. 3-model avg #11.7 for RBC. Perennial HT contender (3rd, 3rd, T13)." },
    { name:"Will Zalatoris", tier:"Contender", sg_tot:0.66, app:0.54, ott:0.30, arg:0.05, putt:-0.23, putt_bermuda:-0.3, putt_bent:0.18, putt_poa:-0.25, dd:4.0,
      shape:"Fade", surface:"Bentgrass", strengths:"Approach is elite. 3 T10s in 3 Augusta starts (2nd, T6, T9). Born for Augusta. Bentgrass putter.",
      weaknesses:"Seasonal putting is terrible (-0.23). Injury history (back). Form has been poor since returning.", notes:"At +10000 the history is extraordinary but current form is a real question." },
    { name:"Ludvig Aberg", tier:"Elite", sg_tot:1.62, app:0.59, ott:0.62, arg:0.12, putt:0.29, putt_bermuda:0.25, putt_bent:0.32, putt_poa:0.22, dd:12.2,
      shape:"Fade", surface:"All", strengths:"Elite everything. T2 at Augusta on debut (2024). Young, ascending, fearless. Distance + iron combo.",
      weaknesses:"Only 1 Augusta start. ARG +0.12 is modest for the hardest ARG course.", notes:"If anyone is going to break the 'first-timers don't win' rule at Augusta, it's Aberg." },
    { name:"Rickie Fowler", tier:"Veteran", sg_tot:1.18, app:0.34, ott:0.46, arg:0.00, putt:0.38, putt_bermuda:0.35, putt_bent:0.4, putt_poa:0.3, dd:2.2,
      shape:"Draw", surface:"All", strengths:"Putting is a weapon (+0.38). OTT +0.46 is solid. Fan favorite with experience everywhere.",
      weaknesses:"ARG is dead zero. APP +0.34 is decent but not elite. Hasn't won since 2023. Missing Masters pressure.", notes:"Harbour Town T68 (E) in 2025. Poor course history. ON CARD at +5600 but models rank him #37. Bermuda putter better suited for Miami. Dart only." },
    { name:"Max Greyserman", tier:"Mid-field", sg_tot:0.44, app:0.09, ott:-0.23, arg:0.17, putt:0.40, putt_bermuda:0.35, putt_bent:0.42, putt_poa:0.38, dd:6.5,
      shape:"Straight", surface:"Poa", strengths:"PUTT +0.40 is elite. ARG +0.17 fits short-grass courses. T7 Houston 2024 proves weakness-masked thesis.",
      weaknesses:"OTT -0.23 (terrible driver). APP +0.09 (below average). Only works at courses that mask driving.", notes:"Pure short-game player. Only bet at venues where driving accuracy is irrelevant." },
    { name:"Tony Finau", tier:"Contender", sg_tot:0.24, app:0.17, ott:-0.30, arg:0.29, putt:0.08, putt_bermuda:0.05, putt_bent:0.1, putt_poa:0.02, dd:3.6,
      shape:"Draw", surface:"Bermuda", strengths:"ARG +0.29 is elite. 2022 Houston winner + course record 62 twice. 4 Augusta T10s. TAILWIND form surges.",
      weaknesses:"OTT -0.30 has deteriorated significantly. APP +0.17 is below where it was. Distance advantage gone.", notes:"2022 version was elite. 2026 version relies on ARG and venue knowledge. Only play at weakness-masked courses." },
    { name:"Sam Burns", tier:"Contender", sg_tot:1.10, app:0.19, ott:0.30, arg:0.00, putt:0.60, putt_bermuda:0.55, putt_bent:0.62, putt_poa:0.52, dd:8.4,
      shape:"Draw", surface:"Bermuda/Poa", strengths:"SG:PUTT +0.60 = one of the best putters on Tour. Warm 1.14x form. Won Valspar 2022 on putting alone.",
      weaknesses:"APP +0.19 is weak for approach-dominant courses. ARG is dead zero.", notes:"Masters T7 (-9). Bermuda PUTT king (+0.55). NOT a Harbour Town fit (putter-dependent, small greens neutral). Save him for Miami Championship (Blue Monster Bermuda = his course)." },
    { name:"Maverick McNealy", tier:"Mid-field", sg_tot:1.34, app:0.44, ott:0.43, arg:0.17, putt:0.29, putt_bermuda:0.25, putt_bent:0.32, putt_poa:0.22, dd:6.8,
      shape:"Fade", surface:"All", strengths:"Well-rounded. All 4 SG categories positive. T3 Valero 2025. Rising steadily in world rankings.",
      weaknesses:"No signature strength that separates. Jack of all trades, master of none.", notes:"Masters T18 (-4). Won us R3 matchup parlay (+$32.89). DG edge play validated all week. T3 at Harbour Town 2025. 3-model avg #13.3 for RBC." },
    { name:"Michael Thorbjornsen", tier:"Mid-field", sg_tot:0.98, app:0.31, ott:0.60, arg:0.05, putt:0.03, putt_bermuda:-0.02, putt_bent:0.05, putt_poa:0.02, dd:10.5,
      shape:"Fade", surface:"All", strengths:"Elite driver (OTT +0.60, DrDist +10.5). Young bomber with ceiling. Houston blind #9.",
      weaknesses:"APP +0.31 is good not great. ARG +0.05 and PUTT +0.03 near zero. No major pedigree yet.", notes:"Future star. Not ready for Augusta yet (no wins, no major T6). Valero/Houston type courses suit him now." },
    { name:"Keith Mitchell", tier:"Mid-field", sg_tot:0.86, app:0.45, ott:0.56, arg:-0.03, putt:-0.12, putt_bermuda:-0.18, putt_bent:-0.08, putt_poa:-0.12, dd:9.5,
      shape:"Fade", surface:"Poa", strengths:"APP+OTT double fit at long approach courses. Co-FRL Houston 2025. DG win edge at Houston.",
      weaknesses:"Putting -0.12 and ARG -0.03 both negative. Short game is the hole.", notes:"Best when both approach AND driving are amplified (Memorial Park, long courses). Don't play at scrambling courses." },
    { name:"Ricky Castillo", tier:"Mid-field", sg_tot:0.65, app:0.14, ott:0.36, arg:0.05, putt:0.10, putt_bermuda:0.08, putt_bent:0.12, putt_poa:0.05, dd:7.9,
      shape:"Draw", surface:"Paspalum/Bermuda", strengths:"Won Puerto Rico 2026 at +2200 = our biggest single win. Grinder who capitalizes in weaker fields.",
      weaknesses:"APP +0.14 is below average. Not competitive at Signature Events or majors.", notes:"Opposite-field specialist. Don't bet him at full-field events against elite players." },
    { name:"Jon Rahm", liv:true, tier:"Elite", sg_tot:2.17, app:0.84, ott:0.79, arg:0.29, putt:0.26, putt_bermuda:0.2, putt_bent:0.32, putt_poa:0.18, dd:12.6,
      shape:"Draw", surface:"All", strengths:"Elite ball-striker with top-tier APP and OTT. Positive in all 4 SG categories. Complete game with no exploitable weakness.",
      weaknesses:"LIV schedule limits PGA Tour data recency. ARG and PUTT positive but not dominant.", notes:"Former world #1. 2 majors. LIV defection creates massive odds discount when eligible for majors." },
    { name:"Min Woo Lee", tier:"Contender", sg_tot:1.63, app:0.29, ott:0.63, arg:0.33, putt:0.38, putt_bermuda:0.32, putt_bent:0.4, putt_poa:0.35, dd:12.9,
      shape:"Draw", surface:"All", strengths:"Strong putter (+0.38) and elite ARG (+0.33). Long off the tee with bomber distance. Well-rounded short game.",
      weaknesses:"APP +0.29 is below average for his tier. Iron play is the gap in an otherwise strong profile.", notes:"Explosive young talent. Distance + short game combo is rare. Benched in our tracker (0-4 all markets)." },
    { name:"Jake Knapp", tier:"Contender", sg_tot:1.20, app:0.11, ott:0.44, arg:0.05, putt:0.60, putt_bermuda:0.52, putt_bent:0.62, putt_poa:0.58, dd:13.0,
      shape:"Fade", surface:"Poa", strengths:"Elite putter (+0.60 = one of the best on Tour). Bomber distance (DrDist +13.0). OTT +0.44 solid.",
      weaknesses:"APP +0.11 is well below average. ARG +0.05 near zero. Iron play and scrambling are real weaknesses.", notes:"Putt-dependent player. Only viable at putting-dominant courses (Copperhead type). Poa surface specialist." },
    { name:"Hideki Matsuyama", tier:"Contender", sg_tot:1.35, app:0.62, ott:-0.01, arg:0.45, putt:0.28, putt_bermuda:0.22, putt_bent:0.35, putt_poa:0.18, dd:-0.9,
      shape:"Fade", surface:"Bentgrass", strengths:"Elite iron player (APP +0.62) and scrambler (ARG +0.45). Putting positive. 2021 Masters champion.",
      weaknesses:"OTT -0.01 is essentially Tour average. Not a bomber (DrDist -0.9). Driving is the clear weak link.", notes:"Masters T12 (-5). Pinnacle shortened 6 straight days pre-Masters � sharp signal was real. We didn't bet him and should have. Lesson: act on Pinnacle signals. PGA Champ E/W locked at +4000." },
    { name:"Cameron Young", tier:"Contender", sg_tot:1.86, app:0.59, ott:0.69, arg:0.13, putt:0.44, putt_bermuda:0.38, putt_bent:0.48, putt_poa:0.35, dd:11.1,
      shape:"Draw", surface:"All", strengths:"Elite ball-striker (APP +0.59, OTT +0.69) with strong putting (+0.44). Bomber distance. One of the most talented non-winners.",
      weaknesses:"ARG +0.13 is modest. Has not converted talent into wins — closing ability is a question mark.", notes:"Masters co-leader after R3 (65) then collapsed R4 (73). Tindall #2, 5 sources converged but couldn't close. Bomber profile doesn't ideally fit Harbour Town accuracy test." },
    { name:"Shane Lowry", tier:"Contender", sg_tot:0.90, app:0.70, ott:0.14, arg:-0.05, putt:0.11, putt_bermuda:0.08, putt_bent:0.15, putt_poa:0.05, dd:-0.5,
      shape:"Fade", surface:"All", strengths:"Elite iron player (APP +0.70 = top-15 on Tour). 2019 Open champion. Experienced in wind and tough conditions.",
      weaknesses:"ARG -0.05 is slightly negative. Not long off the tee (DrDist -0.5). Putting only slightly positive.", notes:"Approach-dependent player. Best on courses where iron play is the primary separator. Wind-course specialist." },
    { name:"Harris English", tier:"Contender", sg_tot:1.09, app:0.11, ott:0.40, arg:0.12, putt:0.46, putt_bermuda:0.42, putt_bent:0.48, putt_poa:0.38, dd:2.2,
      shape:"Draw", surface:"Bermuda", strengths:"Elite putter (+0.46). Solid driver (OTT +0.40). Bermuda surface specialist. All-around positive SG profile.",
      weaknesses:"APP +0.11 is well below average. Iron play is the clear gap. Over-reliant on the flat stick.", notes:"Harbour Town T66 (-1) in 2025. ON CARD at +5000 but models rank him #49. Poor course history contradicts the narrative. Dart only." },
    { name:"Viktor Hovland", tier:"Contender", sg_tot:1.20, app:0.76, ott:0.10, arg:0.14, putt:0.20, putt_bermuda:0.15, putt_bent:0.25, putt_poa:0.18, dd:0.6,
      shape:"Fade", surface:"All", strengths:"Elite approach play (APP +0.76). Positive in all 4 SG categories. 2-time FedEx Cup champion.",
      weaknesses:"OTT +0.10 and DrDist +0.6 mean he's not long. ARG +0.14 is modest. Short game has been the historical leak.", notes:"Rebuilt short game has stabilized. When putting is on, he's a top-5 player. Approach is the engine." },
    { name:"Matt Fitzpatrick", tier:"Contender", sg_tot:1.69, app:0.67, ott:0.42, arg:0.30, putt:0.29, putt_bermuda:0.25, putt_bent:0.35, putt_poa:0.2, dd:2.7,
      shape:"Fade", surface:"Bentgrass", strengths:"Complete game — positive in all 4 categories. APP +0.67 and ARG +0.30 elite. US Open champion (2022).",
      weaknesses:"Not a bomber (DrDist +2.7). OTT +0.42 is good but not elite. Distance disadvantage at long courses.", notes:"2023 Harbour Town winner. Masters T21 (-3). 3-model avg #3.7 for RBC Heritage (M6 #1 in APP-heavy build). Elite accuracy profile for short courses." },
    { name:"Si Woo Kim", tier:"Contender", sg_tot:1.52, app:0.81, ott:0.66, arg:0.24, putt:-0.19, putt_bermuda:-0.25, putt_bent:-0.12, putt_poa:-0.18, dd:-2.7,
      shape:"Variable", surface:"All", strengths:"Elite ball-striker — APP +0.81 and OTT +0.66 are both top-tier. ARG +0.24 solid. Shot-shaping ability is rare.",
      weaknesses:"Putting is a real liability (-0.19). Short hitter (DrDist -2.7). The flat stick consistently costs him.", notes:"Masters T47 (+4). Made cut barely. Mayo: 'If there was ever a tournament Si Woo was going to win, it would be this one.' T8 Harbour Town 2025. Ball-striking best year of career. 3-model avg #4.3." },
    { name:"Sungjae Im", tier:"Mid-field", sg_tot:0.52, app:-0.20, ott:0.09, arg:0.41, putt:0.22, putt_bermuda:0.18, putt_bent:0.25, putt_poa:0.15, dd:-2.3,
      shape:"Draw", surface:"Bermuda", strengths:"Elite scrambler (ARG +0.41). Positive putter (+0.22). Bermuda specialist. Iron man — never misses events.",
      weaknesses:"APP -0.20 is a significant weakness. OTT +0.09 near average. Ball-striking overall is below par.", notes:"Short-game-only player. Only viable at courses where ARG is amplified and approach is forgiven." },
    { name:"Robert MacIntyre", tier:"Contender", sg_tot:1.61, app:0.22, ott:0.52, arg:0.23, putt:0.64, putt_bermuda:0.58, putt_bent:0.65, putt_poa:0.55, dd:3.7,
      shape:"Draw", surface:"All", strengths:"Elite putter (+0.64 = top-5 on Tour). Strong driver (OTT +0.52). Positive in all 4 SG categories.",
      weaknesses:"APP +0.22 is below average for his talent level. Iron play is the clear gap in the profile.", notes:"Scottish left-hander. Putting carries the game. When approach is even slightly on, he contends anywhere." },
    { name:"Chris Gotterup", tier:"Contender", sg_tot:1.09, app:0.40, ott:0.49, arg:0.08, putt:0.12, putt_bermuda:0.08, putt_bent:0.15, putt_poa:0.1, dd:16.2,
      shape:"Draw", surface:"All", strengths:"Longest hitter in our database (DrDist +16.2). OTT +0.49 and APP +0.40 both solid. Positive in all 4 categories.",
      weaknesses:"ARG +0.08 and PUTT +0.12 near neutral. Short game doesn't match the ball-striking.", notes:"Pure bomber. Won our Arnold Palmer matchup vs Thomas. Best at courses where distance creates separation." },
    { name:"Marco Penge", tier:"Mid-field", sg_tot:0.52, app:0.04, ott:0.83, arg:-0.22, putt:-0.14, putt_bermuda:-0.08, putt_bent:-0.12, putt_poa:-0.05, dd:20.2,
      shape:"Fade", surface:"All", strengths:"Extreme bomber — OTT +0.83 and DrDist +20.2 are elite. Longest driver in the database by a wide margin.",
      weaknesses:"Everything else. APP +0.04 near zero, ARG -0.22 and PUTT -0.14 both negative. All-or-nothing distance player.", notes:"Only viable at courses where extreme distance creates enough advantage to offset poor short game." },
    { name:"J.J. Spaun", tier:"Mid-field", sg_tot:1.10, app:0.64, ott:0.44, arg:0.07, putt:-0.05, putt_bermuda:-0.08, putt_bent:0.02, putt_poa:-0.05, dd:2.6,
      shape:"Fade", surface:"All", strengths:"Elite approach play (APP +0.64). OTT +0.44 solid. Ball-striking combo is strong.",
      weaknesses:"Putting slightly negative (-0.05). ARG +0.07 near zero. Short game doesn't support the iron play.", notes:"Underrated approach specialist. Profile is similar to Kitayama — great irons, weak putter, steady grinder." },
    { name:"Sepp Straka", tier:"Contender", sg_tot:1.09, app:0.60, ott:0.33, arg:0.05, putt:0.12, putt_bermuda:0.08, putt_bent:0.15, putt_poa:0.1, dd:-0.2,
      shape:"Fade", surface:"All", strengths:"Elite iron player (APP +0.60). Positive in all 4 SG categories. Reliable ball-striker.",
      weaknesses:"ARG +0.05 and PUTT +0.12 are modest. Not a bomber (DrDist -0.2). Short game is functional not special.", notes:"Model avg #14.7 for RBC Heritage (top 18 all 3 models). Positive in every stat. Mayo: 'always there.' +5200." },
    { name:"Alex Noren", tier:"Mid-field", sg_tot:1.00, app:0.33, ott:-0.06, arg:0.28, putt:0.44, putt_bermuda:0.38, putt_bent:0.48, putt_poa:0.4, dd:-6.3,
      shape:"Fade", surface:"All", strengths:"Strong putter (+0.44) and solid scrambler (ARG +0.28). Short game is the weapon.",
      weaknesses:"OTT -0.06 slightly negative. DrDist -6.3 means he's one of the shorter hitters. Distance disadvantage is real.", notes:"Short-game specialist. Best at tight courses where accuracy matters more than length." },
    { name:"Justin Thomas", tier:"Contender", sg_tot:0.96, app:0.36, ott:-0.12, arg:0.41, putt:0.31, putt_bermuda:0.28, putt_bent:0.35, putt_poa:0.22, dd:5.6,
      shape:"Fade", surface:"All", strengths:"Elite scrambler (ARG +0.41) and strong putter (+0.31). 2 majors. Short game has compensated for ball-striking decline.",
      weaknesses:"OTT -0.12 has deteriorated significantly from peak. APP +0.36 is good not great. The driver is the problem.", notes:"Post-peak JT. The talent is still there but OTT decline is concerning. ARG carries the game now." },
    { name:"Denny McCarthy", tier:"Mid-field", sg_tot:0.22, app:0.05, ott:-0.29, arg:0.09, putt:0.36, putt_bermuda:0.32, putt_bent:0.38, putt_poa:0.3, dd:-4.0,
      shape:"Straight", surface:"Bermuda", strengths:"Strong putter (+0.36). Bermuda surface specialist. Straight ball flight is consistent.",
      weaknesses:"OTT -0.29 is a major weakness. APP +0.05 near zero. Ball-striking is well below Tour average.", notes:"Pure putter. Only viable at courses where driving and approach are both masked. Very narrow range of fits." },
    { name:"Jordan Smith", tier:"Mid-field", sg_tot:0.76, app:0.34, ott:0.49, arg:-0.04, putt:-0.03, putt_bermuda:-0.08, putt_bent:0.02, putt_poa:-0.05, dd:5.2,
      shape:"Draw", surface:"All", strengths:"Solid driver (OTT +0.49, DrDist +5.2). APP +0.34 decent. Ball-striking is the strength.",
      weaknesses:"ARG -0.04 and PUTT -0.03 both slightly negative. Short game is the weak link.", notes:"Ball-striking-only player. Needs courses that reward driving and approach over scrambling and putting." },
    { name:"Tom Hoge", tier:"Mid-field", sg_tot:0.48, app:0.09, ott:0.40, arg:-0.08, putt:-0.09, putt_bermuda:-0.12, putt_bent:-0.05, putt_poa:-0.08, dd:5.8,
      shape:"Fade", surface:"All", strengths:"Solid driver (OTT +0.40, DrDist +5.8). Positional off the tee.",
      weaknesses:"APP +0.09, ARG -0.08, PUTT -0.09 — approach, scrambling, and putting all near zero or negative.", notes:"Driving-only player. Very narrow profile. Only works at venues where OTT is the primary separator." },
    { name:"Pierceson Coody", tier:"Mid-field", sg_tot:0.75, app:0.32, ott:0.61, arg:-0.15, putt:-0.03, putt_bermuda:-0.08, putt_bent:0.02, putt_poa:-0.05, dd:13.7,
      shape:"Fade", surface:"All", strengths:"Strong driver (OTT +0.61) and bomber distance (DrDist +13.7). APP +0.32 is decent.",
      weaknesses:"ARG -0.15 is a real weakness. PUTT -0.03 near zero. Scrambling is the hole in the game.", notes:"On Notice in our tracker. Young bomber whose short game needs development. Model backing remains strong." },
    { name:"Sahith Theegala", tier:"Contender", sg_tot:0.91, app:0.46, ott:0.01, arg:0.20, putt:0.24, putt_bermuda:0.2, putt_bent:0.28, putt_poa:0.18, dd:3.9,
      shape:"Draw", surface:"All", strengths:"Balanced game — positive in all 4 SG categories. APP +0.46 is strong. ARG and PUTT both solid.",
      weaknesses:"OTT +0.01 is essentially average. DrDist +3.9 modest. Not a bomber — no distance edge.", notes:"Well-liked by narratives. Complete game without a signature elite category. Fan favorite with closing ability." },
    { name:"Ryan Fox", tier:"Mid-field", sg_tot:0.54, app:0.18, ott:0.12, arg:0.10, putt:0.14, putt_bermuda:0.1, putt_bent:0.18, putt_poa:0.12, dd:9.1,
      shape:"Draw", surface:"All", strengths:"Bomber distance (DrDist +9.1). All 4 SG categories positive. No glaring weakness.",
      weaknesses:"No elite category either. APP +0.18, OTT +0.12, ARG +0.10, PUTT +0.14 all modest.", notes:"Jack of all trades, master of none. Kiwi who performs best at international events and bomber tracks." },
    { name:"Davis Thompson", tier:"Mid-field", sg_tot:0.71, app:0.38, ott:0.46, arg:0.08, putt:-0.20, putt_bermuda:-0.25, putt_bent:-0.15, putt_poa:-0.2, dd:3.4,
      shape:"Fade", surface:"All", strengths:"Strong ball-striker (APP +0.38, OTT +0.46). Good total driving package.",
      weaknesses:"Putting is a major weakness (-0.20). ARG +0.08 near zero. The flat stick consistently costs him contention.", notes:"Young ball-striker whose putting holds him back. Profile is similar to early-career Morikawa — irons carry, putter drags." },
    { name:"Nico Echavarria", tier:"Mid-field", sg_tot:0.45, app:0.21, ott:0.12, arg:-0.11, putt:0.23, putt_bermuda:0.28, putt_bent:0.18, putt_poa:0.15, dd:-5.3,
      shape:"Draw", surface:"Bermuda", strengths:"Bermuda putter. Won Cognizant 2026 at 50/1. Can contend at penalty courses.",
      weaknesses:"ARG negative. OTT modest. Not competitive at long bomber courses.", notes:"Our biggest winner. E/W 1/4 5pl $10 returned $322.50. Bermuda-putting specialist." },
    { name:"Alex Smalley", tier:"Mid-field", sg_tot:0.70, app:0.28, ott:0.37, arg:0.04, putt:0.00, putt_bermuda:-0.05, putt_bent:0.05, putt_poa:-0.02, dd:4.9,
      shape:"Fade", surface:"All", strengths:"Balanced ball-striker. OTT +0.37 is solid. Consistent mid-field performer.",
      weaknesses:"Putting is dead neutral. No standout skill that separates. ARG near zero.", notes:"Steady but unspectacular. Comp-course data often ranks him 20-30." },
    { name:"Austin Smotherman", tier:"Mid-field", sg_tot:0.52, app:0.48, ott:0.41, arg:-0.12, putt:-0.26, putt_bermuda:-0.22, putt_bent:-0.28, putt_poa:-0.25, dd:4.2,
      shape:"Fade", surface:"All", strengths:"APP +0.48 is quietly elite. OTT solid. Won FRL at Cognizant at +10000. Ball-striking can go very low.",
      weaknesses:"Putting is terrible (-0.26). ARG negative. Short game is the hole.", notes:"Our Cognizant FRL winner at +10000 ($2.50 returned $158.75). Ball-striker whose putter limits his ceiling." },
    { name:"Aldrich Potgieter", tier:"Mid-field", sg_tot:-0.20, app:-0.23, ott:0.54, arg:-0.31, putt:-0.21, putt_bermuda:-0.18, putt_bent:-0.22, putt_poa:-0.20, dd:22.0,
      shape:"Draw", surface:"All", strengths:"Longest driver in any field he enters (DrDist +22.0). Pure bomber.",
      weaknesses:"Everything except distance. APP, ARG, PUTT all negative. Can't hit greens, can't scramble, can't putt.", notes:"Long drive specialist, not a golfer yet. Mayo: 'better off in long drive competitions until he refines his game.'" },
    { name:"Brian Harman", tier:"Veteran", sg_tot:0.34, app:-0.04, ott:-0.12, arg:0.18, putt:0.32, putt_bermuda:0.35, putt_bent:0.28, putt_poa:0.25, dd:-8.5,
      shape:"Draw", surface:"Bermuda", strengths:"2023 Open champion. 2025 Valero winner in brutal wind. Elite putter. Short game carries.",
      weaknesses:"OTT and APP both negative. Short hitter. Only wins when conditions are brutal and ball-strikers fail.", notes:"T3 at Harbour Town 2025. ON CARD at +12500. Chips and putts for a living. Mayo impressed by Masters R2 comeback. Course horse at this price." },
    { name:"Eric Cole", tier:"Mid-field", sg_tot:0.12, app:0.14, ott:-0.56, arg:0.21, putt:0.33, putt_bermuda:0.28, putt_bent:0.35, putt_poa:0.30, dd:-1.8,
      shape:"Straight", surface:"Poa", strengths:"SG:PUTT +0.33 is elite. ARG +0.21 positive. Short game specialist.",
      weaknesses:"OTT -0.56 is terrible. Shortest driver on Tour. Only works at courses where driving is irrelevant.", notes:"Putter-only play. Bet at Valspar (+11000) on Poa putting thesis. MC'd." },
    { name:"Alejandro Tosti", tier:"Mid-field", sg_tot:-0.01, app:0.05, ott:0.10, arg:-0.05, putt:-0.08, putt_bermuda:-0.10, putt_bent:-0.05, putt_poa:-0.08, dd:5.5,
      shape:"Draw", surface:"All", strengths:"Co-FRL at Houston 2025 (opened 65, T5 finish). Can go low in R1.",
      weaknesses:"Everything is near zero. No standout skill. Relies on hot weeks.", notes:"Houston FRL dart. TAILWIND 1.89x form ratio (highest in field). Results haven't matched the form signal." },
    { name:"Bud Cauley", tier:"Mid-field", sg_tot:0.26, app:0.268, ott:0.001, arg:0.093, putt:-0.099, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-3.5,
      shape:"Unknown", surface:"Unknown", strengths:"2025 Valero SG:TOT #7, APP#13. DG TAILWIND 1.47. Course specialist.",
      weaknesses:"Not on any RH model top-20. Putting slightly negative.", notes:"Titanic pick at +8000 b365. 2025 TPC SA data validates the thesis." },
    { name:"Rico Hoey", tier:"Mid-field", sg_tot:0.57, app:0.438, ott:0.643, arg:-0.147, putt:-0.364, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:6.1,
      shape:"Draw", surface:"Unknown", strengths:"2025 Valero APP #2 in entire field. OTT +0.64 is elite distance. Approach is the weapon.",
      weaknesses:"PUTT -0.36 is terrible. ARG -0.15 negative. Short game is a black hole.", notes:"Mayo + Rick Gehman both like him this week. At +6600 b365 the approach upside is real if he can putt neutral." },
    { name:"Tom Kim", tier:"Mid-field", sg_tot:0.38, app:0.239, ott:-0.170, arg:0.209, putt:0.099, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-3.5,
      shape:"Fade", surface:"Unknown", strengths:"Well-rounded without an elite skill. ARG positive. 7-for-7 cuts in 2026.",
      weaknesses:"OTT -0.17 is below average. DG HEADWIND 0.72 at TPC SA. 2025 Valero SG:TOT #127 (+4).", notes:"DG form 0.98 neutral. Bad course history. At +10000 b365." },
    { name:"Nick Taylor", tier:"Mid-field", sg_tot:0.62, app:0.377, ott:-0.125, arg:0.292, putt:0.078, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-5.9,
      shape:"Unknown", surface:"Unknown", strengths:"ARG +0.29 is elite. APP +0.38 solid. DG course history +0.155.",
      weaknesses:"OTT -0.13, short hitter (DD -5.9).", notes:"Mayo's favorite Canadian for Harbour Town. 8 consecutive events gaining on approach. ARG elite. Model avg #27. +8200." },
    { name:"Chris Kirk", tier:"Mid-field", sg_tot:0.13, app:0.246, ott:0.046, arg:0.023, putt:-0.183, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-1.9,
      shape:"Unknown", surface:"Unknown", strengths:"TPC SA course history. Titanic pick at 90/1.",
      weaknesses:"PUTT -0.18 is bad. DG form 0.88 cool. 6mo TOT #84.", notes:"DG TAILWIND 1.66 + course history +0.310. Sharp disagree between form (cool) and history (elite)." },
    { name:"Matt Wallace", tier:"Mid-field", sg_tot:0.40, app:0.220, ott:0.029, arg:0.177, putt:-0.023, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-0.3,
      shape:"Unknown", surface:"Unknown", strengths:"ARG +0.18 is solid. Balanced game.",
      weaknesses:"Nothing elite. APP +0.22 is average.", notes:"At +8000 b365." },
    { name:"Doug Ghim", tier:"Mid-field", sg_tot:0.25, app:0.215, ott:0.268, arg:0.053, putt:-0.284, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0.8,
      shape:"Unknown", surface:"Unknown", strengths:"OTT +0.27. Wind #50 in 5yr data.",
      weaknesses:"PUTT -0.28 is terrible.", notes:"At +12500 b365." },
    { name:"Johnny Keefer", tier:"Mid-field", sg_tot:0.42, app:0.248, ott:0.565, arg:-0.242, putt:-0.148, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:11.0,
      shape:"Unknown", surface:"Unknown", strengths:"OTT +0.57 is elite distance. DD +11.0 is a bomber.",
      weaknesses:"ARG -0.24 is bad. Approach is average.", notes:"At +4500 b365. Bomber profile." },
    { name:"Christiaan Bezuidenhout", tier:"Mid-field", sg_tot:0.66, app:0.29, ott:-0.24, arg:0.29, putt:0.31, putt_bermuda:0.25, putt_bent:0.35, putt_poa:0.28, dd:-11.9,
      shape:"Fade", surface:"Bentgrass", strengths:"ARG +0.29 and PUTT +0.31 = elite short game combo. Positive in both.",
      weaknesses:"OTT -0.24 and DrDist -11.9. Shortest hitter in most fields. Distance disadvantage is severe.", notes:"South African with short-game feel. Only bet at courses that mask driving. Valero composite #18." },
    { name:"Mackenzie Hughes", tier:"Mid-field", sg_tot:0.22, app:0.01, ott:-0.22, arg:0.25, putt:0.19, putt_bermuda:0.15, putt_bent:0.22, putt_poa:0.18, dd:-3.1,
      shape:"Fade", surface:"All", strengths:"ARG +0.25 is strong. Putting positive. Short game grinder.",
      weaknesses:"APP +0.01 (Tour average). OTT -0.22 (poor driver). Can't ball-strike.", notes:"Valero composite #5 from comp-course data. TAILWIND 1.26x form. $2.50 DK bet at +11500." },
    { name:"Matti Schmid", tier:"Mid-field", sg_tot:0.14, app:-0.20, ott:0.17, arg:-0.06, putt:0.23, putt_bermuda:0.20, putt_bent:0.25, putt_poa:0.18, dd:8.1,
      shape:"Draw", surface:"All", strengths:"Putting +0.23 is his weapon. Some distance.",
      weaknesses:"APP -0.20 is a real problem. ARG near zero.", notes:"German with a putter. Limited upside at approach-dominant courses." },
    { name:"Sami Valimaki", tier:"Mid-field", sg_tot:0.03, app:0.08, ott:0.22, arg:-0.07, putt:-0.13, putt_bermuda:-0.10, putt_bent:-0.15, putt_poa:-0.12, dd:6.5,
      shape:"Draw", surface:"All", strengths:"OTT +0.22 gives some driver advantage.",
      weaknesses:"Putting is negative. ARG negative. Below-average game outside of driving.", notes:"Finnish player with some distance. Hasn't consistently performed on PGA Tour." },
    { name:"Justin Rose", tier:"Veteran", sg_tot:0.83, app:0.54, ott:0.11, arg:0.06, putt:0.12, putt_bermuda:0.08, putt_bent:0.15, putt_poa:0.10, dd:2.4,
      shape:"Fade", surface:"Bentgrass", strengths:"5x R1 leader at Augusta (record). APP +0.54 elite. 4 Augusta T10s.",
      weaknesses:"Comp #46 suggests current ability well below pedigree. Can't convert leads into wins.", notes:"Masters T3 (-10). Augusta history thesis validated again. EoR1 T10 cashed. FRL placed concern (T6). At 45, still shows up at courses he knows." },
    { name:"Ryan Gerard", tier:"Mid-field", sg_tot:1.27, app:0.80, ott:0.51, arg:0.01, putt:-0.05, putt_bermuda:-0.08, putt_bent:-0.02, putt_poa:0.48, dd:1.6,
      shape:"Fade", surface:"Poa", strengths:"SG:APP +0.80 is top-10 on Tour. Elite iron player. Poa putting is his best surface (+0.48).",
      weaknesses:"ARG +0.01 and PUTT -0.05 overall. Can't chip or putt on most surfaces. Burned out from overplaying.", notes:"Model avg #16.3 for RBC Heritage. M6 #12 (APP-heavy). Mayo top 10 in his model. Young player trending up after Masters T15 (-4)." },
    { name:"Jacob Bridgeman", tier:"Contender", sg_tot:1.36, app:0.30, ott:0.23, arg:0.15, putt:0.69, putt_bermuda:0.62, putt_bent:0.72, putt_poa:0.65, dd:3.1,
      shape:"Draw", surface:"All", strengths:"Best putter on Tour (SG:PUTT +0.69). Positive everywhere. Complete game.",
      weaknesses:"Not the longest. APP +0.30 is good not elite. Relatively unproven at majors.", notes:"Made cut at first Masters (T41, +2). Shot 71 R1. Model avg #26 for RBC. Mayo: 'this course fits him a lot more than other courses.'" },
    { name:"Haotong Li", tier:"Mid-field", sg_tot:0.49, app:0.29, ott:0.37, arg:-0.18, putt:0.00, putt_bermuda:-0.05, putt_bent:0.05, putt_poa:-0.02, dd:5.4,
      shape:"Draw", surface:"All", strengths:"Ball-striking combo (APP +0.29, OTT +0.37) is solid. Distance.",
      weaknesses:"ARG -0.18. Putting dead flat. Short game is a real hole.", notes:"On Notice in our tracker. WD risk (withdrew AP Inv). Inconsistent availability." },
    { name:"A.J. Ewart", tier:"Mid-field", sg_tot:0.15, app:-0.07, ott:0.11, arg:-0.25, putt:0.08, putt_bermuda:0.05, putt_bent:0.10, putt_poa:0.06, dd:10.3,
      shape:"Draw", surface:"All", strengths:"Some distance. Comp-course data ranks him surprisingly high.",
      weaknesses:"ARG -0.25 is poor. APP negative. Limited Tour pedigree.", notes:"Valero dark horse ($1.25 at +34000). Comp 6mo #4 at correlated courses. Anti-bias protocol find." },
    { name:"Akshay Bhatia", tier:"Contender", sg_tot:1.44, app:0.74, ott:0.22, arg:0.06, putt:0.41, putt_bermuda:0.45, putt_bent:0.38, putt_poa:0.35, dd:1.4,
      shape:"Draw", surface:"Bermuda", strengths:"APP +0.74 elite. PUTT +0.41 (Bermuda best). Won AP Inv 2026 and Valero 2024.",
      weaknesses:"OTT +0.22 modest. ARG near zero. No Augusta pedigree.", notes:"Masters MC (+6). DG HEADWIND confirmed. +36% CLV on our lock was nice but the bet lost. India trip circadian concern was valid." },
    { name:"Daniel Berger", tier:"Contender", sg_tot:0.69, app:0.63, ott:0.38, arg:-0.22, putt:-0.09, putt_bermuda:-0.12, putt_bent:-0.05, putt_poa:-0.08, dd:1.9,
      shape:"Fade", surface:"All", strengths:"APP +0.63 is elite. Comp 6mo #3 and 3yr #7 at Valero correlated courses.",
      weaknesses:"PUTT and ARG both negative. Short game is a hole. Back injury history.", notes:"T3 at Harbour Town 2025. Model avg #19. +9400. Nobody is talking about him. Sleeper." },
    { name:"Lucas Glover", tier:"Veteran", sg_tot:0.06, app:0.28, ott:0.01, arg:0.06, putt:-0.29, putt_bermuda:-0.32, putt_bent:-0.25, putt_poa:-0.28, dd:-2.0,
      shape:"Fade", surface:"All", strengths:"TPC SA SG:TOT #11 over 16 rounds. APP #8 at the venue. Course specialist.",
      weaknesses:"Putting is terrible (-0.29). Overall game has declined significantly.", notes:"Form ratio 2.31x (highest on Tour) but from a very low baseline. Veteran grinding on course knowledge." },
    { name:"Mac Meissner", tier:"Mid-field", sg_tot:0.68, app:0.41, ott:0.12, arg:0.15, putt:-0.00, putt_bermuda:-0.03, putt_bent:0.02, putt_poa:-0.01, dd:2.6,
      shape:"Fade", surface:"All", strengths:"APP +0.41 solid. ARG +0.15 positive. Balanced ball-striker.",
      weaknesses:"Not a bomber (DrDist +2.6). Putting dead flat. No distance advantage.", notes:"Mayo's model #1 pick at Valspar. Shot 62 in 2025 at TPC SA." },
    { name:"Matt Kuchar", tier:"Veteran", sg_tot:-0.07, app:-0.07, ott:-0.39, arg:0.18, putt:0.21, putt_bermuda:0.18, putt_bent:0.22, putt_poa:0.15, dd:-5.0,
      shape:"Fade", surface:"All", strengths:"TPC SA SG:TOT #3 over 18 rounds. ARG +0.18. Veteran course knowledge.",
      weaknesses:"APP and OTT both negative. Game has declined significantly. Short hitter.", notes:"18 rounds of strong TPC SA data. Pure course-knowledge play at the Valero. Not viable elsewhere." },
    { name:"Matt McCarty", tier:"Mid-field", sg_tot:0.73, app:0.12, ott:0.19, arg:-0.01, putt:0.42, putt_bermuda:0.38, putt_bent:0.45, putt_poa:0.40, dd:-2.7,
      shape:"Straight", surface:"Poa", strengths:"PUTT +0.42 is elite. Best putter at Valspar comp rank #2 on Poa surfaces.",
      weaknesses:"APP +0.12 is below average. No ball-striking edge.", notes:"Valspar bet at +6600. Putting weapon on Poa Triv greens." },
    { name:"Max McGreevy", tier:"Mid-field", sg_tot:0.63, app:0.30, ott:0.47, arg:-0.01, putt:-0.13, putt_bermuda:-0.10, putt_bent:-0.15, putt_poa:-0.12, dd:-3.0,
      shape:"Fade", surface:"All", strengths:"OTT +0.47 gives some driver advantage. APP +0.30 is decent.",
      weaknesses:"Putting is negative (-0.13). ARG near zero.", notes:"Benched (0-4 including 0-3 at Cognizant). Over-exposed in early season." },
    { name:"Michael Brennan", tier:"Mid-field", sg_tot:0.57, app:0.11, ott:0.30, arg:-0.04, putt:0.21, putt_bermuda:0.18, putt_bent:0.23, putt_poa:0.20, dd:10.7,
      shape:"Draw", surface:"All", strengths:"Carry distance elite. RH Model 15 #2 (carry + prox 200+). Can win at bomber courses.",
      weaknesses:"APP +0.11 is weak. ARG near zero. Relies on distance.", notes:"Benched (0-3). Houston composite dark horse. Mayo and Stewart both mentioned as live. ARG concern at short-grass courses." },
    { name:"Patrick Reed", tour:"other", tier:"Veteran", sg_tot:0.79, app:0.50, ott:-0.04, arg:0.16, putt:0.16, putt_bermuda:0.20, putt_bent:0.12, putt_poa:0.15, dd:-4.1,
      shape:"Draw", surface:"Bermuda", strengths:"Won Masters 2018 on ARG + PUTT. 4 Augusta T10s. Major pedigree on Bermuda.",
      weaknesses:"OTT -0.04 poor. LIV = no recent PGA data. Game has declined.", notes:"Masters T12 (-5). FRL placed T3 R1 (+$38.75). Faded R3-R4 (72-73). TAILWIND thesis worked early but not late. DP World Tour / Asian Tour � not PGA, not LIV. Plays majors only on PGA side." },
    { name:"Sam Stevens", tier:"Mid-field", sg_tot:0.92, app:0.28, ott:0.55, arg:0.11, putt:-0.02, putt_bermuda:-0.05, putt_bent:0.02, putt_poa:-0.03, dd:5.7,
      shape:"Fade", surface:"All", strengths:"OTT +0.55 is strong. Well-rounded ball-striker. SG:TOT +0.92 is solid.",
      weaknesses:"Putting slightly negative. Not a separator with the flatstick.", notes:"TPC SA SG:TOT #7 over 10 rounds. Neutral form. Consistent without being spectacular." },
    { name:"Sudarshan Yellamaraju", tier:"Mid-field", sg_tot:0.37, app:0.04, ott:0.26, arg:-0.04, putt:0.09, putt_bermuda:0.06, putt_bent:0.12, putt_poa:0.08, dd:8.6,
      shape:"Draw", surface:"All", strengths:"Some distance. Comp-course models consistently rank him in the 20-35 range.",
      weaknesses:"APP +0.04 is Tour average. ARG slightly negative. No elite skill.", notes:"Anti-bias protocol dark horse. Ghost ownership. $2.50 Valero at +14000 and Houston analysis flagged him at T7." },
    { name:"Taylor Pendrith", tier:"Contender", sg_tot:0.94, app:0.29, ott:0.49, arg:0.11, putt:0.04, putt_bermuda:0.02, putt_bent:0.06, putt_poa:0.03, dd:10.7,
      shape:"Fade", surface:"All", strengths:"SG:TOT +0.94 is strong. OTT +0.49 bomber. Well-rounded.",
      weaknesses:"Putting near zero (+0.04). Form has been cool (0.83x recently).", notes:"Co-FRL Houston 2025. TPC SA history #26. Solid player whose form dips create value at longer prices." },
    { name:"Thorbjorn Olesen", tier:"Mid-field", sg_tot:0.53, app:0.32, ott:0.19, arg:0.02, putt:-0.00, putt_bermuda:-0.03, putt_bent:0.02, putt_poa:-0.01, dd:1.2,
      shape:"Fade", surface:"All", strengths:"TPC SA SG:TOT #11. APP #16 and ARG #15 at the venue. Ball-striker who fits TPC SA.",
      weaknesses:"Putting dead flat. Not a bomber. No standout skill beyond iron play.", notes:"Course specialist at TPC San Antonio. T10 Valspar 2025 on Sunday 69. European veteran." },
    { name:"Zach Bauchou", tier:"Mid-field", sg_tot:0.25, app:0.15, ott:0.22, arg:-0.08, putt:0.05, putt_bermuda:0.02, putt_bent:0.08, putt_poa:0.04, dd:4.8,
      shape:"Draw", surface:"All", strengths:"Some distance and approach skill. Comp courses rank him mid-field.",
      weaknesses:"ARG negative. Relatively unproven. Small sample on Tour.", notes:"Valero composite #7. Comp 6mo #42, 3yr #51. Young player showing up in models." },
    { name:"Kristoffer Reitan", tier:"Mid-field", sg_tot:0.56, app:-0.15, ott:0.55, arg:-0.15, putt:0.30, putt_bermuda:0.25, putt_bent:0.32, putt_poa:0.28, dd:9.1,
      shape:"Draw", surface:"Poa", strengths:"OTT +0.55 strong driver. PUTT +0.30 positive especially on Poa. Distance.",
      weaknesses:"APP -0.15 is poor. ARG -0.15 also negative. Ball-striking tee-to-green is weak.", notes:"On Notice (0-3). HEADWIND form at Valspar. Skill base says better than results show." },
    { name:"Ryo Hisatsune", tier:"Mid-field", sg_tot:0.91, app:0.47, ott:0.41, arg:0.11, putt:-0.08, putt_bermuda:-0.12, putt_bent:-0.05, putt_poa:-0.08, dd:0.3,
      shape:"Fade", surface:"All", strengths:"APP +0.47 strong. OTT +0.41 solid. Ball-striking is genuine. SG:TOT +0.91.",
      weaknesses:"Putting negative (-0.08). Inconsistent week to week.", notes:"T18 at Harbour Town 2025. ON CARD at +10500. Model avg #10.3. Mayo: 'most definitely consider.' Point-and-click approach course fits his game. Driving positive every start this year." },
    { name:"Rasmus Hojgaard", tier:"Contender", sg_tot:0.76, app:0.17, ott:0.24, arg:-0.03, putt:0.39, putt_bermuda:0.35, putt_bent:0.42, putt_poa:0.38, dd:14.2,
      shape:"Fade", surface:"All", strengths:"PUTT +0.39 is strong (better than brother Nicolai). DrDist +14.2 = bomber. Distance + putting combo.",
      weaknesses:"APP +0.17 is modest. ARG near zero. Iron play not elite.", notes:"Houston dark horse surfaced by anti-bias protocol. M15#5, M19#7. Better putter than Nicolai on Poa." },
    { name:"Andrew Novak", tier:"Mid-field", sg_tot:0.28, app:0.159, ott:0.022, arg:0.074, putt:0.023, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-0.8,
      shape:"Unknown", surface:"Unknown", strengths:"Balanced. T5 at Valero 2025. Ball striking back per Mayo.",
      weaknesses:"Nothing elite. Short hitter.", notes:"Mayo's highest mid-tier conviction. Bet 60/1 E/W. 'First click' for single entry." },
    { name:"Andrew Putnam", tier:"Mid-field", sg_tot:0.09, app:0.024, ott:-0.482, arg:0.357, putt:0.195, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-22.0,
      shape:"Unknown", surface:"Unknown", strengths:"ARG +0.36 is elite. PUTT +0.20 solid. Expert #14 (Andy #5).",
      weaknesses:"OTT -0.48 is terrible. Shortest hitter in most fields.", notes:"Andy2 #5. ARG specialist at an elevated green course." },
    { name:"Beau Hossler", tier:"Mid-field", sg_tot:-0.02, app:-0.347, ott:-0.327, arg:0.304, putt:0.348, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-1.7,
      shape:"Unknown", surface:"Unknown", strengths:"ARG +0.30 + PUTT +0.35 = elite short game combo. DG TAILWIND 1.61.",
      weaknesses:"APP -0.35 and OTT -0.33 = can't hit the ball. Relies entirely on short game.", notes:"At +14000 b365. Short game only." },
    { name:"Billy Horschel", tier:"Mid-field", sg_tot:-0.17, app:0.004, ott:-0.361, arg:0.071, putt:0.114, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-3.4,
      shape:"Unknown", surface:"Unknown", strengths:"Experienced. Knows most courses well.",
      weaknesses:"OTT -0.36 is very weak. Overall declining.", notes:"Veteran at long prices." },
    { name:"Chad Ramey", tier:"Mid-field", sg_tot:0.08, app:-0.139, ott:-0.065, arg:-0.029, putt:0.317, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-2.8,
      shape:"Unknown", surface:"Unknown", strengths:"PUTT +0.32 elite. 6mo PUTT#6. 2025 Valero SG:TOT#8.",
      weaknesses:"APP -0.14 below average. No ball-striking weapon.", notes:"FRL ON CARD. Course history + putting at a putting course. DG TAILWIND 1.25." },
    { name:"David Ford", tier:"Mid-field", sg_tot:0.14, app:-0.006, ott:0.478, arg:-0.169, putt:-0.167, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:2.2,
      shape:"Unknown", surface:"Unknown", strengths:"OTT +0.48 is strong distance.",
      weaknesses:"APP near zero. ARG and PUTT both negative.", notes:"DFS bargain tier at $6.7K. Bomber." },
    { name:"Emiliano Grillo", tier:"Mid-field", sg_tot:-0.05, app:0.072, ott:0.100, arg:-0.158, putt:-0.066, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-6.6,
      shape:"Unknown", surface:"Unknown", strengths:"Adequate ball-striking.",
      weaknesses:"ARG -0.16 is bad. Nothing stands out.", notes:"Veteran at long odds." },
    { name:"J.T. Poston", tier:"Mid-field", sg_tot:0.50, app:0.104, ott:0.192, arg:0.043, putt:0.159, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-5.1,
      shape:"Unknown", surface:"Unknown", strengths:"Balanced positive across all 4 SG categories. SG:TOT +0.50.",
      weaknesses:"Nothing elite — solid everywhere but not a specialist.", notes:"6th/8th/3rd/5th/T11/T11 at Harbour Town career. Models rank him 50th but course history is elite. Chips and putts his way to results even with bad irons. Mayo likes him." },
    { name:"Jesper Svensson", tier:"Mid-field", sg_tot:-0.05, app:0.002, ott:0.413, arg:-0.088, putt:-0.375, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:15.3,
      shape:"Unknown", surface:"Unknown", strengths:"OTT +0.41 elite distance. DD +15.3 is one of the longest on Tour.",
      weaknesses:"PUTT -0.38 is terrible. ARG negative.", notes:"DFS bargain at $6.8K. Pure bomber in wind." },
    { name:"Joel Dahmen", tier:"Mid-field", sg_tot:0.16, app:0.267, ott:0.347, arg:-0.143, putt:-0.312, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-6.9,
      shape:"Unknown", surface:"Unknown", strengths:"APP +0.27 and OTT +0.35 = ball-striking is his game.",
      weaknesses:"PUTT -0.31 is very bad. ARG -0.14 negative.", notes:"Replaced Hojgaard in the field." },
    { name:"Lanto Griffin", tier:"Mid-field", sg_tot:1.07, app:0.398, ott:0.018, arg:0.278, putt:0.373, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0.5,
      shape:"Unknown", surface:"Unknown", strengths:"SG:TOT +1.07 is elite. APP +0.40, ARG +0.28, PUTT +0.37 = positive everywhere.",
      weaknesses:"Small recent sample. OTT near zero.", notes:"Expert #47 but SG data says elite. Disconnect." },
    { name:"Lee Hodges", tier:"Mid-field", sg_tot:0.25, app:0.219, ott:0.171, arg:-0.089, putt:-0.055, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-3.2,
      shape:"Unknown", surface:"Unknown", strengths:"APP +0.22 is decent.",
      weaknesses:"ARG and PUTT both slightly negative.", notes:"Mid-field grinder." },
    { name:"Patrick Rodgers", tier:"Mid-field", sg_tot:0.41, app:0.122, ott:0.061, arg:0.110, putt:0.119, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:5.9,
      shape:"Unknown", surface:"Unknown", strengths:"Balanced positive in all 4 categories. Expert #31.",
      weaknesses:"Nothing elite.", notes:"Quiet consistent player." },
    { name:"Sam Ryder", tier:"Mid-field", sg_tot:-0.43, app:-0.173, ott:-0.312, arg:-0.139, putt:0.195, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:-3.9,
      shape:"Unknown", surface:"Unknown", strengths:"DG TAILWIND 1.59. 2025 FRL winner at TPC SA (shot 63 R1). PUTT +0.20.",
      weaknesses:"SG:TOT -0.43 = below Tour average. Negative in APP, OTT, ARG.", notes:"FRL ON CARD. Pure form surge + course FRL history. Woodland thesis." },
    { name:"Taylor Moore", tier:"Mid-field", sg_tot:0.21, app:-0.198, ott:0.150, arg:0.133, putt:0.121, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:7.1,
      shape:"Unknown", surface:"Unknown", strengths:"OTT +0.15, ARG +0.13, PUTT +0.12 = short game + distance.",
      weaknesses:"APP -0.20 is bad.", notes:"Replaced Coody in the field." },
    { name:"Vince Whaley", tier:"Mid-field", sg_tot:0.01, app:-0.211, ott:-0.412, arg:0.128, putt:0.503, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:1.1,
      shape:"Unknown", surface:"Unknown", strengths:"PUTT +0.50 = #1 in 6mo form across entire field. Elite putter.",
      weaknesses:"APP -0.21 and OTT -0.41 = terrible ball-striking.", notes:"At +15000. Best putter in the field at a putting course. Can he survive T2G?" },
    { name:"Zecheng Dou", tier:"Mid-field", sg_tot:0.25, app:0.215, ott:0.268, arg:0.053, putt:-0.284, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0.8,
      shape:"Unknown", surface:"Unknown", strengths:"APP +0.22 + OTT +0.27 = solid ball-striking. 6mo APP#9, ARG#15.",
      weaknesses:"PUTT -0.28 is bad.", notes:"APP+ARG dual fit at +12500. Iron precision." },
    { name:"Adrien Dumont de Chassart", tier:"Mid-field", sg_tot:0.49, app:0.099, ott:0.148, arg:0.100, putt:0.143, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:6.8,
      shape:"Unknown", surface:"Unknown", strengths:"Balanced. Positive in all 4 SG categories. SG:TOT +0.49.",
      weaknesses:"Nothing elite in any category.", notes:"Belgian. Solid all-around at +9000." },
    { name:"Bronson Burgoon", tier:"Mid-field", sg_tot:0.00, app:0.000, ott:0.000, arg:0.000, putt:0.000, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0.0,
      shape:"Unknown", surface:"Unknown", strengths:"6mo TOT#22. PUTT#9 in 6mo. Texas local.",
      weaknesses:"Limited DG data.", notes:"At +15000. Texas player with recent putting form." },
    { name:"S.H. Kim", tier:"Mid-field", sg_tot:0.16, app:-0.346, ott:0.118, arg:0.067, putt:0.324, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0.8,
      shape:"Fade", surface:"Unknown", strengths:"PUTT +0.32 elite. DG TAILWIND 1.26. 6mo PUTT#23. Wide putting stance.",
      weaknesses:"APP -0.35 is terrible. Can't hit greens.", notes:"Pure putter. At +10000. Putting-only thesis doesn't work at an approach course." },
    // --- Masters field additions (Noonan profiles, Apr 3) ---
    { name:"Bryson DeChambeau", liv:true, tier:"Contender", sg_tot:1.45, app:0.45, ott:0.82, arg:0.08, putt:0.10, putt_bermuda:0, putt_bent:0.15, putt_poa:0, dd:18.5,
      shape:"Straight", surface:"All", strengths:"Distance elite. T10 in 6/8 recent majors. 2024 US Open champ. Rounding into form for majors as usual.",
      weaknesses:"Noonan: 'rigid methodology lacks nuance and feel.' APP 0.39-0.45 on LIV (was 0.93 PGA Tour). Short game suspect at Augusta.",
      notes:"Augusta SG:TOT +0.49/rd. Best: T5 2025, T6 2024. ON CARD +1400 E/W 1/4 5pl $20. Tindall 70/79. Noonan skeptical of Augusta fit.", augusta_sg:0.49 },
    { name:"Gary Woodland", tier:"Mid-field", sg_tot:0.03, app:-0.10, ott:0.25, arg:-0.33, putt:0.21, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:12.0,
      shape:"Fade", surface:"Bent", strengths:"Houston winner 2026 (-21). TAILWIND 1.52x. 2019 US Open champ. Ball speed up.",
      weaknesses:"ARG -0.33 at hardest ARG course on Tour. Augusta SG:TOT -0.50/rd. MC in 3 of 5 Masters starts.",
      notes:"Won Houston but Augusta is kryptonite. SG:TOT barely positive. DG form surge from very low base.", augusta_sg:-0.50 },
    { name:"Brooks Koepka", tier:"Contender", sg_tot:0.85, app:0.42, ott:0.38, arg:0.05, putt:0.00, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:10.2,
      shape:"Fade", surface:"All", strengths:"4x major champ. 2x Masters runner-up (2019, 2023). Flips switch for majors. Augusta SG +0.27/rd.",
      weaknesses:"OWGR 165th. LIV form inconsistent. MC in 3 of 5 recent Masters. Major gear-shift is the only thesis.",
      notes:"Noonan: 'tough nut to crack in non-majors, shifts gears when lights are brightest.' At +3400 EoR1.", augusta_sg:0.27 },
    { name:"Tyrrell Hatton", liv:true, tier:"Contender", sg_tot:0.95, app:0.35, ott:0.28, arg:0.22, putt:0.10, putt_bermuda:0, putt_bent:0.15, putt_poa:0, dd:4.5,
      shape:"Draw", surface:"All", strengths:"T9 2024, T14 2025 — warming to Augusta. 10th consecutive start. Well-rounded game. ARG +0.22.",
      weaknesses:"Augusta SG only +0.42/rd despite good recent results. LIV schedule limits prep.",
      notes:"Noonan: 'always felt his game is well-suited for Augusta.' Finally showing it with back-to-back T14-or-better.", augusta_sg:0.42 },
    { name:"Keegan Bradley", tier:"Mid-field", sg_tot:0.62, app:0.28, ott:0.15, arg:0.12, putt:0.07, putt_bermuda:0, putt_bent:0.10, putt_poa:0, dd:-2.0,
      shape:"Fade", surface:"Bent", strengths:"2025 Ryder Cup captain energy. Augusta SG +0.76/rd. 2011 PGA champ. Experience (10th start).",
      weaknesses:"Zero top-20s in 9 Masters starts. Noonan: either freed up post-Ryder Cup or consumed by it. Results suggest the latter.",
      notes:"10th start, still chasing first T20 at Augusta. SG data says he plays well here but results don't show it.", augusta_sg:0.76 },
    { name:"Max Homa", tier:"Mid-field", sg_tot:0.45, app:0.22, ott:0.18, arg:0.15, putt:-0.10, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:5.5,
      shape:"Fade", surface:"Bent", strengths:"T3 2024 Masters. Augusta SG +0.46/rd. Short game strong. When locked in, elite ceiling.",
      weaknesses:"OWGR 156th. Struggling badly in 2026. Noonan: 'if he struggles at Valero, tough to back.'",
      notes:"Noonan: lead-in form not strong but better than last year (low bar). T3 here in 2024 proves ceiling exists.", augusta_sg:0.46 },
    // Masters 2026 backfill — added Apr 8
    { name:"Harry Hall", tier:"Contender", sg_tot:1.07, app:0.15, ott:0.10, arg:0.45, putt:0.37, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Variable", surface:"Unknown", strengths:"ARG #5 in Betsperts model. Strong scrambler. DG rank 31st.",
      weaknesses:"APP #56, OTT #57 — ball-striking is the weakness. First Masters.",
      notes:"DG E/W EV +20.3% at b365 +15000. Betsperts TOT #30. Debutant." },
    { name:"Michael Kim", tier:"Mid-field", sg_tot:0.54, app:0.18, ott:0.08, arg:0.15, putt:0.13, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Draw", surface:"Unknown", strengths:"Rick: right-to-left shot shape (rare for righty). 27th at 2025 Masters. Beautiful iron shots.",
      weaknesses:"Betsperts TOT #58. DG HEADWIND 0.69x. No strong stat profile for Augusta.",
      notes:"ON CARD FRL +9000 E/W b365. Rick punt play. $6,700 DFS." },
    { name:"Aaron Rai", tier:"Mid-field", sg_tot:0.49, app:0.28, ott:0.08, arg:0.05, putt:-0.08, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Fade", surface:"Unknown", strengths:"APP solid. DG rank 80th. Betsperts APP #40.",
      weaknesses:"PUTT #61 in Betsperts. HEADWIND signal. 46% MC probability.",
      notes:"2nd Masters start. DG not optimistic." },
    { name:"Tom McKibbin", tier:"Mid-field", sg_tot:0.31, app:0.10, ott:0.15, arg:0.02, putt:0.04, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Draw", surface:"Unknown", strengths:"Young talent. LIV player with length.",
      weaknesses:"DG rank 106. HEADWIND signal. 46% MC probability.",
      notes:"Masters debutant via LIV." },
    { name:"Carlos Ortiz", tier:"Mid-field", sg_tot:0.58, app:0.12, ott:0.18, arg:0.15, putt:0.13, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Variable", surface:"Unknown", strengths:"Well-rounded profile. DG rank 64.",
      weaknesses:"HEADWIND signal at Augusta. No strong stat spike.",
      notes:"LIV player. Limited Augusta data." },
    { name:"Casey Jarvis", tier:"Mid-field", sg_tot:0.60, app:0.10, ott:0.20, arg:0.10, putt:0.20, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Variable", surface:"Unknown", strengths:"Rick: been hot on DP World Tour (won back-to-back). DG rank 59.",
      weaknesses:"HEADWIND at Augusta. 42% MC probability. First Masters.",
      notes:"South African. DP World Tour form." },
    { name:"Rasmus Neergaard-Petersen", tier:"Bubble", sg_tot:0.27, app:0.05, ott:0.10, arg:0.05, putt:0.07, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Variable", surface:"Unknown", strengths:"DG rank 112. Young Nordic player.",
      weaknesses:"HEADWIND 0.48x. 48% MC probability. No Augusta pedigree.",
      notes:"Masters debutant. $6,700 DK." },
    { name:"Davis Riley", tier:"Bubble", sg_tot:-0.86, app:-0.20, ott:-0.15, arg:-0.10, putt:-0.05, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Fade", surface:"Unknown", strengths:"Previous PGA Tour winner. Betsperts PUTT #22.",
      weaknesses:"DG rank 368. SG negative across the board. 65% MC probability.",
      notes:"Struggling badly. Past champion invite only path." },
    { name:"Dustin Johnson", liv:true, tier:"Bubble", sg_tot:0.01, app:0.05, ott:0.15, arg:-0.05, putt:-0.10, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:15.0,
      shape:"Fade", surface:"All", strengths:"2020 Masters champion (-20, record). Elite length. Won 2 majors.",
      weaknesses:"LIV form declining. DG rank 156. 49% MC probability.",
      notes:"2020 champion. November Masters record -20. But a shell of himself in 2026. TAILWIND 1.30x from Augusta history only." },
    { name:"Sergio Garcia", tier:"Bubble", sg_tot:0.14, app:0.10, ott:0.05, arg:0.05, putt:-0.06, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Draw", surface:"Unknown", strengths:"2017 Masters champion. Deep Augusta history. Creative short game.",
      weaknesses:"DG rank 131. HEADWIND signal. LIV form poor. 50% MC probability.",
      notes:"2017 champion. Emotional player. LIV has not been kind to his form." },
    { name:"Charl Schwartzel", tier:"Bubble", sg_tot:-0.01, app:0.05, ott:-0.05, arg:0.05, putt:-0.05, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Draw", surface:"Unknown", strengths:"2011 Masters champion. 4 birdies in last 4 holes to win. TAILWIND 1.5x.",
      weaknesses:"DG rank 159. 50% MC probability. LIV player, minimal competitive data.",
      notes:"2011 champion. Augusta history carries his probability." },
    { name:"Danny Willett", tier:"Bubble", sg_tot:-1.08, app:-0.20, ott:-0.15, arg:0.10, putt:-0.05, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Fade", surface:"Unknown", strengths:"2016 Masters champion. ARG still decent. Betsperts ARG #28.",
      weaknesses:"DG rank 457. SG deeply negative. 65% MC probability.",
      notes:"2016 champion. Won when Spieth collapsed on 12. Sentimental favorite only." },
    { name:"Bubba Watson", tier:"Bubble", sg_tot:-0.15, app:-0.10, ott:0.05, arg:0.05, putt:-0.15, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:10.0,
      shape:"Draw", surface:"Unknown", strengths:"2x Masters champion (2012, 2014). Lefty advantage on certain holes. Creative shot-maker.",
      weaknesses:"DG rank 188. 55% MC probability. LIV form poor.",
      notes:"2x champion. Shot shaping genius but game has declined significantly." },
    { name:"Zach Johnson", tier:"Bubble", sg_tot:0.01, app:-0.05, ott:-0.10, arg:0.15, putt:0.30, putt_bermuda:0, putt_bent:0.30, putt_poa:0, dd:-15.0,
      shape:"Fade", surface:"Bentgrass best", strengths:"2007 Masters champion. Elite putter. ARG #32 Betsperts. PUTT #9.",
      weaknesses:"DG rank 157. Short hitter. 55% MC probability.",
      notes:"2007 champion. Won without length — pure iron play + putting. 56 years old." },
    { name:"Fred Couples", tier:"Past Champ", sg_tot:0, app:0, ott:0, arg:0, putt:0, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Draw", surface:"Unknown", strengths:"1992 Masters champion. Augusta legend. Perennial fan favorite.",
      weaknesses:"67 years old. No competitive data. 82% MC probability.",
      notes:"Honorary competitor at this point. Still hits it pure in practice." },
    { name:"Vijay Singh", tier:"Past Champ", sg_tot:0, app:0, ott:0, arg:0, putt:0, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Fade", surface:"Unknown", strengths:"2000 Masters champion. 3 major wins total.",
      weaknesses:"63 years old. 82% MC probability.",
      notes:"Betsperts has him at DK $6,100. ARG #15 in their model — his short game somehow still ranks." },
    { name:"Jose Maria Olazabal", tier:"Past Champ", sg_tot:0, app:0, ott:0, arg:0, putt:0, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Fade", surface:"Unknown", strengths:"2x Masters champion (1994, 1999). Seve's heir at Augusta.",
      weaknesses:"60 years old. 97% MC probability.",
      notes:"Honorary competitor." },
    { name:"Mike Weir", tier:"Past Champ", sg_tot:0, app:0, ott:0, arg:0, putt:0, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Draw", surface:"Unknown", strengths:"2003 Masters champion. Only Canadian Masters winner. Lefty.",
      weaknesses:"55 years old. 89% MC probability.",
      notes:"Honorary competitor." },
    { name:"Angel Cabrera", tier:"Past Champ", sg_tot:0, app:0, ott:0, arg:0, putt:0, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Draw", surface:"Unknown", strengths:"2009 Masters champion. Powerful. 2013 runner-up (playoff loss to Scott).",
      weaknesses:"No current competitive data. 80% MC probability.",
      notes:"Argentine legend. Won in playoff over Perry/Campbell." },
    { name:"Mason Howell", tier:"Amateur", sg_tot:0, app:0, ott:0.10, arg:0, putt:0, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:5.0,
      shape:"Variable", surface:"Unknown", strengths:"2025 U.S. Amateur champion. Betsperts OTT #47.",
      weaknesses:"Amateur. 78% MC probability. No professional data.",
      notes:"Top amateur in field. Klos: 6 amateurs competing." },
    { name:"Ethan Fang", tier:"Amateur", sg_tot:0, app:0, ott:0, arg:0, putt:0, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Variable", surface:"Unknown", strengths:"Amateur qualifier.",
      weaknesses:"79% MC probability. No professional data.",
      notes:"Amateur." },
    { name:"Brandon Holtz", tier:"Amateur", sg_tot:0, app:0, ott:0, arg:0, putt:0, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Variable", surface:"Unknown", strengths:"Amateur qualifier.",
      weaknesses:"93% MC probability.",
      notes:"Amateur." },
    { name:"Jackson Herrington", tier:"Amateur", sg_tot:0, app:0, ott:0, arg:0, putt:0, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Variable", surface:"Unknown", strengths:"Amateur qualifier.",
      weaknesses:"88% MC probability.",
      notes:"Amateur." },
    { name:"Mateo Pulcini", tier:"Amateur", sg_tot:0, app:0, ott:0, arg:0, putt:0, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Variable", surface:"Unknown", strengths:"Amateur qualifier.",
      weaknesses:"93% MC probability.",
      notes:"Amateur." },
    { name:"Naoyuki Kataoka", tier:"Amateur", sg_tot:0, app:0, ott:0, arg:0, putt:0, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Variable", surface:"Unknown", strengths:"Asia-Pacific Amateur champion.",
      weaknesses:"77% MC probability.",
      notes:"Japanese amateur. Asia-Pacific Am path to Masters." },
    { name:"Fifa Laopakdee", tier:"Amateur", sg_tot:0, app:0, ott:0, arg:0, putt:0, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Variable", surface:"Unknown", strengths:"Amateur qualifier from Thailand.",
      weaknesses:"83% MC probability.",
      notes:"Thai amateur. Pongsapak Laopakdee." },
    { name:"Brian Campbell", tier:"Bubble", sg_tot:-0.87, app:-0.15, ott:-0.20, arg:0.05, putt:0.05, putt_bermuda:0, putt_bent:0, putt_poa:0, dd:0,
      shape:"Variable", surface:"Unknown", strengths:"Betsperts TOT #69. TAILWIND signal at Augusta.",
      weaknesses:"DG rank 371. 76% MC probability. SG deeply negative.",
      notes:"First Masters via qualifying. DG TAILWIND driven by small history sample." },
];

// Player status flags (updated from conversation intel, podcasts, news)
// Types: injury, rest, travel, motivation, equipment, form, note
const PLAYER_STATUS = [
    { player: "Collin Morikawa", type: "injury", status: "Back injury persisted through Masters (T7 -9 finish despite it). Ball speed down. Monitor for RBC Heritage — if playing, elite Harbour Town fit.", severity: "caution", updated: "Apr 12" },
    { player: "Rory McIlroy", type: "info", status: "Won Masters back-to-back (-12). 67-65-73-71. +7.75 SG total dominated. Likely skip RBC Heritage.", severity: "info", updated: "Apr 12" },
    { player: "Russell Henley", type: "info", status: "Masters T3 (-10)! Shot 66 R3. Both T20 prop and E/W place cashed. Hot form heading into RBC Heritage — strong Harbour Town fit.", severity: "info", updated: "Apr 12" },
    { player: "Tommy Fleetwood", type: "caution", status: "Masters T33 (E). Collapsed R4 with 76. Was T4 after R2. R4 fade pattern concern — mid-tier grinder fading Sunday. Monitor.", severity: "caution", updated: "Apr 12" },
    { player: "Patrick Reed", type: "info", status: "Masters T12 (-5). R1-R2 brilliant (69-69, FRL placed T3). Faded R3-R4 (72-73). TAILWIND thesis partially validated.", severity: "info", updated: "Apr 12" },
];

// Course library
const COURSES = [
    {
        name: "Augusta National", event: "The Masters", surface: "Bentgrass", length: "7,555 yds",
        archetype: "Second-shot + Short game", scoring: "Difficult", dataKey: "masters",
        topStats: ["SG:APP 150+", "Course History", "Carry Distance", "SG:ARG", "Par 5 BoB%"],
        masked: "Driving accuracy, seasonal putting", amplified: "Approach precision, short-grass ARG, Par 5 scoring",
        bets: 9, pl: 0, status: "live"
    },
    {
        name: "Memorial Park GC", event: "Houston Open", surface: "Poa Trivialis", length: "7,475 yds",
        archetype: "Second-shot + Bomber", scoring: "Hard", dataKey: "houston",
        topStats: ["SG:APP", "DrDist", "SG:ARG (short grass)", "SG:OTT", "Bogey Avoidance"],
        masked: "Driving accuracy (1.25in rough)", amplified: "Distance, approach 150+, short-grass scrambling",
        bets: 11, pl: -58, status: "settled"
    },
    {
        name: "Innisbrook (Copperhead)", event: "Valspar Championship", surface: "Poa Trivialis", length: "7,352 yds",
        archetype: "Second-shot + Poa putting", scoring: "Hard", dataKey: "valspar",
        topStats: ["SG:APP", "SG:OTT (less-than-driver)", "Bogey Avoidance", "SG:PUTT Poa", "Par 3 scoring"],
        masked: "None significant", amplified: "Approach precision, positional driving, Poa putting",
        bets: 11, pl: -85, status: "settled"
    },
    {
        name: "TPC Sawgrass", event: "The Players", surface: "Bermuda/Poa", length: "7,245 yds",
        archetype: "Second-shot + Penalty", scoring: "Hard", dataKey: "players",
        topStats: ["SG:APP", "SG:PUTT Poa", "Bogey Avoidance", "SG:ARG", "Course History"],
        masked: "None", amplified: "Iron precision, scrambling, mental fortitude",
        bets: 17, pl: -110, status: "settled"
    },
    {
        name: "Bay Hill Club & Lodge", event: "Arnold Palmer Inv", surface: "Bermuda", length: "7,466 yds",
        archetype: "Bermuda putting + Ball-striking", scoring: "Hard", dataKey: "arnoldpalmer",
        topStats: ["SG:PUTT Bermuda", "SG:APP", "SG:OTT", "Bogey Avoidance"],
        masked: "Short game", amplified: "Bermuda putting, ball-striking, wind management",
        bets: 22, pl: 51.10, status: "settled"
    },
    {
        name: "TPC San Antonio (Oaks)", event: "Valero Texas Open", surface: "Bermuda/Poa", length: "7,438 yds",
        archetype: "Second-shot + Wind-exposed", scoring: "Hard (wind-dependent)", dataKey: "valero",
        topStats: ["SG:APP", "SG:ARG", "SG:OTT", "Wind Management", "Par 5 Scoring"],
        masked: "Fairway accuracy (moderate rough)", amplified: "Approach to elevated greens, short game, wind shaping",
        bets: 5, pl: 0, status: "upcoming"
    },
    {
        name: "PGA National (Champion)", event: "Cognizant Classic", surface: "Bermuda", length: "7,125 yds",
        archetype: "Grinder / Penalty course", scoring: "Hard", dataKey: "cognizant",
        topStats: ["SG:PUTT Bermuda", "Bogey Avoidance", "SG:APP", "Scrambling", "SG:OTT Accuracy"],
        masked: "Driving distance (short course)", amplified: "Bermuda putting, water management, bogey avoidance",
        bets: 17, pl: 341.75, status: "settled"
    },
    {
        name: "Grand Reserve GC", event: "Puerto Rico Open", surface: "Bermuda/Paspalum", length: "7,506 yds",
        archetype: "Birdie-fest + Wind-exposed", scoring: "Standard", dataKey: "puertorico",
        topStats: ["SG:OTT (Wind)", "SG:APP", "Wind Management", "Birdie Making", "SG:PUTT Paspalum"],
        masked: "Driving accuracy (wide fairways)", amplified: "Wind shaping, ball flight control, distance in wind",
        bets: 9, pl: 195, status: "settled"
    },
];
