// Season data
const SEASON = {
    totalBets: 156,
    settled: 136,
    open: 16,
    staked: 1372.75,
    settledStaked: 1176.50,
    returned: 1204.25,
    pl: 27.75,
    roi: 2.4,
    winners: 10
};

const TOURNAMENTS = [
    { name: "AMEX", bets: 11, staked: 100, returned: 10, pl: -90, phase: 1 },
    { name: "Farmers", bets: 20, staked: 142, returned: 0, pl: -142, phase: 1 },
    { name: "WM Open", bets: 13, staked: 87.50, returned: 0, pl: -87.50, phase: 1 },
    { name: "Genesis", bets: 16, staked: 160, returned: 114.40, pl: -45.60, phase: 2 },
    { name: "Cognizant", bets: 17, staked: 184.50, returned: 526.25, pl: 341.75, phase: 2 },
    { name: "Arnold Palmer", bets: 22, staked: 192.50, returned: 243.60, pl: 51.10, phase: 2 },
    { name: "Puerto Rico", bets: 9, staked: 100, returned: 295, pl: 195, phase: 2 },
    { name: "Players", bets: 17, staked: 125, returned: 15, pl: -110, phase: 2 },
    { name: "Valspar", bets: 11, staked: 85, returned: 0, pl: -85, phase: 2 },
    { name: "Houston", bets: 11, staked: 130, returned: 0, pl: 0, phase: 2, status: "live" },
];

const WINNERS = [
    { tournament: "Genesis", player: "Collin Morikawa", market: "Top 10", odds: "+210", stake: 20, ret: 62, pl: 42 },
    { tournament: "Genesis", player: "Tommy Fleetwood", market: "Top 10", odds: "+162", stake: 20, ret: 52.40, pl: 32.40 },
    { tournament: "Cognizant", player: "Nico Echavarria", market: "E/W 1/4 5pl", odds: "+5000", stake: 10, ret: 322.50, pl: 312.50 },
    { tournament: "Cognizant", player: "Keith Mitchell", market: "E/W 1/5 8pl", odds: "+2500", stake: 15, ret: 45, pl: 30 },
    { tournament: "Cognizant", player: "Austin Smotherman", market: "E/W 1/4 5pl", odds: "+10000", stake: 2.50, ret: 158.75, pl: 156.25 },
    { tournament: "Arnold Palmer", player: "Collin Morikawa", market: "Top 10", odds: "+230", stake: 10, ret: 33, pl: 23 },
    { tournament: "Puerto Rico", player: "Ricky Castillo", market: "E/W 1/4 5pl", odds: "+2200", stake: 20, ret: 295, pl: 275 },
    { tournament: "Arnold Palmer", player: "Conners/Bhatia", market: "2-Ball Parlay", odds: "+200", stake: 10, ret: 30, pl: 20 },
    { tournament: "Arnold Palmer", player: "Chris Gotterup", market: "72H vs Thomas", odds: "-110", stake: 10, ret: 19.10, pl: 9.10 },
    { tournament: "Arnold Palmer", player: "DFS Lineup", market: "GPP", odds: "-", stake: 20, ret: 144, pl: 124 },
];

const MARKETS = [
    { type: "Outright E/W", bets: 51, pl: 267, roi: 64.6 },
    { type: "FRL", bets: 49, pl: -159.75, roi: -46.1 },
    { type: "Props (T10)", bets: 20, pl: -42.60, roi: -21.8 },
    { type: "DFS", bets: 5, pl: 69, roi: 92.0 },
    { type: "Matchups", bets: 3, pl: 19.10, roi: 47.8 },
    { type: "3-Ball", bets: 4, pl: -80, roi: -100 },
];

const EW_TERMS = [
    { terms: "E/W 1/4 5pl", bets: 23, pl: 590.25, roi: 293.7 },
    { terms: "E/W 1/5 8pl", bets: 11, pl: -61, roi: -52.6 },
    { terms: "E/W 1/5 5pl", bets: 18, pl: -130, roi: -100 },
    { terms: "E/W 1/5 10pl", bets: 6, pl: -35, roi: -100 },
];

// Current Houston card
const HOUSTON_CARD = [
    { num: 1, player: "Nicolai Hojgaard", market: "Outright", terms: "1/4 5pl", odds: "+2500", stake: 20, placed: "Mar 25", edge: "Meta #3", status: "2nd (-17)" },
    { num: 2, player: "Kurt Kitayama", market: "Outright", terms: "1/4 5pl", odds: "+2800", stake: 20, placed: "Mar 25", edge: "APP #1 + 30% boost", status: "E (back of field)" },
    { num: 3, player: "Adam Scott", market: "Outright", terms: "1/4 5pl", odds: "+4000", stake: 10, placed: "Mar 25", edge: "Meta #2", status: "T10 (-9)" },
    { num: 4, player: "Keith Mitchell", market: "Outright", terms: "1/5 8pl", odds: "+3500", stake: 10, placed: "Mar 25", edge: "APP+OTT double", status: "T~25 (-5)" },
    { num: 5, player: "Wyndham Clark", market: "Outright", terms: "1/5 8pl", odds: "+3500", stake: 10, placed: "Mar 25", edge: "T5 2025 + form", status: "MC" },
    { num: 6, player: "Stephan Jaeger", market: "Outright", terms: "1/5 8pl", odds: "+4500", stake: 10, placed: "Mar 25", edge: "2024 winner", status: "T12 (-8)" },
    { num: 7, player: "Max Greyserman", market: "Outright", terms: "1/5 8pl", odds: "+5500", stake: 10, placed: "Mar 25", edge: "T7 2024", status: "MC" },
    { num: 8, player: "Kurt Kitayama", market: "FRL", terms: "1/4 5pl", odds: "+4000", stake: 10, placed: "Mar 25", edge: "5/5 filter", status: "Lost" },
    { num: 9, player: "Nicolai Hojgaard", market: "FRL", terms: "1/4 5pl", odds: "+3500", stake: 10, placed: "Mar 25", edge: "5/5 filter", status: "Lost" },
    { num: 10, player: "Keith Mitchell", market: "FRL", terms: "1/4 5pl", odds: "+4500", stake: 10, placed: "Mar 25", edge: "4/5 + history", status: "Lost" },
    { num: 11, player: "Alejandro Tosti", market: "FRL", terms: "1/4 5pl", odds: "+8000", stake: 10, placed: "Mar 25", edge: "Co-FRL 2025", status: "Lost" },
];

const MASTERS_CARD = [
    { num: 1, player: "Akshay Bhatia", market: "Outright", terms: "1/5 10pl", odds: "+5500", stake: 10, placed: "Mar 8", t10s: 0, comp: "#15", status: "Open" },
    { num: 2, player: "Bryson DeChambeau", market: "Outright", terms: "1/4 5pl", odds: "+1400", stake: 20, placed: "Mar 8", t10s: 2, comp: "#33", status: "Open" },
    { num: 3, player: "Adam Scott", market: "Outright", terms: "1/4 5pl", odds: "+8000", stake: 10, placed: "Mar 27", t10s: 3, comp: "#18", status: "Open" },
    { num: 4, player: "Jason Day", market: "Outright", terms: "1/4 5pl", odds: "+7000", stake: 10, placed: "Mar 27", t10s: 4, comp: "#53", status: "Open" },
];

const VALERO_CARD = [
    { num: 1, player: "A.J. Ewart", market: "Outright", terms: "Win", odds: "+34000", stake: 1.25, placed: "Mar 28", edge: "Comp #2. Dark horse.", status: "Open" },
    { num: 2, player: "Will Zalatoris", market: "Outright", terms: "Win", odds: "+7800", stake: 5, placed: "Mar 28", edge: "Comp #4. APP elite.", status: "Open" },
    { num: 3, player: "Sudarshan Yellamaraju", market: "Outright", terms: "Win", odds: "+14000", stake: 2.50, placed: "Mar 28", edge: "Comp #9. Dark horse.", status: "Open" },
    { num: 4, player: "Mackenzie Hughes", market: "Outright", terms: "Win", odds: "+11500", stake: 2.50, placed: "Mar 28", edge: "Comp #5. Course fit.", status: "Open" },
];

// Player rotation data
const PLAYERS = {
    active: [
        { name: "Collin Morikawa", bets: 6, wins: 2, pl: 35, roi: 50 },
        { name: "Ricky Castillo", bets: 3, wins: 1, pl: 270, roi: 1080 },
        { name: "Tommy Fleetwood", bets: 3, wins: 1, pl: 17.40, roi: 50 },
        { name: "Keith Mitchell", bets: 6, wins: 1, pl: -32, roi: -32 },
        { name: "Kurt Kitayama", bets: 6, wins: 0, pl: -50, roi: -100 },
        { name: "Stephan Jaeger", bets: 4, wins: 0, pl: -11, roi: -100 },
        { name: "Nicolai Hojgaard", bets: 5, wins: 0, pl: -25, roi: -100 },
    ],
    onNotice: [
        { name: "Sepp Straka", bets: 3, wins: 0, pl: -25, consec: 3, reason: "T8 Players near-miss" },
        { name: "Ryo Hisatsune", bets: 3, wins: 0, pl: -7.50, consec: 3, reason: "T13 Players near-miss" },
        { name: "Pierceson Coody", bets: 3, wins: 0, pl: -15, consec: 2, reason: "Model backing strong" },
        { name: "Haotong Li", bets: 4, wins: 0, pl: -12.50, consec: 2, reason: "WD risk" },
    ],
    benched: [
        { name: "Min Woo Lee", bets: 4, wins: 0, pl: -40, consec: 4, reason: "0-4 all markets" },
        { name: "Ryan Gerard", bets: 4, wins: 0, pl: -30, consec: 4, reason: "0-4 all markets" },
        { name: "Si Woo Kim", bets: 3, wins: 0, pl: -30, consec: 3, reason: "Putting liability" },
        { name: "Max McGreevy", bets: 4, wins: 0, pl: -36, consec: 4, reason: "Over-exposed Cognizant" },
        { name: "Michael Brennan", bets: 3, wins: 0, pl: -17.50, consec: 3, reason: "Long darts not connecting" },
    ]
};

// Player scouting profiles (game evaluation, not betting)
const SCOUTING = [
    { name:"Scottie Scheffler", tier:"Elite", sg_tot:2.58, app:0.90, ott:0.71, arg:0.40, putt:0.57, putt_bermuda:0.52, putt_bent:0.65, putt_poa:0.48, dd:8.7,
      shape:"Fade", surface:"All", strengths:"Complete game. #1 in world. APP+ARG+PUTT all positive. Par 5 scorer.",
      weaknesses:"None significant. Occasionally loses focus in non-major events.", notes:"2x Masters champion. Withdrew Houston (2nd child). The standard." },
    { name:"Rory McIlroy", tier:"Elite", sg_tot:2.12, app:0.69, ott:0.94, arg:0.19, putt:0.30, putt_bermuda:0.25, putt_bent:0.38, putt_poa:0.22, dd:19.4,
      shape:"Draw", surface:"All", strengths:"Longest elite driver on Tour. APP solid. 2025 Masters champion (career slam).",
      weaknesses:"ARG can leak under pressure (Augusta 2011 collapse). Historically inconsistent with wedges.", notes:"Career Grand Slam completed 2025. Form lukewarm since." },
    { name:"Collin Morikawa", tier:"Elite", sg_tot:1.70, app:0.96, ott:0.73, arg:0.05, putt:-0.04, putt_bermuda:-0.12, putt_bent:0.08, putt_poa:-0.15, dd:2.0,
      shape:"Fade", surface:"Bentgrass best", strengths:"Best iron player on Tour. SG:APP #1 career. Distance control is elite.",
      weaknesses:"Putting. Career SG:PUTT slightly negative. ARG near zero. Not a scrambler.", notes:"2 majors (different). Back spasm at Players — monitor health." },
    { name:"Xander Schauffele", tier:"Elite", sg_tot:1.84, app:0.83, ott:0.60, arg:0.16, putt:0.25, putt_bermuda:0.22, putt_bent:0.3, putt_poa:0.18, dd:11.4,
      shape:"Fade", surface:"All", strengths:"Most balanced elite player. Positive in all 4 SG categories. 2 majors in 2024.",
      weaknesses:"Returning from early-season injury. Putting rank 76th this year — concerning.", notes:"Chasing career slam (needs Masters). 4 Augusta T10s." },
    { name:"Jordan Spieth", tier:"Contender", sg_tot:0.97, app:0.38, ott:0.09, arg:0.21, putt:0.29, putt_bermuda:0.18, putt_bent:0.42, putt_poa:0.15, dd:6.1,
      shape:"Variable", surface:"Bentgrass best", strengths:"Best Augusta record of generation (6-for-6 T10). Creative short game. Clutch putter. Course knowledge elite.",
      weaknesses:"Ball-striking has deteriorated. OTT +0.09 is below average. Distance disadvantage at long courses.", notes:"Won Valero 2021 to end 4-year drought. TPC SA SG:TOT #1." },
    { name:"Cameron Smith", tier:"Contender", sg_tot:0.31, app:-0.25, ott:-0.38, arg:0.48, putt:0.47, putt_bermuda:0.55, putt_bent:0.35, putt_poa:0.28, dd:-8.0,
      shape:"Draw", surface:"Bermuda", strengths:"Par 5 king at Augusta. 4-for-4 T10. Elite short game + putting. Best scrambler in field.",
      weaknesses:"LIV = no recent PGA data. Short hitter. OTT and APP both negative career. Ball-striking is a real weakness.", notes:"At +8000 the LIV discount is massive for a 4-for-4 Augusta T10 player." },
    { name:"Adam Scott", tier:"Contender", sg_tot:0.91, app:0.60, ott:0.30, arg:0.05, putt:-0.03, putt_bermuda:-0.08, putt_bent:0.12, putt_poa:-0.15, dd:8.2,
      shape:"Draw", surface:"Bentgrass", strengths:"Past Masters champion (2013). 3-for-3 T10 at Augusta. Ball speed up 4mph in 2026. APP elite.",
      weaknesses:"Age 45. Putting slightly negative career. ARG near zero. May lack closing gear at this stage.", notes:"Physical surge (ball speed) is real and DG regression suppresses it. 6mo-comp #5." },
    { name:"Jason Day", tier:"Veteran", sg_tot:0.58, app:-0.06, ott:0.01, arg:0.33, putt:0.29, putt_bermuda:0.22, putt_bent:0.38, putt_poa:0.15, dd:-1.4,
      shape:"Draw", surface:"Bentgrass", strengths:"4-for-4 Augusta T10 (T2, 3rd, T5, T5). SG:ARG +0.33 elite at hardest ARG course. Lag putter on bent.",
      weaknesses:"Ball-striking has cratered. APP -0.06 and OTT +0.01 are Tour average at best. Current form #53 in composite.", notes:"Pure Augusta history play. The course rewards his specific skill set even as overall game declines." },
    { name:"Kurt Kitayama", tier:"Contender", sg_tot:1.17, app:0.69, ott:0.57, arg:-0.01, putt:-0.09, putt_bermuda:-0.15, putt_bent:0.05, putt_poa:-0.12, dd:10.2,
      shape:"Fade", surface:"All", strengths:"SG:APP top-10 on Tour. Distance + iron combo is elite. RH models consistently rank him top-5.",
      weaknesses:"Putting. SG:PUTT -0.09 career. ARG -0.01 is neutral. Doesn't surge — steady T15-T25 grinder who rarely wins. 0-for-6 in our tracker.",
      notes:"The model loves him every week but he doesn't convert. Price is always right but form never peaks." },
    { name:"Nicolai Hojgaard", tier:"Contender", sg_tot:1.11, app:0.52, ott:0.36, arg:-0.01, putt:0.23, putt_bermuda:0.18, putt_bent:0.28, putt_poa:0.22, dd:14.3,
      shape:"Fade", surface:"Poa/Bent", strengths:"Distance + APP + positive putting. Versatile across course types. Top-10 in all 5 RH models at Houston.",
      weaknesses:"ARG slightly negative. No Augusta history. Still developing consistency — can MC unexpectedly.", notes:"Narrative consensus pick this season. Every source mentions him. Price has shortened accordingly." },
    { name:"Stephan Jaeger", tier:"Mid-field", sg_tot:0.40, app:0.10, ott:-0.22, arg:0.27, putt:0.26, putt_bermuda:0.2, putt_bent:0.3, putt_poa:0.25, dd:5.7,
      shape:"Straight", surface:"Poa", strengths:"2024 Houston winner. ARG +0.27 elite. Putting positive. Textbook weakness-masked player.",
      weaknesses:"OTT -0.22 (terrible driver). APP +0.10 is below average. Only works at courses that mask driving.", notes:"TAILWIND 1.31x is strongest recent form in the field. The weakness-masked thesis is proven by his own 2024 win." },
    { name:"Ben Griffin", tier:"Mid-field", sg_tot:1.05, app:0.35, ott:-0.04, arg:0.28, putt:0.46, putt_bermuda:0.38, putt_bent:0.45, putt_poa:0.42, dd:0.1,
      shape:"Draw", surface:"Poa", strengths:"ARG + PUTT combo = elite short game. Well-rounded without a glaring weakness.",
      weaknesses:"Not a bomber (DrDist +0.1). OTT slightly negative. Doesn't have the distance for the longest courses.", notes:"Dark horse surfaced by anti-bias protocol at Houston. Model 19 #8 (long/difficult). Under-narrated." },
    { name:"Wyndham Clark", tier:"Contender", sg_tot:0.62, app:0.30, ott:0.03, arg:0.27, putt:0.02, putt_bermuda:-0.05, putt_bent:0.08, putt_poa:0.02, dd:8.4,
      shape:"Fade", surface:"All", strengths:"ARG +0.27 amplified at short-grass courses. T5 Houston 2025. TAILWIND 1.29x = surging form.",
      weaknesses:"OTT and PUTT both near zero. Not an elite ball-striker or putter. Relies on form momentum.", notes:"2023 US Open champion. Form-dependent player whose ceiling is very high when everything clicks." },
    { name:"Tommy Fleetwood", tier:"Contender", sg_tot:1.73, app:0.66, ott:0.49, arg:0.33, putt:0.24, putt_bermuda:0.18, putt_bent:0.28, putt_poa:0.2, dd:1.4,
      shape:"Draw", surface:"All", strengths:"Complete game. Positive in all 4 SG categories. APP+ARG combo elite. 5yr-comp #7 at Augusta correlated courses.",
      weaknesses:"Hasn't won a major. Can be passive in final rounds. Not the longest off the tee.", notes:"3 Augusta T10s. Consistent contender who never quite breaks through at majors." },
    { name:"Russell Henley", tier:"Contender", sg_tot:1.56, app:0.60, ott:0.29, arg:0.29, putt:0.38, putt_bermuda:0.32, putt_bent:0.45, putt_poa:0.28, dd:-8.4,
      shape:"Fade", surface:"Bentgrass best", strengths:"APP+ARG+PUTT all positive = complete short-game player. 5yr-comp ARG #4 at Augusta courses. Lag putting elite.",
      weaknesses:"Short hitter (DrDist -8.4). OTT +0.29 is modest. Distance disadvantage at long courses.", notes:"Perennially underpriced. Fits every Augusta stat fingerprint. Market never gives him credit." },
    { name:"Corey Conners", tier:"Contender", sg_tot:0.83, app:0.56, ott:0.47, arg:-0.06, putt:-0.15, putt_bermuda:-0.22, putt_bent:-0.1, putt_poa:-0.18, dd:-1.6,
      shape:"Fade", surface:"All", strengths:"Iron play is elite (APP +0.56). OTT +0.47 = good total driving. 2x Valero champion. 3-for-3 Augusta T10s.",
      weaknesses:"Putting is a real problem (-0.15 career). ARG -0.06. The flat stick consistently costs him.", notes:"TPC San Antonio APP #1 over 20 rounds. The best iron player who can't putt." },
    { name:"Patrick Cantlay", tier:"Contender", sg_tot:1.30, app:0.56, ott:0.47, arg:0.15, putt:0.11, putt_bermuda:0.08, putt_bent:0.15, putt_poa:0.05, dd:5.1,
      shape:"Fade", surface:"All", strengths:"5yr-comp TOT #6 at Augusta-correlated courses. Balanced game. 4 Augusta T10s. Steady under pressure.",
      weaknesses:"Not a bomber. Form has dipped (1mo rank outside top-15). Market has drifted him to +6600.", notes:"At +6600 with 4 Augusta T10s and comp-course #6, the market may have over-corrected." },
    { name:"Will Zalatoris", tier:"Contender", sg_tot:0.66, app:0.54, ott:0.30, arg:0.05, putt:-0.23, putt_bermuda:-0.3, putt_bent:0.18, putt_poa:-0.25, dd:4.0,
      shape:"Fade", surface:"Bentgrass", strengths:"Approach is elite. 3-for-3 Augusta T10 (2nd, T6, T9). Born for Augusta. Bentgrass putter (+1.18/round at Augusta).",
      weaknesses:"Seasonal putting is terrible (-0.23). Injury history (back). Form has been poor since returning.", notes:"At +10000 the history is extraordinary but current form is a real question." },
    { name:"Ludvig Aberg", tier:"Elite", sg_tot:1.62, app:0.59, ott:0.62, arg:0.12, putt:0.29, putt_bermuda:0.25, putt_bent:0.32, putt_poa:0.22, dd:12.2,
      shape:"Fade", surface:"All", strengths:"Elite everything. T2 at Augusta on debut (2024). Young, ascending, fearless. Distance + iron combo.",
      weaknesses:"Only 1 Augusta start. ARG +0.12 is modest for the hardest ARG course.", notes:"If anyone is going to break the 'first-timers don't win' rule at Augusta, it's Aberg." },
    { name:"Rickie Fowler", tier:"Veteran", sg_tot:1.18, app:0.34, ott:0.46, arg:0.00, putt:0.38, putt_bermuda:0.35, putt_bent:0.4, putt_poa:0.3, dd:2.2,
      shape:"Draw", surface:"All", strengths:"Putting is a weapon (+0.38). OTT +0.46 is solid. Fan favourite with experience everywhere.",
      weaknesses:"ARG is dead zero. APP +0.34 is decent but not elite. Hasn't won since 2023. Missing Masters pressure.", notes:"Needs top-5 at Valero to qualify for Masters via OWGR. Hunger factor is real." },
    { name:"Max Greyserman", tier:"Mid-field", sg_tot:0.44, app:0.09, ott:-0.23, arg:0.17, putt:0.40, putt_bermuda:0.35, putt_bent:0.42, putt_poa:0.38, dd:6.5,
      shape:"Straight", surface:"Poa", strengths:"PUTT +0.40 is elite. ARG +0.17 fits short-grass courses. T7 Houston 2024 proves weakness-masked thesis.",
      weaknesses:"OTT -0.23 (terrible driver). APP +0.09 (below average). Only works at courses that mask driving.", notes:"Pure short-game player. Only bet at venues where driving accuracy is irrelevant." },
    { name:"Tony Finau", tier:"Contender", sg_tot:0.24, app:0.17, ott:-0.30, arg:0.29, putt:0.08, putt_bermuda:0.05, putt_bent:0.1, putt_poa:0.02, dd:3.6,
      shape:"Draw", surface:"Bermuda", strengths:"ARG +0.29 is elite. 2022 Houston winner + course record 62 twice. 4 Augusta T10s. TAILWIND form surges.",
      weaknesses:"OTT -0.30 has deteriorated significantly. APP +0.17 is below where it was. Distance advantage gone.", notes:"2022 version was elite. 2026 version relies on ARG and venue knowledge. Only play at weakness-masked courses." },
    { name:"Sam Burns", tier:"Contender", sg_tot:1.10, app:0.19, ott:0.30, arg:0.00, putt:0.60, putt_bermuda:0.55, putt_bent:0.62, putt_poa:0.52, dd:8.4,
      shape:"Draw", surface:"Bermuda/Poa", strengths:"SG:PUTT +0.60 = one of the best putters on Tour. Warm 1.14x form. Won Valspar 2022 on putting alone.",
      weaknesses:"APP +0.19 is weak for approach-dominant courses. ARG is dead zero.", notes:"If you need a putter at a putting course (Copperhead, Memorial Park), Burns is the play. Don't bet him at pure approach venues." },
    { name:"Maverick McNealy", tier:"Mid-field", sg_tot:1.34, app:0.44, ott:0.43, arg:0.17, putt:0.29, putt_bermuda:0.25, putt_bent:0.32, putt_poa:0.22, dd:6.8,
      shape:"Fade", surface:"All", strengths:"Well-rounded. All 4 SG categories positive. T3 Valero 2025. Rising steadily in world rankings.",
      weaknesses:"No signature strength that separates. Jack of all trades, master of none.", notes:"Comp #20 at Masters. +11000 could be huge value if he's genuinely top-20 quality." },
    { name:"Michael Thorbjornsen", tier:"Mid-field", sg_tot:0.98, app:0.31, ott:0.60, arg:0.05, putt:0.03, putt_bermuda:-0.02, putt_bent:0.05, putt_poa:0.02, dd:10.5,
      shape:"Fade", surface:"All", strengths:"Elite driver (OTT +0.60, DrDist +10.5). Young bomber with ceiling. Houston blind #9.",
      weaknesses:"APP +0.31 is good not great. ARG +0.05 and PUTT +0.03 near zero. No major pedigree yet.", notes:"Future star. Not ready for Augusta yet (no wins, no major T6). Valero/Houston type courses suit him now." },
    { name:"Keith Mitchell", tier:"Mid-field", sg_tot:0.86, app:0.45, ott:0.56, arg:-0.03, putt:-0.12, putt_bermuda:-0.18, putt_bent:-0.08, putt_poa:-0.12, dd:9.5,
      shape:"Fade", surface:"Poa", strengths:"APP+OTT double fit at long approach courses. Co-FRL Houston 2025. DG win edge at Houston.",
      weaknesses:"Putting -0.12 and ARG -0.03 both negative. Short game is the hole.", notes:"Best when both approach AND driving are amplified (Memorial Park, long courses). Don't play at scrambling courses." },
    { name:"Ricky Castillo", tier:"Mid-field", sg_tot:0.65, app:0.14, ott:0.36, arg:0.05, putt:0.10, putt_bermuda:0.08, putt_bent:0.12, putt_poa:0.05, dd:7.9,
      shape:"Draw", surface:"Paspalum/Bermuda", strengths:"Won Puerto Rico 2026 at +2200 = our biggest single win. Grinder who capitalizes in weaker fields.",
      weaknesses:"APP +0.14 is below average. Not competitive at Signature Events or majors.", notes:"Opposite-field specialist. Don't bet him at full-field events against elite players." },
    { name:"Jon Rahm", tier:"Elite", sg_tot:2.17, app:0.84, ott:0.79, arg:0.29, putt:0.26, putt_bermuda:0.2, putt_bent:0.32, putt_poa:0.18, dd:12.6,
      shape:"Draw", surface:"All", strengths:"Elite ball-striker with top-tier APP and OTT. Positive in all 4 SG categories. Complete game with no exploitable weakness.",
      weaknesses:"LIV schedule limits PGA Tour data recency. ARG and PUTT positive but not dominant.", notes:"Former world #1. 2 majors. LIV defection creates massive odds discount when eligible for majors." },
    { name:"Min Woo Lee", tier:"Contender", sg_tot:1.63, app:0.29, ott:0.63, arg:0.33, putt:0.38, putt_bermuda:0.32, putt_bent:0.4, putt_poa:0.35, dd:12.9,
      shape:"Draw", surface:"All", strengths:"Strong putter (+0.38) and elite ARG (+0.33). Long off the tee with bomber distance. Well-rounded short game.",
      weaknesses:"APP +0.29 is below average for his tier. Iron play is the gap in an otherwise strong profile.", notes:"Explosive young talent. Distance + short game combo is rare. Benched in our tracker (0-4 all markets)." },
    { name:"Jake Knapp", tier:"Contender", sg_tot:1.20, app:0.11, ott:0.44, arg:0.05, putt:0.60, putt_bermuda:0.52, putt_bent:0.62, putt_poa:0.58, dd:13.0,
      shape:"Fade", surface:"Poa", strengths:"Elite putter (+0.60 = one of the best on Tour). Bomber distance (DrDist +13.0). OTT +0.44 solid.",
      weaknesses:"APP +0.11 is well below average. ARG +0.05 near zero. Iron play and scrambling are real weaknesses.", notes:"Putt-dependent player. Only viable at putting-dominant courses (Copperhead type). Poa surface specialist." },
    { name:"Hideki Matsuyama", tier:"Contender", sg_tot:1.35, app:0.62, ott:-0.01, arg:0.45, putt:0.28, putt_bermuda:0.22, putt_bent:0.35, putt_poa:0.18, dd:-0.9,
      shape:"Fade", surface:"Bentgrass", strengths:"Elite iron player (APP +0.62) and scrambler (ARG +0.45). Putting positive. 2021 Masters champion.",
      weaknesses:"OTT -0.01 is essentially Tour average. Not a bomber (DrDist -0.9). Driving is the clear weak link.", notes:"Augusta champion who thrives at approach-dominant courses. Bentgrass specialist. Injury history (neck/back)." },
    { name:"Cameron Young", tier:"Contender", sg_tot:1.86, app:0.59, ott:0.69, arg:0.13, putt:0.44, putt_bermuda:0.38, putt_bent:0.48, putt_poa:0.35, dd:11.1,
      shape:"Draw", surface:"All", strengths:"Elite ball-striker (APP +0.59, OTT +0.69) with strong putting (+0.44). Bomber distance. One of the most talented non-winners.",
      weaknesses:"ARG +0.13 is modest. Has not converted talent into wins — closing ability is a question mark.", notes:"Multiple runner-up finishes. The talent is undeniable but the win column is empty. Price often reflects upside." },
    { name:"Shane Lowry", tier:"Contender", sg_tot:0.90, app:0.70, ott:0.14, arg:-0.05, putt:0.11, putt_bermuda:0.08, putt_bent:0.15, putt_poa:0.05, dd:-0.5,
      shape:"Fade", surface:"All", strengths:"Elite iron player (APP +0.70 = top-15 on Tour). 2019 Open champion. Experienced in wind and tough conditions.",
      weaknesses:"ARG -0.05 is slightly negative. Not long off the tee (DrDist -0.5). Putting only slightly positive.", notes:"Approach-dependent player. Best on courses where iron play is the primary separator. Wind-course specialist." },
    { name:"Harris English", tier:"Contender", sg_tot:1.09, app:0.11, ott:0.40, arg:0.12, putt:0.46, putt_bermuda:0.42, putt_bent:0.48, putt_poa:0.38, dd:2.2,
      shape:"Draw", surface:"Bermuda", strengths:"Elite putter (+0.46). Solid driver (OTT +0.40). Bermuda surface specialist. All-around positive SG profile.",
      weaknesses:"APP +0.11 is well below average. Iron play is the clear gap. Over-reliant on the flat stick.", notes:"Bermuda putting is his edge. Only bet at Bermuda-surface venues where iron play is forgiven." },
    { name:"Viktor Hovland", tier:"Contender", sg_tot:1.20, app:0.76, ott:0.10, arg:0.14, putt:0.20, putt_bermuda:0.15, putt_bent:0.25, putt_poa:0.18, dd:0.6,
      shape:"Fade", surface:"All", strengths:"Elite approach play (APP +0.76). Positive in all 4 SG categories. 2-time FedEx Cup champion.",
      weaknesses:"OTT +0.10 and DrDist +0.6 mean he's not long. ARG +0.14 is modest. Short game has been the historical leak.", notes:"Rebuilt short game has stabilized. When putting is on, he's a top-5 player. Approach is the engine." },
    { name:"Matt Fitzpatrick", tier:"Contender", sg_tot:1.69, app:0.67, ott:0.42, arg:0.30, putt:0.29, putt_bermuda:0.25, putt_bent:0.35, putt_poa:0.2, dd:2.7,
      shape:"Fade", surface:"Bentgrass", strengths:"Complete game — positive in all 4 categories. APP +0.67 and ARG +0.30 elite. US Open champion (2022).",
      weaknesses:"Not a bomber (DrDist +2.7). OTT +0.42 is good but not elite. Distance disadvantage at long courses.", notes:"2026 Valspar champion (-11, 68-69-68-68). Won with consistent ball-striking on Copperhead's small greens. US Open champion (2022). Bentgrass/Poa precision player who thrives at accuracy-rewarding setups. Masters composite #17 — strong Augusta fit (APP + ARG + Poa putting)." },
    { name:"Si Woo Kim", tier:"Contender", sg_tot:1.52, app:0.81, ott:0.66, arg:0.24, putt:-0.19, putt_bermuda:-0.25, putt_bent:-0.12, putt_poa:-0.18, dd:-2.7,
      shape:"Variable", surface:"All", strengths:"Elite ball-striker — APP +0.81 and OTT +0.66 are both top-tier. ARG +0.24 solid. Shot-shaping ability is rare.",
      weaknesses:"Putting is a real liability (-0.19). Short hitter (DrDist -2.7). The flat stick consistently costs him.", notes:"Benched in our tracker due to putting. When the putter cooperates he's a winner, but it rarely does." },
    { name:"Sungjae Im", tier:"Mid-field", sg_tot:0.52, app:-0.20, ott:0.09, arg:0.41, putt:0.22, putt_bermuda:0.18, putt_bent:0.25, putt_poa:0.15, dd:-2.3,
      shape:"Draw", surface:"Bermuda", strengths:"Elite scrambler (ARG +0.41). Positive putter (+0.22). Bermuda specialist. Iron man — never misses events.",
      weaknesses:"APP -0.20 is a significant weakness. OTT +0.09 near average. Ball-striking overall is below par.", notes:"Short-game-only player. Only viable at courses where ARG is amplified and approach is forgiven." },
    { name:"Robert MacIntyre", tier:"Contender", sg_tot:1.61, app:0.22, ott:0.52, arg:0.23, putt:0.64, putt_bermuda:0.58, putt_bent:0.65, putt_poa:0.55, dd:3.7,
      shape:"Draw", surface:"All", strengths:"Elite putter (+0.64 = top-5 on Tour). Strong driver (OTT +0.52). Positive in all 4 SG categories.",
      weaknesses:"APP +0.22 is below average for his talent level. Iron play is the clear gap in the profile.", notes:"Scottish left-hander. Putting carries the game. When approach is even slightly on, he contends anywhere." },
    { name:"Chris Gotterup", tier:"Contender", sg_tot:1.09, app:0.40, ott:0.49, arg:0.08, putt:0.12, putt_bermuda:0.08, putt_bent:0.15, putt_poa:0.1, dd:16.2,
      shape:"Draw", surface:"All", strengths:"Longest hitter in our database (DrDist +16.2). OTT +0.49 and APP +0.40 both solid. Positive in all 4 categories.",
      weaknesses:"ARG +0.08 and PUTT +0.12 near neutral. Short game doesn't match the ball-striking.", notes:"Pure bomber. Won our Arnold Palmer matchup vs Thomas. Best at courses where distance creates separation." },
    { name:"Marco Penge", tier:"Mid-field", sg_tot:0.52, app:0.04, ott:0.83, arg:-0.22, putt:-0.14, putt_bermuda:-0.08, putt_bent:-0.12, putt_poa:-0.05, dd:20.2,
      shape:"Fade", surface:"All", strengths:"Extreme bomber — OTT +0.83 and DrDist +20.2 are elite. Longest driver in the database by a wide margin.",
      weaknesses:"Everything else. APP +0.04 near zero, ARG -0.22 and PUTT -0.14 both negative. All-or-nothing distance player.", notes:"Only viable at courses where extreme distance creates enough advantage to offset poor short game." },
    { name:"J.J. Spaun", tier:"Mid-field", sg_tot:1.10, app:0.64, ott:0.44, arg:0.07, putt:-0.05, putt_bermuda:-0.08, putt_bent:0.02, putt_poa:-0.05, dd:2.6,
      shape:"Fade", surface:"All", strengths:"Elite approach play (APP +0.64). OTT +0.44 solid. Ball-striking combo is strong.",
      weaknesses:"Putting slightly negative (-0.05). ARG +0.07 near zero. Short game doesn't support the iron play.", notes:"Underrated approach specialist. Profile is similar to Kitayama — great irons, weak putter, steady grinder." },
    { name:"Sepp Straka", tier:"Contender", sg_tot:1.09, app:0.60, ott:0.33, arg:0.05, putt:0.12, putt_bermuda:0.08, putt_bent:0.15, putt_poa:0.1, dd:-0.2,
      shape:"Fade", surface:"All", strengths:"Elite iron player (APP +0.60). Positive in all 4 SG categories. Reliable ball-striker.",
      weaknesses:"ARG +0.05 and PUTT +0.12 are modest. Not a bomber (DrDist -0.2). Short game is functional not special.", notes:"On Notice in our tracker after T8 Players near-miss. Approach-first player who needs surface to cooperate." },
    { name:"Alex Noren", tier:"Mid-field", sg_tot:1.00, app:0.33, ott:-0.06, arg:0.28, putt:0.44, putt_bermuda:0.38, putt_bent:0.48, putt_poa:0.4, dd:-6.3,
      shape:"Fade", surface:"All", strengths:"Strong putter (+0.44) and solid scrambler (ARG +0.28). Short game is the weapon.",
      weaknesses:"OTT -0.06 slightly negative. DrDist -6.3 means he's one of the shorter hitters. Distance disadvantage is real.", notes:"Short-game specialist. Best at tight courses where accuracy matters more than length." },
    { name:"Justin Thomas", tier:"Contender", sg_tot:0.96, app:0.36, ott:-0.12, arg:0.41, putt:0.31, putt_bermuda:0.28, putt_bent:0.35, putt_poa:0.22, dd:5.6,
      shape:"Fade", surface:"All", strengths:"Elite scrambler (ARG +0.41) and strong putter (+0.31). 2 majors. Short game has compensated for ball-striking decline.",
      weaknesses:"OTT -0.12 has deteriorated significantly from peak. APP +0.36 is good not great. The driver is the problem.", notes:"Post-peak JT. The talent is still there but OTT decline is concerning. ARG carries the game now." },
    { name:"Denny McCarthy", tier:"Mid-field", sg_tot:0.22, app:0.05, ott:-0.29, arg:0.09, putt:0.36, putt_bermuda:0.32, putt_bent:0.38, putt_poa:0.3, dd:-4.0,
      shape:"Straight", surface:"Bermuda", strengths:"Strong putter (+0.36). Bermuda surface specialist. Straight ball flight is consistent.",
      weaknesses:"OTT -0.29 is a major weakness. APP +0.05 near zero. Ball-striking is well below Tour average.", notes:"Pure putter. Only viable at courses where driving and approach are both masked. Very narrow range of fits." },
    { name:"Jordan Smith", tier:"Mid-field", sg_tot:0.76, app:0.34, ott:0.49, arg:-0.04, putt:-0.03, putt_bermuda:-0.08, putt_bent:0.02, putt_poa:-0.05, dd:5.2,
      shape:"Draw", surface:"All", strengths:"Solid driver (OTT +0.49, DrDist +5.2). APP +0.34 decent. Ball-striking is the strength.",
      weaknesses:"ARG -0.04 and PUTT -0.03 both slightly negative. Short game is the weak link.", notes:"Ball-striking-only player. Needs courses that reward driving and approach over scrambling and putting." },
    { name:"Tom Hoge", tier:"Mid-field", sg_tot:0.48, app:0.09, ott:0.40, arg:-0.08, putt:-0.09, putt_bermuda:-0.12, putt_bent:-0.05, putt_poa:-0.08, dd:5.8,
      shape:"Fade", surface:"All", strengths:"Solid driver (OTT +0.40, DrDist +5.8). Positional off the tee.",
      weaknesses:"APP +0.09, ARG -0.08, PUTT -0.09 — approach, scrambling, and putting all near zero or negative.", notes:"Driving-only player. Very narrow profile. Only works at venues where OTT is the primary separator." },
    { name:"Pierceson Coody", tier:"Mid-field", sg_tot:0.75, app:0.32, ott:0.61, arg:-0.15, putt:-0.03, putt_bermuda:-0.08, putt_bent:0.02, putt_poa:-0.05, dd:13.7,
      shape:"Fade", surface:"All", strengths:"Strong driver (OTT +0.61) and bomber distance (DrDist +13.7). APP +0.32 is decent.",
      weaknesses:"ARG -0.15 is a real weakness. PUTT -0.03 near zero. Scrambling is the hole in the game.", notes:"On Notice in our tracker. Young bomber whose short game needs development. Model backing remains strong." },
    { name:"Sahith Theegala", tier:"Contender", sg_tot:0.91, app:0.46, ott:0.01, arg:0.20, putt:0.24, putt_bermuda:0.2, putt_bent:0.28, putt_poa:0.18, dd:3.9,
      shape:"Draw", surface:"All", strengths:"Balanced game — positive in all 4 SG categories. APP +0.46 is strong. ARG and PUTT both solid.",
      weaknesses:"OTT +0.01 is essentially average. DrDist +3.9 modest. Not a bomber — no distance edge.", notes:"Well-liked by narratives. Complete game without a signature elite category. Fan favourite with closing ability." },
    { name:"Ryan Fox", tier:"Mid-field", sg_tot:0.54, app:0.18, ott:0.12, arg:0.10, putt:0.14, putt_bermuda:0.1, putt_bent:0.18, putt_poa:0.12, dd:9.1,
      shape:"Draw", surface:"All", strengths:"Bomber distance (DrDist +9.1). All 4 SG categories positive. No glaring weakness.",
      weaknesses:"No elite category either. APP +0.18, OTT +0.12, ARG +0.10, PUTT +0.14 all modest.", notes:"Jack of all trades, master of none. Kiwi who performs best at international events and bomber tracks." },
    { name:"Davis Thompson", tier:"Mid-field", sg_tot:0.71, app:0.38, ott:0.46, arg:0.08, putt:-0.20, putt_bermuda:-0.25, putt_bent:-0.15, putt_poa:-0.2, dd:3.4,
      shape:"Fade", surface:"All", strengths:"Strong ball-striker (APP +0.38, OTT +0.46). Good total driving package.",
      weaknesses:"Putting is a major weakness (-0.20). ARG +0.08 near zero. The flat stick consistently costs him contention.", notes:"Young ball-striker whose putting holds him back. Profile is similar to early-career Morikawa — irons carry, putter drags." },
    { name:"Nico Echavarria", tier:"Mid-field", sg_tot:0.45, app:0.21, ott:0.12, arg:-0.11, putt:0.23, putt_bermuda:0.28, putt_bent:0.18, putt_poa:0.15, dd:-5.3,
      shape:"Draw", surface:"Bermuda", strengths:"Bermuda putter. Won Cognizant 2026 at 50/1. Can contend at penalty courses.",
      weaknesses:"ARG negative. OTT modest. Not competitive at long bomber courses.", notes:"Our biggest winner. E/W 1/4 5pl $10 returned $322.50. Bermuda-putting specialist." },
    { name:"Alex Smalley", tier:"Mid-field", sg_tot:0.70, app:0.28, ott:0.37, arg:0.04, putt:0.00, putt_bermuda:-0.05, putt_bent:0.05, putt_poa:-0.02, dd:4.9,
      shape:"Fade", surface:"All", strengths:"Balanced ball-striker. OTT +0.37 is solid. Consistent mid-field performer.",
      weaknesses:"Putting is dead neutral. No standout skill that separates. ARG near zero.", notes:"Steady but unspectacular. Comp-course data often ranks him 20-30." },
    { name:"Austin Smotherman", tier:"Mid-field", sg_tot:0.52, app:0.48, ott:0.41, arg:-0.12, putt:-0.26, putt_bermuda:-0.22, putt_bent:-0.28, putt_poa:-0.25, dd:4.2,
      shape:"Fade", surface:"All", strengths:"APP +0.48 is quietly elite. OTT solid. Won FRL at Cognizant at +10000. Ball-striking can go very low.",
      weaknesses:"Putting is terrible (-0.26). ARG negative. Short game is the hole.", notes:"Our Cognizant FRL winner at +10000 ($2.50 returned $158.75). Ball-striker whose putter limits his ceiling." },
    { name:"Aldrich Potgieter", tier:"Mid-field", sg_tot:-0.20, app:-0.23, ott:0.54, arg:-0.31, putt:-0.21, putt_bermuda:-0.18, putt_bent:-0.22, putt_poa:-0.20, dd:22.0,
      shape:"Draw", surface:"All", strengths:"Longest driver in any field he enters (DrDist +22.0). Pure bomber.",
      weaknesses:"Everything except distance. APP, ARG, PUTT all negative. Can't hit greens, can't scramble, can't putt.", notes:"Long drive specialist, not a golfer yet. Mayo: 'better off in long drive competitions until he refines his game.'" },
    { name:"Brian Harman", tier:"Veteran", sg_tot:0.34, app:-0.04, ott:-0.12, arg:0.18, putt:0.32, putt_bermuda:0.35, putt_bent:0.28, putt_poa:0.25, dd:-8.5,
      shape:"Draw", surface:"Bermuda", strengths:"2023 Open champion. 2025 Valero winner in brutal wind. Elite putter. Short game carries.",
      weaknesses:"OTT and APP both negative. Short hitter. Only wins when conditions are brutal and ball-strikers fail.", notes:"Defending Valero champion. Won at -9 in 30mph north wind. TPC SA SG:TOT #4 over 8 rounds." },
    { name:"Eric Cole", tier:"Mid-field", sg_tot:0.12, app:0.14, ott:-0.56, arg:0.21, putt:0.33, putt_bermuda:0.28, putt_bent:0.35, putt_poa:0.30, dd:-1.8,
      shape:"Straight", surface:"Poa", strengths:"SG:PUTT +0.33 is elite. ARG +0.21 positive. Short game specialist.",
      weaknesses:"OTT -0.56 is terrible. Shortest driver on Tour. Only works at courses where driving is irrelevant.", notes:"Putter-only play. Bet at Valspar (+11000) on Poa putting thesis. MC'd." },
    { name:"Alejandro Tosti", tier:"Mid-field", sg_tot:-0.01, app:0.05, ott:0.10, arg:-0.05, putt:-0.08, putt_bermuda:-0.10, putt_bent:-0.05, putt_poa:-0.08, dd:5.5,
      shape:"Draw", surface:"All", strengths:"Co-FRL at Houston 2025 (opened 65, T5 finish). Can go low in R1.",
      weaknesses:"Everything is near zero. No standout skill. Relies on hot weeks.", notes:"Houston FRL dart. TAILWIND 1.89x form ratio (highest in field). Results haven't matched the form signal." },
    { name:"Christiaan Bezuidenhout", tier:"Mid-field", sg_tot:0.66, app:0.29, ott:-0.24, arg:0.29, putt:0.31, putt_bermuda:0.25, putt_bent:0.35, putt_poa:0.28, dd:-11.9,
      shape:"Fade", surface:"Bentgrass", strengths:"ARG +0.29 and PUTT +0.31 = elite short game combo. Positive in both.",
      weaknesses:"OTT -0.24 and DrDist -11.9. Shortest hitter in most fields. Distance disadvantage is severe.", notes:"South African with short-game feel. Only bet at courses that mask driving. Valero composite #18." },
    { name:"Mackenzie Hughes", tier:"Mid-field", sg_tot:0.22, app:0.01, ott:-0.22, arg:0.25, putt:0.19, putt_bermuda:0.15, putt_bent:0.22, putt_poa:0.18, dd:-3.1,
      shape:"Fade", surface:"All", strengths:"ARG +0.25 is strong. Putting positive. Short game grinder.",
      weaknesses:"APP +0.01 (Tour average). OTT -0.22 (poor driver). Can't ball-strike.", notes:"Valero composite #5 from comp-course data. TAILWIND 1.26x form. $2.50 DK bet at +11500." },
    { name:"Matti Schmid", tier:"Mid-field", sg_tot:0.14, app:-0.20, ott:0.17, arg:-0.06, putt:0.23, putt_bermuda:0.20, putt_bent:0.25, putt_poa:0.18, dd:8.1,
      shape:"Draw", surface:"All", strengths:"Putting +0.23 is his weapon. Some distance.",
      weaknesses:"APP -0.20 is a real problem. ARG near zero.", notes:"German with a putter. Limited upside at approach-dominant courses." },
    { name:"Sami Valimaki", tier:"Mid-field", sg_tot:0.03, app:0.08, ott:0.22, arg:-0.07, putt:-0.13, putt_bermuda:-0.10, putt_bent:-0.15, putt_poa:-0.12, dd:6.5,
      shape:"Draw", surface:"All", strengths:"OTT +0.22 gives some driver advantage.",
      weaknesses:"Putting is negative. ARG negative. Below-average game outside of driving.", notes:"Finnish player with some distance. Hasn't consistently performed on PGA Tour." },
    { name:"Justin Rose", tier:"Veteran", sg_tot:0.83, app:0.54, ott:0.11, arg:0.06, putt:0.12, putt_bermuda:0.08, putt_bent:0.15, putt_poa:0.10, dd:2.4,
      shape:"Fade", surface:"Bentgrass", strengths:"5x R1 leader at Augusta (record). APP +0.54 elite. 4 Augusta T10s.",
      weaknesses:"Comp #46 suggests current ability well below pedigree. Can't convert leads into wins.", notes:"The most overpriced player at the Masters by our composite. Market prices the name and Augusta R1 history, not current form." },
    { name:"Ryan Gerard", tier:"Mid-field", sg_tot:1.27, app:0.80, ott:0.51, arg:0.01, putt:-0.05, putt_bermuda:-0.08, putt_bent:-0.02, putt_poa:0.48, dd:1.6,
      shape:"Fade", surface:"Poa", strengths:"SG:APP +0.80 is top-10 on Tour. Elite iron player. Poa putting is his best surface (+0.48).",
      weaknesses:"ARG +0.01 and PUTT -0.05 overall. Can't chip or putt on most surfaces. Burned out from overplaying.", notes:"Benched (0-4 in tracker). WD from Valero. Playing too much golf. Co-FRL Houston 2025. Mayo: 'he can't chip and can't putt.'" },
    { name:"Jacob Bridgeman", tier:"Contender", sg_tot:1.36, app:0.30, ott:0.23, arg:0.15, putt:0.69, putt_bermuda:0.62, putt_bent:0.72, putt_poa:0.65, dd:3.1,
      shape:"Draw", surface:"All", strengths:"Best putter on Tour (SG:PUTT +0.69). Positive everywhere. Complete game.",
      weaknesses:"Not the longest. APP +0.30 is good not elite. Relatively unproven at majors.", notes:"Young player with the best flatstick on Tour. Augusta composite puts him at interesting prices." },
    { name:"Haotong Li", tier:"Mid-field", sg_tot:0.49, app:0.29, ott:0.37, arg:-0.18, putt:0.00, putt_bermuda:-0.05, putt_bent:0.05, putt_poa:-0.02, dd:5.4,
      shape:"Draw", surface:"All", strengths:"Ball-striking combo (APP +0.29, OTT +0.37) is solid. Distance.",
      weaknesses:"ARG -0.18. Putting dead flat. Short game is a real hole.", notes:"On Notice in our tracker. WD risk (withdrew AP Inv). Inconsistent availability." },
    { name:"A.J. Ewart", tier:"Mid-field", sg_tot:0.15, app:-0.07, ott:0.11, arg:-0.25, putt:0.08, putt_bermuda:0.05, putt_bent:0.10, putt_poa:0.06, dd:10.3,
      shape:"Draw", surface:"All", strengths:"Some distance. Comp-course data ranks him surprisingly high.",
      weaknesses:"ARG -0.25 is poor. APP negative. Limited Tour pedigree.", notes:"Valero dark horse ($1.25 at +34000). Comp 6mo #4 at correlated courses. Anti-bias protocol find." },
    { name:"Akshay Bhatia", tier:"Contender", sg_tot:1.44, app:0.74, ott:0.22, arg:0.06, putt:0.41, putt_bermuda:0.45, putt_bent:0.38, putt_poa:0.35, dd:1.4,
      shape:"Draw", surface:"Bermuda", strengths:"APP +0.74 elite. PUTT +0.41 (Bermuda best). Won AP Inv 2026 and Valero 2024.",
      weaknesses:"OTT +0.22 modest. ARG near zero. No Augusta pedigree.", notes:"In India for Hero Indian Open pre-Masters. Circadian rhythm concern. Pre-placed Masters bet at +5500." },
    { name:"Daniel Berger", tier:"Contender", sg_tot:0.69, app:0.63, ott:0.38, arg:-0.22, putt:-0.09, putt_bermuda:-0.12, putt_bent:-0.05, putt_poa:-0.08, dd:1.9,
      shape:"Fade", surface:"All", strengths:"APP +0.63 is elite. Comp 6mo #3 and 3yr #7 at Valero correlated courses.",
      weaknesses:"PUTT and ARG both negative. Short game is a hole. Back injury history.", notes:"Playoff loss to Bhatia at AP Inv (shot 63 FRL). Back concerns persist. Stewart: 'still can't chip.'" },
    { name:"Lucas Glover", tier:"Veteran", sg_tot:0.06, app:0.28, ott:0.01, arg:0.06, putt:-0.29, putt_bermuda:-0.32, putt_bent:-0.25, putt_poa:-0.28, dd:-2.0,
      shape:"Fade", surface:"All", strengths:"TPC SA SG:TOT #11 over 16 rounds. APP #8 at the venue. Course specialist.",
      weaknesses:"Putting is terrible (-0.29). Overall game has declined significantly.", notes:"Form ratio 2.31x (highest on Tour) but from a very low baseline. Veteran grinding on course knowledge." },
    { name:"Mac Meissner", tier:"Mid-field", sg_tot:0.68, app:0.41, ott:0.12, arg:0.15, putt:-0.00, putt_bermuda:-0.03, putt_bent:0.02, putt_poa:-0.01, dd:2.6,
      shape:"Fade", surface:"All", strengths:"APP +0.41 solid. ARG +0.15 positive. Balanced ball-striker.",
      weaknesses:"Not a bomber (DrDist +2.6). Putting dead flat. No distance advantage.", notes:"Mayo's model #1 pick at Valspar. Shot 62 in 2025 at TPC SA." },
    { name:"Matt Kuchar", tier:"Veteran", sg_tot:-0.07, app:-0.07, ott:-0.39, arg:0.18, putt:0.21, putt_bermuda:0.18, putt_bent:0.22, putt_poa:0.15, dd:-5.0,
      shape:"Fade", surface:"All", strengths:"TPC SA SG:TOT #3 over 18 rounds. ARG +0.18. Veteran course knowledge.",
      weaknesses:"APP and OTT both negative. Game has declined significantly. Short hitter.", notes:"18 rounds of strong TPC SA data. Pure course-knowledge play at the Valero. Not viable elsewhere." },
    { name:"Matt McCarty", tier:"Mid-field", sg_tot:0.73, app:0.12, ott:0.19, arg:-0.01, putt:0.42, putt_bermuda:0.38, putt_bent:0.45, putt_poa:0.40, dd:-2.7,
      shape:"Straight", surface:"Poa", strengths:"PUTT +0.42 is elite. Best putter at Valspar comp rank #2 on Poa surfaces.",
      weaknesses:"APP +0.12 is below average. No ball-striking edge.", notes:"Valspar bet at +6600. Putting weapon on Poa Triv greens." },
    { name:"Max McGreevy", tier:"Mid-field", sg_tot:0.63, app:0.30, ott:0.47, arg:-0.01, putt:-0.13, putt_bermuda:-0.10, putt_bent:-0.15, putt_poa:-0.12, dd:-3.0,
      shape:"Fade", surface:"All", strengths:"OTT +0.47 gives some driver advantage. APP +0.30 is decent.",
      weaknesses:"Putting is negative (-0.13). ARG near zero.", notes:"Benched (0-4 including 0-3 at Cognizant). Over-exposed in early season." },
    { name:"Michael Brennan", tier:"Mid-field", sg_tot:0.57, app:0.11, ott:0.30, arg:-0.04, putt:0.21, putt_bermuda:0.18, putt_bent:0.23, putt_poa:0.20, dd:10.7,
      shape:"Draw", surface:"All", strengths:"Carry distance elite. RH Model 15 #2 (carry + prox 200+). Can win at bomber courses.",
      weaknesses:"APP +0.11 is weak. ARG near zero. Relies on distance.", notes:"Benched (0-3). Houston composite dark horse. Mayo and Stewart both mentioned as live. ARG concern at short-grass courses." },
    { name:"Patrick Reed", tier:"Veteran", sg_tot:0.79, app:0.50, ott:-0.04, arg:0.16, putt:0.16, putt_bermuda:0.20, putt_bent:0.12, putt_poa:0.15, dd:-4.1,
      shape:"Draw", surface:"Bermuda", strengths:"Won Masters 2018 on ARG + PUTT. 4 Augusta T10s. Major pedigree on Bermuda.",
      weaknesses:"OTT -0.04 poor. LIV = no recent PGA data. Game has declined.", notes:"LIV player with elite Augusta history. ARG #5 at comp courses. Market prices the history heavily." },
    { name:"Sam Stevens", tier:"Mid-field", sg_tot:0.92, app:0.28, ott:0.55, arg:0.11, putt:-0.02, putt_bermuda:-0.05, putt_bent:0.02, putt_poa:-0.03, dd:5.7,
      shape:"Fade", surface:"All", strengths:"OTT +0.55 is strong. Well-rounded ball-striker. SG:TOT +0.92 is solid.",
      weaknesses:"Putting slightly negative. Not a separator with the flatstick.", notes:"TPC SA SG:TOT #7 over 10 rounds. Neutral form. Consistent without being spectacular." },
    { name:"Sudarshan Yellamaraju", tier:"Mid-field", sg_tot:0.37, app:0.04, ott:0.26, arg:-0.04, putt:0.09, putt_bermuda:0.06, putt_bent:0.12, putt_poa:0.08, dd:8.6,
      shape:"Draw", surface:"All", strengths:"Some distance. Comp-course models consistently rank him in the 20-35 range.",
      weaknesses:"APP +0.04 is Tour average. ARG slightly negative. No elite skill.", notes:"Anti-bias protocol dark horse. Ghost ownership. $2.50 Valero at +14000 and Houston analysis flagged him at T7." },
    { name:"Taylor Pendrith", tier:"Contender", sg_tot:0.94, app:0.29, ott:0.49, arg:0.11, putt:0.04, putt_bermuda:0.02, putt_bent:0.06, putt_poa:0.03, dd:10.7,
      shape:"Fade", surface:"All", strengths:"SG:TOT +0.94 is strong. OTT +0.49 bomber. Well-rounded.",
      weaknesses:"Putting near zero (+0.04). Form has been cool (0.83x recently).", notes:"Co-FRL Houston 2025. TPC SA history #26. Solid player whose form dips create value at longer prices." },
    { name:"Thorbjorn Olesen", tier:"Mid-field", sg_tot:0.53, app:0.32, ott:0.19, arg:0.02, putt:-0.00, putt_bermuda:-0.03, putt_bent:0.02, putt_poa:-0.01, dd:1.2,
      shape:"Fade", surface:"All", strengths:"TPC SA SG:TOT #11. APP #16 and ARG #15 at the venue. Ball-striker who fits TPC SA.",
      weaknesses:"Putting dead flat. Not a bomber. No standout skill beyond iron play.", notes:"Course specialist at TPC San Antonio. T10 Valspar 2025 on Sunday 69. European veteran." },
    { name:"Zach Bauchou", tier:"Mid-field", sg_tot:0.25, app:0.15, ott:0.22, arg:-0.08, putt:0.05, putt_bermuda:0.02, putt_bent:0.08, putt_poa:0.04, dd:4.8,
      shape:"Draw", surface:"All", strengths:"Some distance and approach skill. Comp courses rank him mid-field.",
      weaknesses:"ARG negative. Relatively unproven. Small sample on Tour.", notes:"Valero composite #7. Comp 6mo #42, 3yr #51. Young player showing up in models." },
    { name:"Kristoffer Reitan", tier:"Mid-field", sg_tot:0.56, app:-0.15, ott:0.55, arg:-0.15, putt:0.30, putt_bermuda:0.25, putt_bent:0.32, putt_poa:0.28, dd:9.1,
      shape:"Draw", surface:"Poa", strengths:"OTT +0.55 strong driver. PUTT +0.30 positive especially on Poa. Distance.",
      weaknesses:"APP -0.15 is poor. ARG -0.15 also negative. Ball-striking tee-to-green is weak.", notes:"On Notice (0-3). HEADWIND form at Valspar. Skill base says better than results show." },
    { name:"Ryo Hisatsune", tier:"Mid-field", sg_tot:0.91, app:0.47, ott:0.41, arg:0.11, putt:-0.08, putt_bermuda:-0.12, putt_bent:-0.05, putt_poa:-0.08, dd:0.3,
      shape:"Fade", surface:"All", strengths:"APP +0.47 strong. OTT +0.41 solid. Ball-striking is genuine. SG:TOT +0.91.",
      weaknesses:"Putting negative (-0.08). Inconsistent week to week.", notes:"On Notice (0-3). T13 Players near-miss. Valero RH model #10. Ball-striking profile that needs a hot putting week." },
    { name:"Rasmus Hojgaard", tier:"Contender", sg_tot:0.76, app:0.17, ott:0.24, arg:-0.03, putt:0.39, putt_bermuda:0.35, putt_bent:0.42, putt_poa:0.38, dd:14.2,
      shape:"Fade", surface:"All", strengths:"PUTT +0.39 is strong (better than brother Nicolai). DrDist +14.2 = bomber. Distance + putting combo.",
      weaknesses:"APP +0.17 is modest. ARG near zero. Iron play not elite.", notes:"Houston dark horse surfaced by anti-bias protocol. M15#5, M19#7. Better putter than Nicolai on Poa." },
];

// Player status flags (updated from conversation intel, podcasts, news)
// Types: injury, rest, travel, motivation, equipment, form, note
const PLAYER_STATUS = [
    { player: "Collin Morikawa", type: "injury", status: "Back spasm. WD after 1 hole at Players. Returned at Valero but status unclear.", severity: "caution", updated: "Mar 28" },
    { player: "Ryan Gerard", type: "rest", status: "Burned out from playing every week including international travel. WD from Valero. Taking time off before Masters.", severity: "info", updated: "Mar 28" },
    { player: "Akshay Bhatia", type: "travel", status: "In India for Hero Indian Open (sponsor obligation). MC there. Flying back 2 weeks before Masters. Circadian rhythm concern.", severity: "caution", updated: "Mar 28" },
    { player: "Pierceson Coody", type: "injury", status: "Back injury. WD from Houston after R1. May play Valero if healthy. Needs win to qualify for Masters.", severity: "warning", updated: "Mar 27" },
    { player: "Scottie Scheffler", type: "rest", status: "WD from Houston (birth of second child). Preparing for Masters. Fully healthy.", severity: "info", updated: "Mar 25" },
    { player: "Xander Schauffele", type: "injury", status: "Returning from early-season injury. Showed form at Valspar (T4). Putting rank 76th this year.", severity: "caution", updated: "Mar 22" },
    { player: "Will Zalatoris", type: "injury", status: "Back from injury. First return at Houston. MC on the number. Approach play looked ok, driving and chipping did not.", severity: "caution", updated: "Mar 27" },
    { player: "Nicolai Hojgaard", type: "motivation", status: "2nd at Houston (-17) heading into R4. Masters qualification virtually locked. Likely WDs from Valero.", severity: "info", updated: "Mar 29" },
    { player: "Michael Thorbjornsen", type: "motivation", status: "T3 at Houston (-12). Should crack OWGR top 50 for Masters invite with this finish.", severity: "info", updated: "Mar 29" },
];

// Course library
const COURSES = [
    {
        name: "Augusta National", event: "The Masters", surface: "Bentgrass", length: "7,555 yds",
        archetype: "Second-shot + Short game", scoring: "Difficult", dataKey: "masters",
        topStats: ["SG:APP 150+", "Course History", "Carry Distance", "SG:ARG", "Par 5 BoB%"],
        masked: "Driving accuracy, seasonal putting", amplified: "Approach precision, short-grass ARG, Par 5 scoring",
        bets: 4, pl: 0, status: "upcoming"
    },
    {
        name: "Memorial Park GC", event: "Houston Open", surface: "Poa Trivialis", length: "7,475 yds",
        archetype: "Second-shot + Bomber", scoring: "Hard", dataKey: "houston",
        topStats: ["SG:APP", "DrDist", "SG:ARG (short grass)", "SG:OTT", "Bogey Avoidance"],
        masked: "Driving accuracy (1.25in rough)", amplified: "Distance, approach 150+, short-grass scrambling",
        bets: 11, pl: -40, status: "live"
    },
    {
        name: "Innisbrook (Copperhead)", event: "Valspar Championship", surface: "Poa Trivialis", length: "7,352 yds",
        archetype: "Second-shot + Poa putting", scoring: "Hard", dataKey: "valspar",
        topStats: ["SG:APP", "SG:OTT (less-than-driver)", "Bogey Avoidance", "SG:PUTT Poa", "Par 3 scoring"],
        masked: "None significant", amplified: "Approach precision, positional driving, Poa putting",
        bets: 11, pl: -85, status: "settled"
    },
    {
        name: "TPC Sawgrass", event: "The Players", surface: "Bermuda/Poa", length: "7,245 yds",
        archetype: "Second-shot + Penalty", scoring: "Hard", dataKey: "players",
        topStats: ["SG:APP", "SG:PUTT Poa", "Bogey Avoidance", "SG:ARG", "Course History"],
        masked: "None", amplified: "Iron precision, scrambling, mental fortitude",
        bets: 17, pl: -110, status: "settled"
    },
    {
        name: "Bay Hill Club & Lodge", event: "Arnold Palmer Inv", surface: "Bermuda", length: "7,466 yds",
        archetype: "Bermuda putting + Ball-striking", scoring: "Hard", dataKey: "arnoldpalmer",
        topStats: ["SG:PUTT Bermuda", "SG:APP", "SG:OTT", "Bogey Avoidance"],
        masked: "Short game", amplified: "Bermuda putting, ball-striking, wind management",
        bets: 22, pl: 51.10, status: "settled"
    },
    {
        name: "TPC San Antonio (Oaks)", event: "Valero Texas Open", surface: "Bermuda/Poa", length: "7,438 yds",
        archetype: "Second-shot + Wind-exposed", scoring: "Hard (wind-dependent)", dataKey: "valero",
        topStats: ["SG:APP", "SG:ARG", "SG:OTT", "Wind Management", "Par 5 Scoring"],
        masked: "Fairway accuracy (moderate rough)", amplified: "Approach to elevated greens, short game, wind shaping",
        bets: 5, pl: 0, status: "upcoming"
    },
    {
        name: "PGA National (Champion)", event: "Cognizant Classic", surface: "Bermuda", length: "7,125 yds",
        archetype: "Grinder / Penalty course", scoring: "Hard", dataKey: "cognizant",
        topStats: ["SG:PUTT Bermuda", "Bogey Avoidance", "SG:APP", "Scrambling", "SG:OTT Accuracy"],
        masked: "Driving distance (short course)", amplified: "Bermuda putting, water management, bogey avoidance",
        bets: 17, pl: 341.75, status: "settled"
    },
    {
        name: "Grand Reserve GC", event: "Puerto Rico Open", surface: "Bermuda/Paspalum", length: "7,506 yds",
        archetype: "Birdie-fest + Wind-exposed", scoring: "Standard", dataKey: "puertorico",
        topStats: ["SG:OTT (Wind)", "SG:APP", "Wind Management", "Birdie Making", "SG:PUTT Paspalum"],
        masked: "Driving accuracy (wide fairways)", amplified: "Wind shaping, ball flight control, distance in wind",
        bets: 9, pl: 195, status: "settled"
    },
];
