// Auto-generated by fetch_news.py -- 2026-07-12 11:56
const NEWS_FEED = [
  {
    "title": "Haeran Ryu finishes off historic week with playoff victory in Evian",
    "link": "https://sports.yahoo.com/articles/haeran-ryu-finishes-off-historic-163650579.html",
    "date": "Sun, 12 Jul 2026 16:36:50 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Rory McIlroy&#39;s hilarious soundbite from the Scottish Open is an incredibly relatable moment",
    "link": "https://sports.yahoo.com/articles/rory-mcilroys-hilarious-soundbite-scottish-163450165.html",
    "date": "Sun, 12 Jul 2026 16:34:50 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "How Scottie Scheffler performed at The Open Championship the last time he missed the cut at the Scottish Open",
    "link": "https://sports.yahoo.com/articles/scottie-scheffler-performed-open-championship-163000144.html",
    "date": "Sun, 12 Jul 2026 16:30:00 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "History, tears and a playoff: How Haeran Ryu survived chaotic Sunday to win Evian",
    "link": "https://golf.com/news/evian-championship-haeran-ryu-brooke-henderson-history-tears/",
    "date": "Sun, 12 Jul 2026 15:52:18 +0000",
    "source": "Golf.com"
  },
  {
    "title": "British Open 101: History, qualifications, course rota, most titles",
    "link": "https://sports.yahoo.com/articles/british-open-101-history-qualifications-150800668.html",
    "date": "Sun, 12 Jul 2026 15:08:00 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Haeran Ryu wins Amundi Evian Championship in stunning playoff finish",
    "link": "https://sports.yahoo.com/articles/haeran-ryu-wins-amundi-evian-145305947.html",
    "date": "Sun, 12 Jul 2026 14:53:05 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Haeran Ryu Goes Back-to-Back in Playoff Thriller at Evian",
    "link": "https://sports.yahoo.com/articles/haeran-ryu-goes-back-back-143101006.html",
    "date": "Sun, 12 Jul 2026 14:31:01 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Amundi Evian Championship 2026 prize money: Full payout from $9.1 million purse",
    "link": "https://sports.yahoo.com/articles/amundi-evian-championship-2026-prize-002544257.html",
    "date": "Sun, 12 Jul 2026 14:28:00 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Scottie Scheffler embracing short memory after rare stumble ahead of Open Championship",
    "link": "https://sports.yahoo.com/articles/scottie-scheffler-embracing-short-memory-125946021.html",
    "date": "Sun, 12 Jul 2026 12:59:46 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Sir Nick Faldo explains how to play a knockdown shot ahead of The Open Championship at Royal Birkdale",
    "link": "https://sports.yahoo.com/articles/sir-nick-faldo-explains-play-123000088.html",
    "date": "Sun, 12 Jul 2026 12:30:00 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "2026 Genesis Scottish Open purse: Payout breakdown, winner's share",
    "link": "https://golf.com/news/2026-scottish-open-purse/",
    "date": "Sun, 12 Jul 2026 12:08:27 +0000",
    "source": "Golf.com"
  },
  {
    "title": "2026 Genesis Scottish Open Sunday TV coverage: How to watch Round 4",
    "link": "https://golf.com/news/2026-genesis-scottish-open-sunday-tv-coverage-watch/",
    "date": "Sun, 12 Jul 2026 02:00:12 +0000",
    "source": "Golf.com"
  },
  {
    "title": "Marathon Sunday awaits at Scottish Open after brutal day of delays",
    "link": "https://golf.com/news/scottish-open-fog-delay-final-round/",
    "date": "Sat, 11 Jul 2026 19:57:36 +0000",
    "source": "Golf.com"
  },
  {
    "title": "Tour winner literally boiled his putter to get hot for ISCO title defense",
    "link": "https://golf.com/news/william-mouw-boiled-putter-isco/",
    "date": "Sat, 11 Jul 2026 16:03:55 +0000",
    "source": "Golf.com"
  },
  {
    "title": "Ryu wins Evian in playoff; 2nd straight major title",
    "link": "https://www.espn.com/golf/story/_/id/49343303/haeran-ryu-wins-evian-championship-2nd-straight-lpga-major",
    "date": "Sun, 12 Jul 2026 12:19:44 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "Glover hangs on to lead in ISCO Championship",
    "link": "https://www.espn.com/golf/story/_/id/49338381/lucas-glover-holds-lead-isco-championship-1-stroke",
    "date": "Sat, 11 Jul 2026 20:31:23 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "Johnson fires 63 for 4-shot lead at Champions stop",
    "link": "https://www.espn.com/golf/story/_/id/49338204/zach-johnson-shoots-63-takes-4-shot-lead-firestone-club",
    "date": "Sat, 11 Jul 2026 19:51:23 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "Fitzpatrick, Thorbjornsen lead foggy Scottish Open",
    "link": "https://www.espn.com/golf/story/_/id/49336735/fitzpatrick-thorbjornsen-lead-fog-delayed-scottish-open",
    "date": "Sat, 11 Jul 2026 17:05:29 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "Glover shoots 64 to lead by 2 shots in Kentucky",
    "link": "https://www.espn.com/golf/story/_/id/49329262/lucas-glover-takes-2-stroke-lead-weekend-kentucky",
    "date": "Fri, 10 Jul 2026 19:51:29 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "Biggest takeaways and remaining questions about changes coming to the PGA Tour",
    "link": "https://www.espn.com/golf/story/_/id/49164913/pga-tour-changes-faq-championship-series-challenger-series",
    "date": "Wed, 24 Jun 2026 11:53:18 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "How Wyndham Clark battled the crowd and the course...",
    "link": "https://www.espn.com/golf/story/_/id/49138277/wyndham-clark-hung-won-2026-us-open-shinnecock-hills",
    "date": "Tue, 23 Jun 2026 15:42:10 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "How to watch The Open in the UK: TV channel, schedule, tee times, prize money",
    "link": "https://www.espn.com/golf/story/_/id/48749193/how-watch-open-championship-2026-uk-tv-channel-schedule-tee-s-prize-money",
    "date": "Sun, 12 Jul 2026 09:06:14 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "What happened last time The Open was at Royal Birkdale?",
    "link": "https://www.espn.com/golf/story/_/id/48766886/what-happened-last-open-was-royal-birkdale",
    "date": "Sun, 12 Jul 2026 08:51:36 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "The Open Last-Chance Qualifier -- What is it? When is it? Who is competing in it?",
    "link": "https://www.espn.com/golf/story/_/id/48767821/the-2026-open-last-chance-qualifier-when-is-competing-it",
    "date": "Sun, 12 Jul 2026 08:51:29 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "Percy fires 66 for 1-shot lead at rainy Firestone",
    "link": "https://www.espn.com/golf/story/_/id/49328616/cameron-percy-fires-66-1-kaulig-companies-championship",
    "date": "Fri, 10 Jul 2026 18:47:01 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "Korda misses cut at Evian; Woad leads after 2",
    "link": "https://www.espn.com/golf/story/_/id/49326476/nelly-korda-misses-cut-evian-championship-lottie-woad-takes-second-round-lead",
    "date": "Fri, 10 Jul 2026 15:26:23 EST",
    "source": "ESPN Golf"
  }
];
