// Auto-generated by fetch_news.py -- 2026-04-05 20:14
const NEWS_FEED = [
  {
    "title": "2026 Masters Tournament is now set with 91 golfers in field",
    "link": "https://sports.yahoo.com/articles/2026-masters-tournament-now-set-003035100.html",
    "date": "Mon, 06 Apr 2026 00:30:35 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Just 4 golfers have won the Masters a week after winning on PGA Tour",
    "link": "https://sports.yahoo.com/articles/just-4-golfers-won-masters-000035816.html",
    "date": "Mon, 06 Apr 2026 00:00:35 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Scottie Scheffler arrives at Augusta National for the Masters with 9-day-old son, Remy",
    "link": "https://sports.yahoo.com/golf/article/scottie-scheffler-arrives-at-augusta-national-for-the-masters-with-9-day-old-son-remy-235510554.html",
    "date": "Sun, 05 Apr 2026 23:55:10 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Jim Furyk to join Golf Channel&#39;s Live From The Masters at Augusta",
    "link": "https://sports.yahoo.com/articles/jim-furyk-join-golf-channels-233023866.html",
    "date": "Sun, 05 Apr 2026 23:30:23 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "MacIntyre misses out as Spaun wins Texas Open",
    "link": "https://sports.yahoo.com/articles/macintyre-wallace-contention-delayed-texas-165236139.html",
    "date": "Sun, 05 Apr 2026 23:29:38 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Life as U.S. Open champ was an adjustment for J.J. Spaun. He figured it out by winning the Texas Open again",
    "link": "https://sports.yahoo.com/articles/life-u-open-champ-adjustment-232245873.html",
    "date": "Sun, 05 Apr 2026 23:22:45 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Eagle-eyed Spaun snatches Texas Open victory",
    "link": "https://sports.yahoo.com/articles/eagle-eyed-spaun-snatches-texas-231646145.html",
    "date": "Sun, 05 Apr 2026 23:16:46 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Ludvig Aberg criticized after his conduct on the 17th hole on Sunday at the Valero Texas Open",
    "link": "https://sports.yahoo.com/articles/ludvig-aberg-criticized-conduct-17th-231549928.html",
    "date": "Sun, 05 Apr 2026 23:15:49 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "J.J. Spaun wins Valero Texas Open, finds form before Masters",
    "link": "https://sports.yahoo.com/articles/j-j-spaun-wins-valero-230459036.html",
    "date": "Sun, 05 Apr 2026 23:04:59 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Donald Trump \u2018doesn\u2019t fit\u2019 at Augusta, claims Butch Harmon ahead of The Masters",
    "link": "https://sports.yahoo.com/articles/donald-trump-doesn-t-fit-230100988.html",
    "date": "Sun, 05 Apr 2026 23:01:00 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Butch Harmon interview: Trump is not welcome at Augusta National",
    "link": "https://sports.yahoo.com/articles/butch-harmon-interview-trump-not-230100173.html",
    "date": "Sun, 05 Apr 2026 23:01:00 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "J.J. Spaun breaks slump, wins Valero Texas Open ahead of the Masters",
    "link": "https://golf.com/news/jj-spaun-breaks-slump-wins-valero/",
    "date": "Sun, 05 Apr 2026 22:50:48 +0000",
    "source": "Golf.com"
  },
  {
    "title": "J.J. Spaun rallies to win Texas Open for first title since US Open",
    "link": "https://sports.yahoo.com/articles/j-j-spaun-rallies-win-224651603.html",
    "date": "Sun, 05 Apr 2026 22:46:51 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "2026 Valero Texas Open money: Here\u2019s how much every player made",
    "link": "https://golf.com/news/valero-texas-open-2026-how-much-made/",
    "date": "Sun, 05 Apr 2026 22:28:23 +0000",
    "source": "Golf.com"
  },
  {
    "title": "Tour Confidential: Biggest Masters storylines, Scottie and Rory's chances",
    "link": "https://golf.com/news/biggest-masters-storylines-scottie-rory-chances-tour-confidential/",
    "date": "Sun, 05 Apr 2026 22:07:40 +0000",
    "source": "Golf.com"
  },
  {
    "title": "2026 Masters odds, picks, field, date: Surprising PGA predictions from golf model that's nailed 16 majors",
    "link": "https://www.cbssports.com/golf/news/2026-masters-odds-picks-golf-predictions-advice-field-start-date/",
    "date": "Sun, 05 Apr 2026 22:06:58 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "Hideki Matsuyama expanded his putter collection this week",
    "link": "https://www.golfwrx.com/775819/hideki-matsuyama-expanded-his-putter-collection-this-week/",
    "date": "Sun, 05 Apr 2026 20:02:04 +0000",
    "source": "GolfWRX"
  },
  {
    "title": "Destination Aiken: Next door to Augusta, a UK-style club is taking shape",
    "link": "https://golf.com/travel/new-holland-jeff-warne-golf-uk-private-public-aiken/",
    "date": "Sun, 05 Apr 2026 18:30:14 +0000",
    "source": "Golf.com"
  },
  {
    "title": "Clayton Keller won an Olympic gold medal. But he also has a golf 'claim to fame'",
    "link": "https://golf.com/news/clayton-keller-olympics-golf-subpar/",
    "date": "Sun, 05 Apr 2026 18:13:39 +0000",
    "source": "Golf.com"
  },
  {
    "title": "Forgotten moments from Rory McIlroy's Masters Sunday: A losing gesture, Bryson's frustration",
    "link": "https://golf.com/news/rory-mcilroy-masters-sunday-forgotten-moments-gesture-bryson/",
    "date": "Sun, 05 Apr 2026 17:13:35 +0000",
    "source": "Golf.com"
  },
  {
    "title": "2026 Valero Texas Open purse: Payout breakdown, winner's share",
    "link": "https://golf.com/news/2026-valero-texas-open-purse-payout-breakdown-winners-share/",
    "date": "Sun, 05 Apr 2026 16:13:51 +0000",
    "source": "Golf.com"
  },
  {
    "title": "Masters 2026 odds, picks, predictions, props: Expert fading Tyrrell Hatton in best bets at Augusta National",
    "link": "https://www.cbssports.com/golf/news/masters-2026-odds-best-bets-picks-predictions-expert-golf-props/",
    "date": "Sun, 05 Apr 2026 15:31:11 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "2026 Masters odds, picks: Scottie Scheffler, Rory McIlroy predictions by model that nailed 4 straight winners",
    "link": "https://www.cbssports.com/golf/news/2026-masters-odds-field-pga-picks-scottie-scheffler-rory-mcilroy-jon-rahm-predictions/",
    "date": "Sun, 05 Apr 2026 15:26:17 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "What's new at Augusta National for 2026 Masters? Course changes, player services, merchandise, food menu",
    "link": "https://www.cbssports.com/golf/news/whats-new-augusta-national-2026-masters-course-merchandise-food/",
    "date": "Sat, 04 Apr 2026 22:33:24 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "Masters 2026 odds, picks, predictions, favorites: Expert fading Rory McIlroy in best bets at Augusta National",
    "link": "https://www.cbssports.com/golf/news/masters-2026-odds-picks-predictions-favorites-expert-fading-rory-mcilroy-in-best-bets-at-augusta-national/",
    "date": "Sat, 04 Apr 2026 17:07:28 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "2026 Masters expert picks, best bets, longshots: Golf insider fading Bryson DeChambeau at Augusta National",
    "link": "https://www.cbssports.com/golf/news/2026-masters-expert-picks-best-bets-longshots/",
    "date": "Sat, 04 Apr 2026 17:07:06 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "2026 Masters odds: Scottie Scheffler and Bryson DeChambeau betting favorites",
    "link": "https://www.golfwrx.com/775803/2026-masters-odds-scottie-scheffler-and-bryson-dechambeau-betting-favorites/",
    "date": "Sat, 04 Apr 2026 11:44:57 +0000",
    "source": "GolfWRX"
  },
  {
    "title": "Inside Johnny Keefer\u2019s surprising putter switch",
    "link": "https://www.golfwrx.com/775817/inside-johnny-keefers-surprising-putter-switch/",
    "date": "Sat, 04 Apr 2026 11:30:04 +0000",
    "source": "GolfWRX"
  },
  {
    "title": "Robert MacIntyre builds 4-shot lead at the 2026 Texas Open heading into the weekend",
    "link": "https://www.cbssports.com/golf/news/texas-open-2026-leaderboard-robert-macintyre-round-2/",
    "date": "Sat, 04 Apr 2026 01:35:23 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "2026 Masters picks: 10 players who could break through to win first major at Augusta National",
    "link": "https://www.cbssports.com/golf/news/masters-2026-picks-breakthrough-players-longshots-first-major/",
    "date": "Fri, 03 Apr 2026 18:58:57 +0000",
    "source": "CBS Golf"
  }
];
