// Auto-generated by fetch_news.py -- 2026-04-01 19:37
const NEWS_FEED = [
  {
    "title": "Masters Picks and Predictions 2026: Scheffler\u00a0Eyes Third Green Jacket",
    "link": "https://sports.yahoo.com/articles/2026-masters-guide-odds-picks-132900654.html",
    "date": "Wed, 01 Apr 2026 23:51:00 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Tiger Woods will not captain 2027 Ryder Cup team, PGA of America announces",
    "link": "https://sports.yahoo.com/articles/tiger-woods-not-captain-2027-231738309.html",
    "date": "Wed, 01 Apr 2026 23:17:38 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Woods declines US Ryder Cup captain role in 2027",
    "link": "https://sports.yahoo.com/articles/woods-declines-us-ryder-cup-225717855.html",
    "date": "Wed, 01 Apr 2026 22:57:17 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "2026 Valero Texas Open odds, picks: Surprising predictions from golf model that's nailed 16 majors",
    "link": "https://www.cbssports.com/golf/news/2026-valero-texas-open-odds-favorites-top-contenders-picks-predictions-field-best-bets/",
    "date": "Wed, 01 Apr 2026 22:45:33 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "Embattled Woods won&#39;t captain 2027 Ryder Cup team: PGA of America",
    "link": "https://sports.yahoo.com/articles/embattled-woods-wont-captain-2027-222936097.html",
    "date": "Wed, 01 Apr 2026 22:29:36 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "In wake of wreck, Tiger Woods tells PGA of America he won&#39;t captain 2027 U.S. Ryder Cup team",
    "link": "https://sports.yahoo.com/golf/breaking-news/article/in-wake-of-wreck-tiger-woods-tells-pga-of-america-he-wont-captain-2027-us-ryder-cup-team-222430699.html",
    "date": "Wed, 01 Apr 2026 22:24:30 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Tiger Woods Steps Away From 2027 Ryder Cup Captaincy",
    "link": "https://sports.yahoo.com/articles/tiger-woods-steps-away-2027-220708973.html",
    "date": "Wed, 01 Apr 2026 22:07:08 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "Tiger Woods won&#39;t be the U.S. Ryder Cup captain in 2027",
    "link": "https://sports.yahoo.com/articles/tiger-woods-wont-u-ryder-215550191.html",
    "date": "Wed, 01 Apr 2026 21:55:50 +0000",
    "source": "Yahoo Golf"
  },
  {
    "title": "This limited-edition Mitusbishi shaft pays homage to Augusta National",
    "link": "https://golf.com/gear/shafts/limited-edition-mitusbishi-shaft-pays-homage-augusta-national/",
    "date": "Wed, 01 Apr 2026 21:07:23 +0000",
    "source": "Golf.com"
  },
  {
    "title": "2026 Texas Open TV schedule, coverage: Where to watch, tee times for final PGA Tour event before the Masters",
    "link": "https://www.cbssports.com/golf/news/texas-open-2026-where-to-watch-tv-schedule-streaming-coverage/",
    "date": "Wed, 01 Apr 2026 20:53:31 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "2026 Masters odds, picks, field, date: Surprising PGA predictions by golf model that's called 16 majors",
    "link": "https://www.cbssports.com/golf/news/2026-masters-golf-tournament-odds-picks-field-start-date-predictions/",
    "date": "Wed, 01 Apr 2026 20:51:45 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "Why the Masters \u2014 and Augusta National \u2014 beguiles us so endlessly",
    "link": "https://golf.com/news/features/why-masters-augusta-national-beguiles-endlessly/",
    "date": "Wed, 01 Apr 2026 18:22:28 +0000",
    "source": "Golf.com"
  },
  {
    "title": "Tiger Woods\u2019s fiercest opponent is Tiger Woods himself",
    "link": "https://golf.com/news/tiger-woods-fiercest-opponent-himself/",
    "date": "Wed, 01 Apr 2026 16:59:46 +0000",
    "source": "Golf.com"
  },
  {
    "title": "2026 Valero Texas Open longshot picks, odds, PGA props: This golf parlay could return over $60,000",
    "link": "https://www.cbssports.com/golf/news/2026-valero-texas-open-longshot-picks-predictions-pga-props-golf-parlay/",
    "date": "Wed, 01 Apr 2026 14:27:22 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "2026 Valero Texas Open odds, prop picks, predictions, free best bets: Golf model backing Jordan Spieth top 5",
    "link": "https://www.cbssports.com/golf/news/2026-valero-texas-open-odds-prop-picks-predictions-free-best-bets-jordan-spieth/",
    "date": "Wed, 01 Apr 2026 13:51:34 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "2026 Masters odds, picks: Scottie Scheffler, Rory McIlroy predictions by model that nailed 4 straight winners",
    "link": "https://www.cbssports.com/golf/news/2026-masters-odds-picks-scottie-scheffler-rory-mcilroy-jon-rahm-predictions-finish-projections/",
    "date": "Wed, 01 Apr 2026 13:51:01 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "PGA Valero Texas Open 2026 odds, picks, predictions, props: Expert fading Ludvig Aberg in best bets",
    "link": "https://www.cbssports.com/golf/news/pga-valero-texas-open-2026-odds-picks-predictions-props-expert-best-bets/",
    "date": "Wed, 01 Apr 2026 13:10:38 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "Tiger Woods takes indefinite leave; Basketball Hall of Fame reveals five inductees; World Cup field set",
    "link": "https://www.cbssports.com/golf/news/tiger-woods-golf-masters-basketball-hall-of-fame-fifa-world-cup-soccer/",
    "date": "Wed, 01 Apr 2026 12:56:55 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "Masters 2026 odds, picks, predictions, props: Expert fading Tyrrell Hatton in best bets at Augusta National",
    "link": "https://www.cbssports.com/golf/news/masters-2026-odds-best-picks-predictions-props-best-bets-augusta-national/",
    "date": "Wed, 01 Apr 2026 12:53:25 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "\u201cSomething different to look at\u201d \u2013 Inside Tommy Fleetwood\u2019s putter testing, adjustments",
    "link": "https://www.golfwrx.com/775626/something-different-to-look-at-inside-tommy-fleetwoods-putter-testing/",
    "date": "Wed, 01 Apr 2026 12:44:37 +0000",
    "source": "GolfWRX"
  },
  {
    "title": "2026 Valero Texas Open Thursday tee times: Round 1 groupings",
    "link": "https://golf.com/news/2026-valero-texas-open-thursday-tee-times-round-1-groupings/",
    "date": "Wed, 01 Apr 2026 10:17:05 +0000",
    "source": "Golf.com"
  },
  {
    "title": "2026 Texas Open preview: Expert predictions, picks as Tommy Fleetwood leads a strong field into San Antonio",
    "link": "https://www.cbssports.com/golf/news/texas-open-2026-predictions-odds-picks-field-rankings-pga-tour-preview/",
    "date": "Tue, 31 Mar 2026 20:44:06 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "A few thoughts on counterbalancing",
    "link": "https://www.golfwrx.com/775558/a-few-thoughts-on-counterbalancing/",
    "date": "Tue, 31 Mar 2026 18:13:44 +0000",
    "source": "GolfWRX"
  },
  {
    "title": "Collin Morikawa withdraws from Texas Open, misses final tune-up event for the 2026 Masters",
    "link": "https://www.cbssports.com/golf/news/collin-morikawa-withdraws-texas-open-2026-masters/",
    "date": "Tue, 31 Mar 2026 16:24:11 +0000",
    "source": "CBS Golf"
  },
  {
    "title": "Hideki Matsuyama testing 2 putters from different brands at Valero Texas Open",
    "link": "https://www.golfwrx.com/775479/hideki-matsuyama-testing-2-putters-from-different-brands-at-valero-texas-open/",
    "date": "Tue, 31 Mar 2026 09:09:56 +0000",
    "source": "GolfWRX"
  },
  {
    "title": "Tiger stepping away from golf to seek treatment",
    "link": "https://www.espn.com/golf/story/_/id/48361336/tiger-woods-stepping-away-golf-seek-treatment",
    "date": "Wed, 1 Apr 2026 07:51:58 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "Tiger won't captain '27 Ryder Cup team, PGA says",
    "link": "https://www.espn.com/golf/story/_/id/48372144/tiger-woods-declines-captaincy-us-ryder-cup-team-27",
    "date": "Wed, 1 Apr 2026 17:46:02 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "Woods can leave U.S. for treatment, judge rules",
    "link": "https://www.espn.com/golf/story/_/id/48371629/judge-grants-tiger-woods-permission-leave-us-treatment",
    "date": "Wed, 1 Apr 2026 17:40:12 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "Morikawa (back) withdraws from Texas Open",
    "link": "https://www.espn.com/golf/story/_/id/48357984/collin-morikawa-withdraws-texas-open-due-back-injury",
    "date": "Tue, 31 Mar 2026 12:42:25 EST",
    "source": "ESPN Golf"
  },
  {
    "title": "How to watch 2026 PGA Texas Valero Open on ESPN",
    "link": "https://www.espn.com/golf/story/_/id/48359854/how-watch-2026-pga-texas-valero-open-espn",
    "date": "Wed, 1 Apr 2026 09:22:03 EST",
    "source": "ESPN Golf"
  }
];
