// Tournament-specific data for the data dashboard
// This is where DG, Betsperts, and narrative source data lives

const TOURNAMENT_DATA = {
    masters: {
        name: "The Masters 2026",
        course: "Augusta National",
        meta: "7,555 yds | Par 72 | Bentgrass (13.5 stimp) | Scoring: Difficult",
        archetype: "Second-shot + Short game",
        narrative: {
            description: "MacKenzie/Jones masterpiece (1932). The most predictive course on Tour \— course history matters more here than anywhere else. Wide fairways with no real rough, but severely contoured elevated greens with SubAir system create the most demanding approach and short-game test in golf. 73% of scoring from par 5s since 2010. Amen Corner (11-13) decides tournaments. Hurricane Helene (2025) removed many trees, opening sightlines and potentially changing wind patterns.",
            tags: ["Bentgrass Fast", "Par 5 Scoring", "Course History King", "Short-Grass ARG", "Elevated Greens", "No Rough Penalty", "Amen Corner", "Major"],
            keyHoles: [
                { num: 10, par: 4, yds: 495, note: "Hardest hole. 100ft elevation drop into Amen Corner." },
                { num: 11, par: 4, yds: 520, note: "Amen Corner start. Pond left. 'Where tournaments are decided.'" },
                { num: 12, par: 3, yds: 155, note: "Most famous par 3 in golf. Wind eddy effect. Nightmare." },
                { num: 13, par: 5, yds: 545, note: "Easiest hole. Rae's Creek. Eagle opportunity = scoring key." },
                { num: 15, par: 5, yds: 550, note: "Risk-reward climax. Pond guards green. Sunday defining." },
                { num: 18, par: 4, yds: 465, note: "Uphill finisher. Oak trees. 'Patrons' everywhere." },
            ],
            winnerDNA: "Top-50 driving distance + SG:APP from 150+ + short-grass ARG + Par 5 scoring. 15 of 16 winners top-50 DrDist. SG:PUTT rank for year is irrelevant (avg winner: 98th). But must putt well THAT WEEK on bent. Every winner since 2011 from OWGR top-25. Course history 0.20 weight.",
            recentWinners: [
                { yr: 2025, name: "Rory McIlroy", score: "-11", odds: "14/1", note: "Career Grand Slam. Playoff over Rose." },
                { yr: 2024, name: "Scottie Scheffler", score: "-12", odds: "4.5/1", note: "2nd win in 3 years. SG:APP led field." },
                { yr: 2023, name: "Jon Rahm", score: "-12", odds: "9/1", note: "SG:PUTT +6.6 for the week." },
                { yr: 2022, name: "Scottie Scheffler", score: "-10", odds: "5.5/1", note: "1st major. Wire-to-wire R2-R4." },
                { yr: 2021, name: "Hideki Matsuyama", score: "-10", odds: "40/1", note: "APP dominant. Seasonal PUTT 175th." },
            ],
        },
        fingerprint: [
            { stat: "SG:APP (150+)", weight: 0.25, note: "72% from 150+. 9/10 winners top-7 GIR. Firm elevated greens." },
            { stat: "Course History", weight: 0.20, note: "Most predictive course on Tour. 22 players with 100% T10 rates." },
            { stat: "Carry Distance", weight: 0.15, note: "7th longest. 15/16 winners top-50 DrDist. Par 5s reachable." },
            { stat: "SG:ARG (Short Grass)", weight: 0.15, note: "Toughest ARG on Tour. Tight lies, grain against, severe slopes." },
            { stat: "Par 5 BoB%", weight: 0.10, note: "Last 4 winners: 88% of scoring from Par 5s." },
            { stat: "3-Putt Avoidance", weight: 0.10, note: "4.24% rate = highest on Tour. Lag putting critical." },
        ],
        masked: ["Driving accuracy (widest fairways on Tour, 51 yds avg)", "Seasonal putting rank (avg winner: 98th SG:PUTT for year)"],
        amplified: ["Approach precision 150+", "Short-grass scrambling", "Par 5 eagle/birdie scoring", "Course knowledge accumulated over years"],
        densityCheck: { profiled: 10, total: 30, pct: 33, status: "HEALTHY" },
        radarAxes: ["APP 150+", "Distance", "ARG (Short Grass)", "Par 5 BoB%", "3-Putt Avd", "Course History"],
        winnerProfile: [90, 80, 75, 85, 70, 90],
        radarPlayers: {
            "Rory McIlroy": [72, 95, 55, 82, 65, 95],
            "Scottie Scheffler": [92, 78, 82, 88, 75, 90],
            "Xander Schauffele": [85, 72, 58, 78, 68, 85],
            "Jon Rahm": [88, 82, 48, 85, 72, 92],
            "Collin Morikawa": [95, 68, 45, 72, 65, 78],
            "Ludvig Aberg": [78, 80, 42, 75, 62, 55],
            "Jordan Spieth": [62, 48, 65, 70, 75, 98],
            "Cameron Smith": [35, 35, 85, 88, 82, 92],
            "Hideki Matsuyama": [82, 65, 88, 85, 72, 88],
            "Adam Scott": [82, 70, 50, 72, 62, 88],
            "Jason Day": [40, 42, 82, 72, 78, 92],
            "Patrick Cantlay": [68, 62, 60, 75, 68, 85],
            "Tommy Fleetwood": [75, 60, 72, 68, 62, 78],
            "Russell Henley": [72, 55, 82, 68, 82, 60],
            "Akshay Bhatia": [78, 58, 42, 65, 55, 25],
            "Bryson DeChambeau": [48, 95, 42, 78, 52, 55],
            "Brooks Koepka": [78, 65, 52, 72, 62, 80],
            "Shane Lowry": [82, 42, 48, 62, 65, 72],
            "Will Zalatoris": [85, 62, 50, 68, 55, 82],
            "Corey Conners": [75, 55, 38, 65, 72, 82],
            "Tony Finau": [55, 62, 72, 72, 58, 78],
            "Si Woo Kim": [72, 52, 58, 62, 55, 40],
            "Sungjae Im": [38, 48, 78, 72, 65, 72],
            "Robert MacIntyre": [52, 62, 42, 65, 55, 55],
        },
        oddsBoard: [
            { rank:1, name:"Scottie Scheffler", fair:"+450", best:"+450", b365:"+450", form:"warm", edge:"0.0%", verdict:"Fair price. No value." },
            { rank:2, name:"Rory McIlroy", fair:"+850", best:"+1000", b365:"+1000", form:"warm", edge:"+1.5%", verdict:"Slight value. Defending champ." },
            { rank:3, name:"Collin Morikawa", fair:"+1800", best:"+2500", b365:"+2500", form:"warm", edge:"+3.2%", verdict:"VALUE. Comp #3, priced like #8." },
            { rank:4, name:"Xander Schauffele", fair:"+1200", best:"+1600", b365:"+1600", form:"warm", edge:"+2.1%", verdict:"Moderate value. Injury recovery." },
            { rank:5, name:"Jon Rahm", fair:"+1000", best:"+1200", b365:"+1200", form:"warm", edge:"+1.6%", verdict:"LIV discount. History supports." },
            { rank:6, name:"Ludvig Aberg", fair:"+1400", best:"+1200", b365:"+1200", form:"warm", edge:"-1.3%", verdict:"Overpriced. Market loves debut T2." },
            { rank:7, name:"Tommy Fleetwood", fair:"+1600", best:"+2200", b365:"+2200", form:"warm", edge:"+3.5%", verdict:"VALUE. 5yr-comp #7, 3 Augusta T10s." },
            { rank:8, name:"Cameron Young", fair:"+2000", best:"+2500", b365:"+2500", form:"TAILWIND", edge:"+2.8%", verdict:"Value. Hottest form in golf." },
            { rank:9, name:"Jordan Spieth", fair:"+2500", best:"+4500", b365:"+4500", form:"cool", edge:"+5.8%", verdict:"STRONG VALUE. 6-for-6 T10." },
            { rank:10, name:"Hideki Matsuyama", fair:"+2200", best:"+3300", b365:"+3300", form:"cool", edge:"+3.8%", verdict:"Value. Past champ, 4 T10s." },
            { rank:11, name:"Russell Henley", fair:"+3500", best:"+5500", b365:"+5500", form:"warm", edge:"+4.2%", verdict:"VALUE. Fits every fingerprint." },
            { rank:12, name:"Cameron Smith", fair:"+3000", best:"+8000", b365:"+8000", form:"neutral", edge:"+8.5%", verdict:"BEST VALUE. 4-for-4 T10. LIV." },
            { rank:13, name:"Patrick Cantlay", fair:"+4000", best:"+6600", b365:"+6600", form:"cool", edge:"+4.8%", verdict:"VALUE. 5yr-comp #6, 4 T10s." },
            { rank:14, name:"Akshay Bhatia", fair:"+5000", best:"+5500", b365:"+5500", form:"TAILWIND", edge:"+0.8%", verdict:"Fair. Form surge, no history." },
            { rank:15, name:"Adam Scott", fair:"+5000", best:"+8000", b365:"+8000", form:"warm", edge:"+5.2%", verdict:"VALUE. 3-for-3 T10. Past champ." },
            { rank:16, name:"Jason Day", fair:"+5500", best:"+7000", b365:"+7000", form:"cool", edge:"+2.8%", verdict:"Value. 4-for-4 T10. ARG elite." },
            { rank:17, name:"Bryson DeChambeau", fair:"+2500", best:"+1100", b365:"+1100", form:"neutral", edge:"-8.2%", verdict:"OVERPRICED. Comp #33." },
            { rank:18, name:"Brooks Koepka", fair:"+4500", best:"+4000", b365:"+4000", form:"neutral", edge:"-1.0%", verdict:"Slightly overpriced." },
            { rank:19, name:"Justin Thomas", fair:"+8000", best:"+4500", b365:"+4500", form:"cool", edge:"-5.5%", verdict:"OVERPRICED. Comp #39." },
            { rank:20, name:"Justin Rose", fair:"+12000", best:"+2800", b365:"+2800", form:"neutral", edge:"-15.2%", verdict:"HEAVILY OVERPRICED. Comp #46." },
        ],
        composite: [],
        rhModels: [],
        formSignals: [],
        weaknessMasked: [],
        narratives: [],
        courseHistory: [],
    },
    cognizant: {
        name: "Cognizant Classic 2026",
        course: "PGA National (Champion)",
        meta: "7,125 yds | Par 70 | Bermuda greens | Scoring: Hard",
        archetype: "Grinder / Penalty course",
        narrative: {
            description: "The Bear Trap (15-16-17) is the signature stretch \— three of the toughest closing holes on Tour. Water on 6 of 18 holes. Bermuda greens running 12+ stimp. Narrow fairways demand accuracy. Wind off the Intracoastal creates unpredictable conditions. This is a survival course where bogey avoidance matters more than birdie-making.",
            tags: ["Bermuda Putting", "Water Hazards", "Bear Trap", "Bogey Avoidance", "Wind Exposed", "Narrow Fairways"],
            keyHoles: [
                { num: 15, par: 3, yds: 179, note: "Bear Trap start. Water everywhere. Historically hardest par 3." },
                { num: 16, par: 4, yds: 448, note: "Bear Trap middle. Water left. Approach over hazard." },
                { num: 17, par: 3, yds: 199, note: "Bear Trap finish. Island green. Tournaments decided here." },
                { num: 6, par: 4, yds: 397, note: "Water carry approach. Demands precision." },
            ],
            winnerDNA: "Bermuda putter + bogey avoidance + water management. Scrambling from tight lies around Bermuda greens. Not a bomber's course \— accuracy and nerve win here.",
            recentWinners: [
                { yr: 2026, name: "Nico Echavarria", score: "-17", odds: "50/1", note: "Our winner! E/W 1/4 5pl $10 returned $322.50." },
                { yr: 2025, name: "Justin Thomas", score: "-12", odds: "18/1", note: "JT's Bermuda putting carried." },
            ],
        },
        fingerprint: [
            { stat: "SG:PUTT (Bermuda)", weight: 0.24, note: "Bermuda greens at 12+ stimp. Grain reading is essential." },
            { stat: "Bogey Avoidance", weight: 0.22, note: "Bear Trap + water on 6 holes. Survival = contention." },
            { stat: "SG:APP", weight: 0.20, note: "Narrow approaches over water. Miss = penalty." },
            { stat: "Scrambling", weight: 0.15, note: "Bermuda tight lies around greens. Must get up and down." },
            { stat: "SG:OTT (Accuracy)", weight: 0.12, note: "Narrow fairways. Accuracy > distance here." },
        ],
        masked: ["Driving distance (short course, accuracy matters more)"],
        amplified: ["Bermuda putting", "Water management", "Bogey avoidance", "Nerve under pressure"],
        densityCheck: { profiled: 5, total: 30, pct: 17, status: "HEALTHY" },
        radarAxes: ["PUTT (Bermuda)", "Bogey Avd", "APP", "Scrambling", "OTT Accuracy"],
        winnerProfile: [85, 82, 75, 78, 70],
        radarPlayers: {
            "Nico Echavarria": [72, 68, 55, 62, 58],
            "Keith Mitchell": [38, 65, 75, 48, 72],
            "Shane Lowry": [58, 72, 82, 68, 65],
        },
        result2026: { winner:"Nico Echavarria", score:"-17", odds:"50/1", why:"Elite Bermuda putter who survived the Bear Trap. SG:PUTT +4.2 for the week. Our E/W 1/4 5pl $10 returned $322.50.", record:"3W-14L | +$341.75" },
        composite: [], rhModels: [], formSignals: [], weaknessMasked: [], narratives: [], courseHistory: [],
    },
    arnoldpalmer: {
        name: "Arnold Palmer Invitational 2026",
        course: "Bay Hill Club & Lodge",
        meta: "7,466 yds | Par 72 | Bermuda greens | Scoring: Hard",
        archetype: "Bermuda putting + Ball-striking",
        narrative: {
            description: "Bay Hill is the ultimate second-shot course with Bermuda greens. The closing stretch (16-17-18) with water everywhere demands nerve and precision. Wind off the lakes creates scoring variance. Signature Event since 2024 means elite 72-player field. Firm Bermuda greens at 12+ stimp reward distance control and trajectory management on approach.",
            tags: ["Bermuda Putting", "Second-Shot", "Signature Event", "Water Closing Stretch", "Firm Greens", "Wind Variable"],
            keyHoles: [
                { num: 6, par: 5, yds: 558, note: "Risk-reward par 5. Water guards green. Scoring hole." },
                { num: 16, par: 5, yds: 555, note: "Water right of green. Eagle opportunity or disaster." },
                { num: 17, par: 3, yds: 223, note: "Long par 3 over water. Most feared hole at Bay Hill." },
                { num: 18, par: 4, yds: 458, note: "Iconic finisher. Water right. Where championships are won." },
            ],
            winnerDNA: "SG:APP elite + Bermuda putting + distance for par 5 scoring. Approach from 175+ with trajectory control into firm greens. Bermuda green reading separates. Wind management on closing holes.",
            recentWinners: [
                { yr: 2026, name: "Akshay Bhatia", score: "-12", odds: "25/1", note: "Won playoff over Berger. Dislocated shoulder celebrating." },
                { yr: 2025, name: "Rory McIlroy", score: "-8", odds: "6/1", note: "3rd Bay Hill win. Windy conditions." },
                { yr: 2024, name: "Scottie Scheffler", score: "-15", odds: "5/1", note: "Dominant wire-to-wire." },
            ],
        },
        fingerprint: [
            { stat: "SG:APP", weight: 0.28, note: "Ultimate approach course. Firm Bermuda demands trajectory control." },
            { stat: "SG:PUTT (Bermuda)", weight: 0.24, note: "Bermuda grain reading at 12+ stimp." },
            { stat: "SG:OTT", weight: 0.16, note: "7,466 yds. Distance helps reach par 5s in two." },
            { stat: "Bogey Avoidance", weight: 0.12, note: "Water on closing stretch. Blow-ups end tournaments." },
            { stat: "SG:ARG", weight: 0.12, note: "Tight Bermuda lies around greens." },
        ],
        masked: ["Short game to some extent (approach precision reduces scrambling need)"],
        amplified: ["Bermuda putting grain reading", "Approach trajectory control", "Water management", "Wind adaptation"],
        densityCheck: { profiled: 8, total: 30, pct: 27, status: "HEALTHY" },
        radarAxes: ["APP", "PUTT (Bermuda)", "OTT / Distance", "Bogey Avd", "ARG"],
        winnerProfile: [88, 82, 75, 72, 65],
        radarPlayers: {
            "Collin Morikawa": [95, 42, 78, 72, 45],
            "Akshay Bhatia": [78, 85, 58, 62, 48],
            "Kurt Kitayama": [92, 38, 80, 65, 42],
        },
        result2026: { winner:"Akshay Bhatia", score:"-12", odds:"25/1", why:"Won playoff over Berger. Elite approach week. Dislocated shoulder celebrating the winning putt. Our Morikawa T10 (+230) cashed, DFS lineup returned $144.", record:"4W-18L | +$46.10" },
        composite: [], rhModels: [], formSignals: [], weaknessMasked: [], narratives: [], courseHistory: [],
    },
    puertorico: {
        name: "Puerto Rico Open 2026",
        course: "Grand Reserve GC",
        meta: "7,506 yds | Par 72 | Bermuda/Paspalum greens | Scoring: Standard",
        archetype: "Birdie-fest + Wind-exposed",
        narrative: {
            description: "Opposite-field event running alongside the Arnold Palmer Invitational. Grand Reserve is a Tom Kite links-style design on the northeast coast of Puerto Rico. Consistent trade winds define the challenge. Wide fairways but firm paspalum greens. The field is weaker than full-field events but hungry players fighting for FedExCup points create value.",
            tags: ["Opposite Field", "Wind Exposed", "Paspalum", "Trade Winds", "Hungry Field", "Birdie Opportunities"],
            keyHoles: [
                { num: 18, par: 4, yds: 468, note: "Wind-exposed closer. Water left. Demands nerve." },
                { num: 4, par: 3, yds: 225, note: "Long par 3 into wind. Ocean views distract." },
            ],
            winnerDNA: "Wind management + ball-striking + making birdies when conditions allow. Opposite-field winners are typically hungry mid-tier players, not stars. SG:OTT in difficult conditions separates.",
            recentWinners: [
                { yr: 2026, name: "Ricky Castillo", score: "-17", odds: "22/1", note: "Our winner! E/W 1/4 5pl $20 returned $295." },
            ],
        },
        fingerprint: [
            { stat: "SG:OTT (Wind)", weight: 0.25, note: "Trade winds make driving the primary challenge." },
            { stat: "SG:APP", weight: 0.22, note: "Firm paspalum greens from distance in wind." },
            { stat: "Wind Management", weight: 0.18, note: "Consistent 15-20mph trade winds shape every shot." },
            { stat: "Birdie Making", weight: 0.15, note: "Must capitalize on scoring holes when wind drops." },
            { stat: "SG:PUTT (Paspalum)", weight: 0.12, note: "Grainy paspalum surface requires adjustment." },
        ],
        masked: ["Driving accuracy (wide fairways)"],
        amplified: ["Wind shaping", "Ball flight control", "Distance in wind"],
        densityCheck: { profiled: 3, total: 30, pct: 10, status: "HEALTHY" },
        radarAxes: ["OTT (Wind)", "APP", "Wind Mgmt", "Birdie Making", "PUTT (Paspalum)"],
        winnerProfile: [80, 75, 85, 78, 65],
        radarPlayers: {
            "Ricky Castillo": [72, 55, 78, 72, 62],
        },
        result2026: { winner:"Ricky Castillo", score:"-17", odds:"22/1", why:"Won as a grinder in trade winds. Our E/W 1/4 5pl $20 returned $295. Biggest single-bet profit of the season.", record:"1W-8L | +$195" },
        composite: [], rhModels: [], formSignals: [], weaknessMasked: [], narratives: [], courseHistory: [],
    },
    players: {
        name: "The Players Championship 2026",
        course: "TPC Sawgrass (Stadium)",
        meta: "7,245 yds | Par 72 | Bermuda/Poa greens | Scoring: Hard",
        archetype: "Second-shot + Penalty course",
        narrative: {
            description: "Pete Dye's masterpiece and the PGA Tour's flagship event. Island green at 17 is the most famous hole in golf. TPC Sawgrass is the hardest course to gain strokes on approach on Tour \— the small, firm, elevated greens surrounded by water and waste areas demand absolute precision. Course history is moderately predictive. The 5th major in everything but name.",
            tags: ["Signature Event", "Island Green", "Penalty Course", "Water Everywhere", "Small Greens", "Pete Dye", "5th Major"],
            keyHoles: [
                { num: 12, par: 4, yds: 358, note: "Short but brutal. Tiny green. Miss = water/bunker." },
                { num: 16, par: 5, yds: 532, note: "Risk-reward par 5. Water guards green. Eagle or double." },
                { num: 17, par: 3, yds: 137, note: "THE island green. Most famous par 3 in golf." },
                { num: 18, par: 4, yds: 462, note: "Water left entire hole. Sunday pressure cooker." },
            ],
            winnerDNA: "SG:APP on small targets + mental fortitude + bogey avoidance. Poa putting on greens that firm up through the week. Must handle the pressure of the island green and closing stretch. Course history matters (moderately predictive).",
            recentWinners: [
                { yr: 2026, name: "Cameron Young", score: "-14", odds: "35/1", note: "Breakthrough win. Ball-striking elite." },
                { yr: 2025, name: "Rory McIlroy", score: "-12", odds: "8/1", note: "Monday playoff. Dominated T2G." },
                { yr: 2024, name: "Scottie Scheffler", score: "-20", odds: "4/1", note: "Wire-to-wire. Historic margin." },
            ],
        },
        fingerprint: [
            { stat: "SG:APP", weight: 0.28, note: "Hardest approach course on Tour. 5,500 sq ft greens." },
            { stat: "SG:PUTT (Poa)", weight: 0.20, note: "Poa annua greens. Bumpy afternoon putts." },
            { stat: "Bogey Avoidance", weight: 0.18, note: "Water on 7 holes. Mental game is huge." },
            { stat: "SG:ARG", weight: 0.15, note: "Hardest scrambling course. Collection areas everywhere." },
            { stat: "Course History", weight: 0.10, note: "Moderately predictive. Repeat contenders exist." },
        ],
        masked: ["Driving distance (7,245 yds is not extreme; precision > power)"],
        amplified: ["Iron precision on tiny targets", "Mental fortitude", "Poa putting", "Scrambling from waste areas"],
        densityCheck: { profiled: 12, total: 30, pct: 40, status: "HEALTHY" },
        radarAxes: ["APP", "PUTT (Poa)", "Bogey Avd", "ARG", "Course History"],
        winnerProfile: [90, 72, 80, 75, 70],
        radarPlayers: {
            "Si Woo Kim": [85, 35, 68, 72, 75],
            "Collin Morikawa": [95, 40, 72, 42, 65],
            "Russell Henley": [78, 72, 75, 72, 60],
            "Cameron Young": [72, 68, 62, 55, 55],
        },
        result2026: { winner:"Cameron Young", score:"-14", odds:"35/1", why:"Breakthrough win on ball-striking. SG:APP led the field. We had him on radar but not on card. Straka T8 would have cashed on 8pl terms.", record:"0W-17L | -$110" },
        composite: [], rhModels: [], formSignals: [], weaknessMasked: [], narratives: [], courseHistory: [],
    },
    valspar: {
        name: "Valspar Championship 2026",
        course: "Innisbrook (Copperhead)",
        meta: "7,352 yds | Par 71 | Poa Trivialis | Scoring: Hard",
        archetype: "Second-shot + Poa putting",
        narrative: {
            description: "Larry Packard's Copperhead Course feels like Carolina hill country, not Florida. 12 doglegs (4 double doglegs) through tree-lined corridors. 5 par 3s averaging 212 yards and 4 par 5s averaging 583 yards. The Snake Pit (16-17-18) is one of the toughest closing stretches on Tour with 18%+ bogey rate on each hole. Less-than-driver course \— driver used only 54% of holes. The 2nd fewest birdies and fewest eagles per 72 holes on Tour.",
            tags: ["Poa Putting", "Less-Than-Driver", "Snake Pit", "Tree-Lined", "Doglegs", "Hard Scoring", "5 Par 3s"],
            keyHoles: [
                { num: 16, par: 4, yds: 475, note: "Snake Pit start. 23.2% bogey. Narrow + water." },
                { num: 17, par: 3, yds: 215, note: "Snake Pit. Tiny green. 15.4% bogey." },
                { num: 18, par: 4, yds: 445, note: "Uphill to clubhouse. 19% bogey. Tournament decider." },
                { num: 14, par: 5, yds: 581, note: "Reachable eagle opp but penal rough." },
            ],
            winnerDNA: "SG:APP is dominant \— last 6 winners averaged 6th in field. Less-than-driver accuracy with 3W/hybrid. Poa Triv putting (smooth, fast). Bogey avoidance through the Snake Pit. Not a bomber's course.",
            recentWinners: [
                { yr: 2025, name: "Viktor Hovland", score: "-11", odds: "18/1", note: "APP + Poa putting. Snake Pit par was enough." },
                { yr: 2024, name: "Peter Malnati", score: "-12", odds: "200/1", note: "Longshot grinder. Bogey avoidance king." },
                { yr: 2023, name: "Taylor Moore", score: "-10", odds: "150/1", note: "Another longshot. ARG + scrambling." },
                { yr: 2022, name: "Sam Burns", score: "-17", odds: "14/1", note: "Soft conditions. Putting carried." },
            ],
        },
        fingerprint: [
            { stat: "SG:APP", weight: 0.30, note: "53% approaches from 175+. Small greens (5,822 sq ft)." },
            { stat: "SG:OTT (Less-Than-Driver)", weight: 0.18, note: "Driver only 54%. 20-26 yd fairways. 3W/hybrid accuracy." },
            { stat: "Bogey Avoidance", weight: 0.14, note: "Snake Pit + 5 par 3s. 2nd fewest birdies on Tour." },
            { stat: "SG:PUTT (Poa Triv)", weight: 0.12, note: "Smooth fast Poa. Top 3 putters = top 3 in 2025." },
            { stat: "Par 3 Scoring (200+)", weight: 0.10, note: "5 par 3s, 4 over 200 yds. Unique feature." },
            { stat: "Scrambling (Rough)", weight: 0.08, note: "3.75in rough closer to greens since 2023." },
        ],
        masked: ["None significant (this course penalizes everything)"],
        amplified: ["Approach precision from 175+", "Positional driving (less-than-driver)", "Poa putting", "Mental toughness through Snake Pit"],
        densityCheck: { profiled: 6, total: 30, pct: 20, status: "HEALTHY" },
        radarAxes: ["APP", "OTT (Accuracy)", "Bogey Avd", "PUTT (Poa)", "Par 3 Scoring", "Scrambling"],
        winnerProfile: [88, 80, 78, 72, 75, 68],
        radarPlayers: {
            "Viktor Hovland": [82, 55, 72, 68, 70, 62],
            "Corey Conners": [78, 85, 70, 35, 65, 48],
            "Sahith Theegala": [72, 48, 65, 68, 62, 65],
        },
        result2026: { winner:"Hovland", score:"-11", odds:"18/1", why:"APP + Poa putting carried through the Snake Pit. Our 11 bets all lost. Valspar remains a tough venue for us.", record:"0W-11L | -$85" },
        composite: [], rhModels: [], formSignals: [], weaknessMasked: [], narratives: [], courseHistory: [],
    },
    houston: {
        name: "Houston Open 2026",
        course: "Memorial Park GC",
        meta: "7,475 yds | Par 70 | Poa Trivialis | Scoring: Hard",
        archetype: "Second-shot + Bomber",
        narrative: {
            description: "Tom Doak/Brooks Koepka redesign (2019) of a municipal course. Augusta-influenced green complexes with short-grass runoffs, false fronts, and elevated contoured greens. The 2nd longest course on Tour with only 21 bunkers and 1.25-inch ryegrass rough \— the lowest missed-fairway penalty anywhere. Defense comes entirely from the greens and the length. Poa Trivialis overseed since 2024; firm and fast at 12-13 stimp.",
            tags: ["Driver Heavy", "Short-Grass ARG", "Poa Putting", "Firm & Fast", "Low Rough Penalty", "Elevated Greens", "False Fronts"],
            keyHoles: [
                { num: 1, par: 4, yds: 489, note: "2nd hardest. Immediate long-approach test." },
                { num: 4, par: 4, yds: 505, note: "Longest par 4. 21%+ bogey rate." },
                { num: 14, par: 4, yds: 530, note: "Hardest hole. 30%+ bogey rate." },
                { num: 15, par: 3, yds: 155, note: "'Loudest hole in Texas.' Creek, false front." },
                { num: 16, par: 5, yds: 576, note: "Water 3 sides. Go/no-go decision." },
                { num: 18, par: 4, yds: 488, note: "Closing dogleg. Precise long approach to finish." },
            ],
            winnerDNA: "Distance + approach precision from 150+ + short-grass chipping + Poa putting. 5 of top 7 in 2025 were top ball speed. Course history emerging (Jaeger 2024, Lee 2025). FRL pattern: 2025 had 5 co-leaders at 65.",
            recentWinners: [
                { yr: 2025, name: "Min Woo Lee", score: "-20", odds: "8/1", note: "Soft conditions. Distance dominated." },
                { yr: 2024, name: "Stephan Jaeger", score: "-12", odds: "125/1", note: "Firm setup. ARG carried. OTT weakness masked." },
                { yr: 2022, name: "Tony Finau", score: "-16", odds: "12/1", note: "Course record 62 twice. ARG + distance." },
                { yr: 2021, name: "Jason Kokrak", score: "-10", odds: "40/1", note: "Wind week. Ball-striking course." },
            ],
        },
        fingerprint: [
            { stat: "SG:APP", weight: 0.30, note: "69% approaches from 150+. Must hit correct green quadrant." },
            { stat: "Driving Distance", weight: 0.18, note: "2nd longest course. 5 of top 7 in 2025 = top ball speed." },
            { stat: "SG:ARG (Short Grass)", weight: 0.15, note: "67% ARG from short grass = highest on Tour." },
            { stat: "SG:OTT (Driver)", weight: 0.12, note: "Driver on nearly every hole. Accuracy irrelevant." },
            { stat: "Bogey Avoidance", weight: 0.10, note: "5 par 4s over 490yds. 28.9% bogey+ rate." },
            { stat: "SG:PUTT (Poa)", weight: 0.10, note: "~50% of winner SG from greens. Poa overseed." },
        ],
        masked: ["Driving accuracy (1.25in rough = lowest miss-FW penalty on Tour)", "Sand saves (only 21 bunkers)"],
        amplified: ["Distance / ball speed", "Approach precision 150-200+", "Short-grass scrambling (67% tight lies)"],
        densityCheck: { profiled: 8, total: 30, pct: 27, status: "HEALTHY" },
        // Blind composite top 40
        composite: [
            { rank:1, name:"Chris Gotterup", comp:0.756, form:1.14, signal:"warm", app:0.395, ott:0.49, dd:16.2, arg:0.08, putt:0.12, t10:23.1, spikes:"M15#10 M16#3 M17#1 M18#10 M19#2", flag:"" },
            { rank:2, name:"Nicolai Hojgaard", comp:0.738, form:1.16, signal:"warm", app:0.488, ott:0.31, dd:14.1, arg:-0.01, putt:0.23, t10:22.5, spikes:"M15#3 M16#4 M17#3 M18#2 M19#1", flag:"ON CARD" },
            { rank:3, name:"Kurt Kitayama", comp:0.734, form:1.07, signal:"warm", app:0.691, ott:0.57, dd:10.2, arg:-0.01, putt:-0.09, t10:21.4, spikes:"M15#1 M16#1 M17#5 M18#7", flag:"ON CARD" },
            { rank:4, name:"Min Woo Lee", comp:0.730, form:1.16, signal:"warm", app:0.286, ott:0.63, dd:12.9, arg:0.33, putt:0.38, t10:32.2, spikes:"M17#4", flag:"HARD ROTATE" },
            { rank:5, name:"Jake Knapp", comp:0.677, form:1.10, signal:"warm", app:0.113, ott:0.44, dd:13.0, arg:0.05, putt:0.60, t10:21.4, spikes:"M15#6 M16#7 M17#2", flag:"DARK HORSE" },
            { rank:6, name:"Adam Scott", comp:0.669, form:1.05, signal:"warm", app:0.598, ott:0.30, dd:8.2, arg:0.05, putt:-0.03, t10:15.1, spikes:"M15#8 M16#5 M17#6 M18#1 M19#3", flag:"ON CARD" },
            { rank:7, name:"Keith Mitchell", comp:0.645, form:1.19, signal:"warm", app:0.448, ott:0.56, dd:9.5, arg:-0.03, putt:-0.12, t10:17.4, spikes:"M16#2 M18#9 M19#9", flag:"ON CARD" },
            { rank:8, name:"Pierceson Coody", comp:0.631, form:1.15, signal:"warm", app:0.293, ott:0.56, dd:13.8, arg:-0.18, putt:0.02, t10:14.9, spikes:"M16#6 M17#9", flag:"" },
            { rank:9, name:"Michael Thorbjornsen", comp:0.613, form:1.12, signal:"warm", app:0.310, ott:0.59, dd:10.5, arg:0.04, putt:0.03, t10:16.4, spikes:"M15#9", flag:"" },
            { rank:10, name:"Ryan Gerard", comp:0.607, form:0.96, signal:"neutral", app:0.798, ott:0.51, dd:1.6, arg:0.01, putt:-0.05, t10:20.8, spikes:"M16#8", flag:"HARD ROTATE" },
            { rank:11, name:"Sam Burns", comp:0.605, form:1.14, signal:"warm", app:0.194, ott:0.30, dd:8.4, arg:0.00, putt:0.60, t10:21.1, spikes:"", flag:"DARK HORSE" },
            { rank:12, name:"Rasmus Hojgaard", comp:0.587, form:1.12, signal:"warm", app:0.113, ott:0.16, dd:14.1, arg:-0.07, putt:0.43, t10:14.7, spikes:"M15#5 M19#7", flag:"DARK HORSE" },
            { rank:13, name:"Taylor Pendrith", comp:0.568, form:1.07, signal:"warm", app:0.289, ott:0.51, dd:11.0, arg:0.09, putt:-0.07, t10:15.2, spikes:"", flag:"" },
            { rank:14, name:"Wyndham Clark", comp:0.567, form:1.29, signal:"TAILWIND", app:0.341, ott:0.05, dd:8.3, arg:0.25, putt:-0.01, t10:16.1, spikes:"M18#3", flag:"ON CARD" },
            { rank:15, name:"Brooks Koepka", comp:0.560, form:1.01, signal:"neutral", app:0.480, ott:0.26, dd:6.2, arg:-0.01, putt:-0.14, t10:14.6, spikes:"M17#7 M19#5", flag:"FADE" },
            { rank:16, name:"Marco Penge", comp:0.552, form:1.18, signal:"warm", app:0.145, ott:0.90, dd:20.2, arg:-0.19, putt:-0.05, t10:18.9, spikes:"", flag:"FADE" },
            { rank:17, name:"Ryan Fox", comp:0.552, form:1.12, signal:"warm", app:0.176, ott:0.12, dd:9.1, arg:0.10, putt:0.14, t10:9.7, spikes:"M19#6", flag:"" },
            { rank:18, name:"Rickie Fowler", comp:0.540, form:0.88, signal:"cool", app:0.339, ott:0.46, dd:2.2, arg:0.00, putt:0.37, t10:20.3, spikes:"M16#9 M18#5", flag:"" },
            { rank:19, name:"Ben Griffin", comp:0.521, form:1.11, signal:"warm", app:0.346, ott:-0.03, dd:0.3, arg:0.27, putt:0.42, t10:19.5, spikes:"M19#8", flag:"DARK HORSE" },
            { rank:20, name:"Sahith Theegala", comp:0.518, form:1.06, signal:"warm", app:0.376, ott:0.07, dd:4.0, arg:0.16, putt:0.19, t10:16.5, spikes:"M17#8 M18#4", flag:"" },
            { rank:23, name:"Alex Smalley", comp:0.497, form:1.22, signal:"TAILWIND", app:0.279, ott:0.30, dd:4.9, arg:0.08, putt:-0.03, t10:13.1, spikes:"", flag:"" },
            { rank:29, name:"Davis Thompson", comp:0.457, form:1.23, signal:"TAILWIND", app:0.346, ott:0.40, dd:3.4, arg:0.04, putt:-0.12, t10:12.5, spikes:"", flag:"" },
            { rank:30, name:"Stephan Jaeger", comp:0.447, form:1.31, signal:"TAILWIND", app:0.095, ott:-0.22, dd:5.7, arg:0.27, putt:0.26, t10:12.9, spikes:"", flag:"ON CARD" },
            { rank:36, name:"Max Greyserman", comp:0.390, form:1.19, signal:"warm", app:0.089, ott:-0.23, dd:6.5, arg:0.17, putt:0.40, t10:10.1, spikes:"", flag:"ON CARD" },
            { rank:38, name:"Tony Finau", comp:0.364, form:1.30, signal:"TAILWIND", app:0.171, ott:-0.30, dd:3.6, arg:0.29, putt:0.08, t10:9.3, spikes:"", flag:"FADE" },
        ],
        // RH model ranks for top players
        rhModels: [
            { name:"Chris Gotterup", m15:10, m16:3, m17:1, m18:10, m19:2, meta:5 },
            { name:"Nicolai Hojgaard", m15:3, m16:4, m17:3, m18:2, m19:1, meta:3 },
            { name:"Kurt Kitayama", m15:1, m16:1, m17:5, m18:7, m19:13, meta:5 },
            { name:"Jake Knapp", m15:6, m16:7, m17:2, m18:25, m19:25, meta:12 },
            { name:"Adam Scott", m15:8, m16:5, m17:6, m18:1, m19:3, meta:5 },
            { name:"Keith Mitchell", m15:13, m16:2, m17:12, m18:9, m19:9, meta:9 },
            { name:"Pierceson Coody", m15:12, m16:6, m17:9, m18:26, m19:16, meta:14 },
            { name:"Michael Thorbjornsen", m15:9, m16:24, m17:24, m18:35, m19:27, meta:24 },
            { name:"Ben Griffin", m15:30, m16:23, m17:23, m18:19, m19:8, meta:21 },
            { name:"Rasmus Hojgaard", m15:5, m16:33, m17:33, m18:46, m19:7, meta:25 },
            { name:"Sam Burns", m15:18, m16:31, m17:31, m18:12, m19:12, meta:21 },
            { name:"Wyndham Clark", m15:21, m16:18, m17:18, m18:3, m19:31, meta:18 },
            { name:"Sahith Theegala", m15:74, m16:8, m17:8, m18:4, m19:15, meta:22 },
            { name:"Stephan Jaeger", m15:38, m16:26, m17:26, m18:14, m19:14, meta:24 },
            { name:"Max Greyserman", m15:63, m16:40, m17:63, m18:49, m19:40, meta:51 },
            { name:"Tony Finau", m15:56, m16:19, m17:19, m18:16, m19:80, meta:38 },
            { name:"Marco Penge", m15:11, m16:78, m17:78, m18:116, m19:61, meta:69 },
        ],
        // Form signals (DG baseline vs bhf)
        formSignals: [
            { name:"Stephan Jaeger", base:1.00, bhf:1.31, signal:"TAILWIND" },
            { name:"Tony Finau", base:0.62, bhf:0.80, signal:"TAILWIND" },
            { name:"Wyndham Clark", base:1.58, bhf:2.04, signal:"TAILWIND" },
            { name:"Davis Thompson", base:1.15, bhf:1.42, signal:"TAILWIND" },
            { name:"Alex Smalley", base:1.10, bhf:1.34, signal:"TAILWIND" },
            { name:"Keith Mitchell", base:1.83, bhf:2.18, signal:"warm" },
            { name:"Nicolai Hojgaard", base:2.89, bhf:3.36, signal:"warm" },
            { name:"Pierceson Coody", base:1.43, bhf:1.65, signal:"warm" },
            { name:"Chris Gotterup", base:2.94, bhf:3.36, signal:"warm" },
            { name:"Adam Scott", base:1.62, bhf:1.71, signal:"warm" },
            { name:"Kurt Kitayama", base:2.82, bhf:3.02, signal:"warm" },
            { name:"Ben Griffin", base:2.15, bhf:2.38, signal:"warm" },
            { name:"Max Greyserman", base:0.86, bhf:1.02, signal:"warm" },
            { name:"Ryan Gerard", base:2.84, bhf:2.74, signal:"neutral" },
            { name:"Sam Burns", base:2.66, bhf:3.04, signal:"warm" },
            { name:"Min Woo Lee", base:5.21, bhf:6.03, signal:"warm" },
            { name:"Brooks Koepka", base:1.75, bhf:1.76, signal:"neutral" },
        ],
        // Weakness-masked analysis
        weaknessMasked: [
            { name:"Stephan Jaeger", weakness:"OTT -0.224", masked:"YES (1.25in rough)", strength:"ARG +0.270", amplified:"YES (67% short grass)", rank:30, form:"TAILWIND 1.31x", verdict:"Course history + masked" },
            { name:"Max Greyserman", weakness:"OTT -0.234", masked:"YES (1.25in rough)", strength:"PUTT +0.403", amplified:"YES (Poa putting)", rank:36, form:"warm 1.19x", verdict:"T7 2024 + masked" },
            { name:"Tony Finau", weakness:"OTT -0.304", masked:"YES (1.25in rough)", strength:"ARG +0.288", amplified:"YES (short grass)", rank:38, form:"TAILWIND 1.30x", verdict:"2022 winner but overpriced" },
            { name:"Wyndham Clark", weakness:"OTT +0.05 (avg)", masked:"N/A", strength:"ARG +0.246", amplified:"YES (short grass)", rank:14, form:"TAILWIND 1.29x", verdict:"T5 2025 + form surge" },
            { name:"Keith Mitchell", weakness:"ARG -0.03", masked:"Partial", strength:"APP+OTT double", amplified:"YES (both amplified)", rank:7, form:"warm 1.19x", verdict:"Double-fit rare player" },
            { name:"Ben Griffin", weakness:"OTT -0.03", masked:"Mild", strength:"ARG +0.27 + PUTT +0.42", amplified:"YES (short game)", rank:19, form:"warm 1.11x", verdict:"Short-game specialist" },
        ],
        // Narrative source matrix
        narratives: [
            { name:"Nicolai Hojgaard", noonan:true, klos:false, mayo:true, stewart:true, titanic:true, count:4, rank:2 },
            { name:"Kurt Kitayama", noonan:true, klos:false, mayo:true, stewart:false, titanic:false, count:2, rank:3 },
            { name:"Ryan Gerard", noonan:true, klos:false, mayo:false, stewart:true, titanic:false, count:2, rank:10 },
            { name:"Chris Gotterup", noonan:false, klos:false, mayo:true, stewart:true, titanic:true, count:3, rank:1 },
            { name:"Adam Scott", noonan:true, klos:false, mayo:false, stewart:false, titanic:false, count:1, rank:6 },
            { name:"Keith Mitchell", noonan:false, klos:false, mayo:false, stewart:true, titanic:false, count:1, rank:7 },
            { name:"Ryan Fox", noonan:true, klos:false, mayo:false, stewart:true, titanic:true, count:3, rank:17 },
            { name:"Wyndham Clark", noonan:false, klos:false, mayo:true, stewart:false, titanic:true, count:2, rank:14 },
            { name:"Stephan Jaeger", noonan:false, klos:false, mayo:false, stewart:false, titanic:true, count:1, rank:30 },
            { name:"Max Greyserman", noonan:false, klos:false, mayo:false, stewart:false, titanic:true, count:1, rank:36 },
            { name:"Michael Brennan", noonan:false, klos:false, mayo:true, stewart:true, titanic:true, count:3, rank:45 },
        ],
        // Radar chart axes match the course stat fingerprint
        radarAxes: ["APP", "Distance", "ARG (Short Grass)", "OTT (Driver)", "Bogey Avd", "PUTT (Poa)"],
        // Winner profile = average of past winners normalized to 0-100 scale
        winnerProfile: [85, 78, 72, 65, 70, 55],
        // Player profiles on same axes (0-100 scale, higher = better fit)
        radarPlayers: {
            "Nicolai Hojgaard": [78, 82, 48, 72, 75, 68],
            "Kurt Kitayama": [95, 72, 48, 80, 72, 38],
            "Adam Scott": [88, 65, 52, 68, 70, 45],
            "Keith Mitchell": [75, 70, 46, 82, 65, 40],
            "Wyndham Clark": [62, 65, 72, 52, 68, 48],
            "Stephan Jaeger": [42, 58, 78, 35, 62, 70],
            "Max Greyserman": [38, 60, 65, 32, 55, 85],
            "Chris Gotterup": [72, 88, 55, 80, 70, 58],
            "Jake Knapp": [45, 80, 52, 75, 68, 88],
            "Min Woo Lee": [58, 80, 78, 82, 75, 80],
            "Pierceson Coody": [60, 82, 35, 80, 62, 50],
            "Sam Burns": [48, 65, 50, 68, 72, 88],
            "Rasmus Hojgaard": [45, 82, 42, 55, 58, 82],
            "Ben Griffin": [65, 42, 75, 40, 68, 82],
            "Ryan Gerard": [92, 45, 50, 78, 68, 42],
            "Sahith Theegala": [70, 52, 62, 48, 65, 65],
            "Tony Finau": [55, 55, 78, 28, 58, 55],
            "Michael Thorbjornsen": [62, 75, 52, 82, 62, 50],
            "Davis Thompson": [65, 55, 52, 72, 60, 38],
            "Alex Smalley": [58, 55, 55, 68, 60, 48],
            "Brooks Koepka": [78, 60, 48, 65, 58, 35],
            "Marco Penge": [45, 92, 32, 92, 55, 42],
            "Ryan Fox": [55, 68, 58, 55, 52, 60],
            "Wyndham Clark": [62, 65, 72, 52, 68, 48],
        },

        // Course history (TPC specific)
        courseHistory: [
            { rank:1, name:"Min Woo Lee", rounds:12, tot:1, app:2, arg:5, putt:8, ott:3, masters:"Y" },
            { rank:2, name:"Stephan Jaeger", rounds:8, tot:2, app:15, arg:3, putt:12, ott:18, masters:"N" },
            { rank:3, name:"Chris Gotterup", rounds:8, tot:3, app:8, arg:12, putt:5, ott:1, masters:"Y" },
            { rank:4, name:"Keith Mitchell", rounds:12, tot:4, app:18, arg:8, putt:22, ott:6, masters:"N" },
            { rank:5, name:"Ryan Gerard", rounds:8, tot:5, app:3, arg:15, putt:25, ott:10, masters:"Y" },
        ],
    }
};
